// Automatically generated by pgrx-c-macros for documentation. Do not hand-edit.
// C macros from bufmgr.h.

#[cfg(feature = "pg19")]
/// C macro BMR_GET_SMGR from bufmgr.h:118 (PostgreSQL 19)
///
/// ```text
/// #define BMR_GET_SMGR( bmr ) ( RelationIsValid ( ( bmr ) . rel ) ? RelationGetSmgr ( ( bmr ) . rel ) : ( bmr ) . smgr )
/// ```
///
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Conversions involving floats reject nonfinite or out-of-range integer results; conversions into Rust enums reject values without a represented discriminant. Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! BMR_GET_SMGR {
    ($bmr:expr $(,)?) => {
        ::core::unimplemented!("pgrx documentation snapshot; C macros are generated for each build")
    };
}
#[cfg(feature = "pg15")]
/// C macro BufferGetBlock from bufmgr.h:136 (PostgreSQL 15)
///
/// ```text
/// #define BufferGetBlock( buffer ) ( AssertMacro ( BufferIsValid ( buffer ) ) , BufferIsLocal ( buffer ) ? LocalBufferBlockPointers [ - ( buffer ) - 1 ] : ( Block ) ( BufferBlocks + ( ( Size ) ( ( buffer ) - 1 ) ) * BLCKSZ ) )
/// ```
///
///
/// Invocation diagnostics use Rust `file!()` and `line!()` at the outer Rust source invocation. The filename is a static UTF-8 byte array with a final zero; the line must fit the inspected C int. Source-line-dependent C preprocessing and integer-constant-expression identity are outside this diagnostic contract.
///
/// Dependency stringification retains the compiler-expanded C diagnostic template and uses Rust `stringify!` on the original outer Rust operand tokens. It never evaluates those tokens. Operand spelling follows Rust whitespace and token rendering, requires ASCII, and preserves all groups and punctuation; it does not promise C preprocessor stringification for Rust-specific syntax. Such strings are static zero-terminated native const-char arguments only. Their C array extent, address, integer-constant-expression identity and return as a string value are unsupported. Root macros containing # remain explicit skips. String arrays retain their complete char-array extent for size and address operations, and decay to read-only pointers for values. Literal mutation is rejected because C string-literal writes are undefined.
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Checked signed arithmetic rejects overflow when the recorded C profile does not define wrapping. Checked signed arithmetic rejects overflow when the recorded C profile does not define wrapping; pointer arithmetic checks representable offsets and distances but still requires valid allocation bounds. Conversions involving floats reject nonfinite or out-of-range integer results; conversions into Rust enums reject values without a represented discriminant. Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! BufferGetBlock {
    ($buffer:expr $(,)?) => {
        ::core::unimplemented!("pgrx documentation snapshot; C macros are generated for each build")
    };
}
#[cfg(any(feature = "pg16", feature = "pg17", feature = "pg18", feature = "pg19"))]
/// Typed call adapter for C inline function BufferGetBlock from bufmgr.h:321 (PostgreSQL 16), bufmgr.h:373 (PostgreSQL 17), bufmgr.h:383 (PostgreSQL 18), bufmgr.h:434 (PostgreSQL 19)
///
/// ```c
/// static inline Block
/// BufferGetBlock(Buffer buffer)
/// {
/// 	Assert(BufferIsValid(buffer));
///
/// 	if (BufferIsLocal(buffer))
/// 		return LocalBufferBlockPointers[-buffer - 1];
/// 	else
/// 		return (Block) (BufferBlocks + ((Size) (buffer - 1)) * BLCKSZ);
/// }
/// ```
///
///
/// Calls the original function through its inspected C prototype. Each operand is evaluated once and converted using C parameter assignment rules. The result retains the function's original C type; `.get()` extracts its native storage, including `()` for a void result. Native calls retain the backend thread, PostgreSQL error, and caller safety contracts of the generated guarded binding.
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! BufferGetBlock {
    ($buffer:expr $(,)?) => {
        ::core::unimplemented!("pgrx documentation snapshot; C macros are generated for each build")
    };
}
#[cfg(feature = "pg15")]
/// C macro BufferGetPage from bufmgr.h:169 (PostgreSQL 15)
///
/// ```text
/// #define BufferGetPage( buffer ) ( ( Page ) BufferGetBlock ( buffer ) )
/// ```
///
///
/// Invocation diagnostics use Rust `file!()` and `line!()` at the outer Rust source invocation. The filename is a static UTF-8 byte array with a final zero; the line must fit the inspected C int. Source-line-dependent C preprocessing and integer-constant-expression identity are outside this diagnostic contract.
///
/// Dependency stringification retains the compiler-expanded C diagnostic template and uses Rust `stringify!` on the original outer Rust operand tokens. It never evaluates those tokens. Operand spelling follows Rust whitespace and token rendering, requires ASCII, and preserves all groups and punctuation; it does not promise C preprocessor stringification for Rust-specific syntax. Such strings are static zero-terminated native const-char arguments only. Their C array extent, address, integer-constant-expression identity and return as a string value are unsupported. Root macros containing # remain explicit skips. String arrays retain their complete char-array extent for size and address operations, and decay to read-only pointers for values. Literal mutation is rejected because C string-literal writes are undefined.
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Checked signed arithmetic rejects overflow when the recorded C profile does not define wrapping. Checked signed arithmetic rejects overflow when the recorded C profile does not define wrapping; pointer arithmetic checks representable offsets and distances but still requires valid allocation bounds. Conversions involving floats reject nonfinite or out-of-range integer results; conversions into Rust enums reject values without a represented discriminant. Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! BufferGetPage {
    ($buffer:expr $(,)?) => {
        ::core::unimplemented!("pgrx documentation snapshot; C macros are generated for each build")
    };
}
#[cfg(any(feature = "pg16", feature = "pg17", feature = "pg18", feature = "pg19"))]
/// Typed call adapter for C inline function BufferGetPage from bufmgr.h:357 (PostgreSQL 16), bufmgr.h:406 (PostgreSQL 17), bufmgr.h:416 (PostgreSQL 18), bufmgr.h:467 (PostgreSQL 19)
///
/// ```c
/// static inline Page
/// BufferGetPage(Buffer buffer)
/// {
/// 	return (Page) BufferGetBlock(buffer);
/// }
/// ```
///
///
/// Calls the original function through its inspected C prototype. Each operand is evaluated once and converted using C parameter assignment rules. The result retains the function's original C type; `.get()` extracts its native storage, including `()` for a void result. Native calls retain the backend thread, PostgreSQL error, and caller safety contracts of the generated guarded binding.
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! BufferGetPage {
    ($buffer:expr $(,)?) => {
        ::core::unimplemented!("pgrx documentation snapshot; C macros are generated for each build")
    };
}
#[cfg(feature = "pg15")]
/// C macro BufferGetPageSize from bufmgr.h:156 (PostgreSQL 15)
///
/// ```text
/// #define BufferGetPageSize( buffer ) ( AssertMacro ( BufferIsValid ( buffer ) ) , ( Size ) BLCKSZ )
/// ```
///
///
/// Invocation diagnostics use Rust `file!()` and `line!()` at the outer Rust source invocation. The filename is a static UTF-8 byte array with a final zero; the line must fit the inspected C int. Source-line-dependent C preprocessing and integer-constant-expression identity are outside this diagnostic contract.
///
/// Dependency stringification retains the compiler-expanded C diagnostic template and uses Rust `stringify!` on the original outer Rust operand tokens. It never evaluates those tokens. Operand spelling follows Rust whitespace and token rendering, requires ASCII, and preserves all groups and punctuation; it does not promise C preprocessor stringification for Rust-specific syntax. Such strings are static zero-terminated native const-char arguments only. Their C array extent, address, integer-constant-expression identity and return as a string value are unsupported. Root macros containing # remain explicit skips. String arrays retain their complete char-array extent for size and address operations, and decay to read-only pointers for values. Literal mutation is rejected because C string-literal writes are undefined.
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Checked signed arithmetic rejects overflow when the recorded C profile does not define wrapping. Conversions involving floats reject nonfinite or out-of-range integer results; conversions into Rust enums reject values without a represented discriminant. Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! BufferGetPageSize {
    ($buffer:expr $(,)?) => {
        ::core::unimplemented!("pgrx documentation snapshot; C macros are generated for each build")
    };
}
#[cfg(any(feature = "pg16", feature = "pg17"))]
/// Typed call adapter for C inline function BufferGetPageSize from bufmgr.h:343 (PostgreSQL 16), bufmgr.h:395 (PostgreSQL 17)
///
/// ```c
/// static inline Size
/// BufferGetPageSize(Buffer buffer)
/// {
/// 	AssertMacro(BufferIsValid(buffer));
/// 	return (Size) BLCKSZ;
/// }
/// ```
///
///
/// Calls the original function through its inspected C prototype. Each operand is evaluated once and converted using C parameter assignment rules. The result retains the function's original C type; `.get()` extracts its native storage, including `()` for a void result. Native calls retain the backend thread, PostgreSQL error, and caller safety contracts of the generated guarded binding.
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! BufferGetPageSize {
    ($buffer:expr $(,)?) => {
        ::core::unimplemented!("pgrx documentation snapshot; C macros are generated for each build")
    };
}
#[cfg(any(feature = "pg18", feature = "pg19"))]
/// Typed call adapter for C inline function BufferGetPageSize from bufmgr.h:405 (PostgreSQL 18), bufmgr.h:456 (PostgreSQL 19)
///
/// ```c
/// static inline Size
/// BufferGetPageSize(Buffer buffer)
/// {
/// 	Assert(BufferIsValid(buffer));
/// 	return (Size) BLCKSZ;
/// }
/// ```
///
///
/// Calls the original function through its inspected C prototype. Each operand is evaluated once and converted using C parameter assignment rules. The result retains the function's original C type; `.get()` extracts its native storage, including `()` for a void result. Native calls retain the backend thread, PostgreSQL error, and caller safety contracts of the generated guarded binding.
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! BufferGetPageSize {
    ($buffer:expr $(,)?) => {
        ::core::unimplemented!("pgrx documentation snapshot; C macros are generated for each build")
    };
}
#[cfg(feature = "pg15")]
/// C macro BufferIsValid from bufmgr.h:123 (PostgreSQL 15)
///
/// ```text
/// #define BufferIsValid( bufnum ) ( AssertMacro ( ( bufnum ) <= NBuffers && ( bufnum ) >= - NLocBuffer ) , ( bufnum ) != InvalidBuffer )
/// ```
///
///
/// Invocation diagnostics use Rust `file!()` and `line!()` at the outer Rust source invocation. The filename is a static UTF-8 byte array with a final zero; the line must fit the inspected C int. Source-line-dependent C preprocessing and integer-constant-expression identity are outside this diagnostic contract.
///
/// Dependency stringification retains the compiler-expanded C diagnostic template and uses Rust `stringify!` on the original outer Rust operand tokens. It never evaluates those tokens. Operand spelling follows Rust whitespace and token rendering, requires ASCII, and preserves all groups and punctuation; it does not promise C preprocessor stringification for Rust-specific syntax. Such strings are static zero-terminated native const-char arguments only. Their C array extent, address, integer-constant-expression identity and return as a string value are unsupported. Root macros containing # remain explicit skips. String arrays retain their complete char-array extent for size and address operations, and decay to read-only pointers for values. Literal mutation is rejected because C string-literal writes are undefined.
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Checked signed arithmetic rejects overflow when the recorded C profile does not define wrapping. Conversions involving floats reject nonfinite or out-of-range integer results; conversions into Rust enums reject values without a represented discriminant. Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! BufferIsValid {
    ($bufnum:expr $(,)?) => {
        ::core::unimplemented!("pgrx documentation snapshot; C macros are generated for each build")
    };
}
#[cfg(any(feature = "pg16", feature = "pg17", feature = "pg18", feature = "pg19"))]
/// Typed call adapter for C inline function BufferIsValid from bufmgr.h:305 (PostgreSQL 16), bufmgr.h:357 (PostgreSQL 17), bufmgr.h:367 (PostgreSQL 18), bufmgr.h:418 (PostgreSQL 19)
///
/// ```c
/// static inline bool
/// BufferIsValid(Buffer bufnum)
/// {
/// 	Assert(bufnum <= NBuffers);
/// 	Assert(bufnum >= -NLocBuffer);
///
/// 	return bufnum != InvalidBuffer;
/// }
/// ```
///
///
/// Calls the original function through its inspected C prototype. Each operand is evaluated once and converted using C parameter assignment rules. The result retains the function's original C type; `.get()` extracts its native storage, including `()` for a void result. Native calls retain the backend thread, PostgreSQL error, and caller safety contracts of the generated guarded binding.
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! BufferIsValid {
    ($bufnum:expr $(,)?) => {
        ::core::unimplemented!("pgrx documentation snapshot; C macros are generated for each build")
    };
}
#[cfg(feature = "pg19")]
/// Typed call adapter for C inline function LockBuffer from bufmgr.h:333 (PostgreSQL 19)
///
/// ```c
/// static inline void
/// LockBuffer(Buffer buffer, BufferLockMode mode)
/// {
/// 	if (mode == BUFFER_LOCK_UNLOCK)
/// 		UnlockBuffer(buffer);
/// 	else
/// 		LockBufferInternal(buffer, mode);
/// }
/// ```
///
///
/// Calls the original function through its inspected C prototype. Each operand is evaluated once and converted using C parameter assignment rules. The result retains the function's original C type; `.get()` extracts its native storage, including `()` for a void result. Native calls retain the backend thread, PostgreSQL error, and caller safety contracts of the generated guarded binding.
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! LockBuffer {
    ($buffer:expr, $mode:expr $(,)?) => {
        ::core::unimplemented!("pgrx documentation snapshot; C macros are generated for each build")
    };
}
/// C macro RelationGetNumberOfBlocks from bufmgr.h:219 (PostgreSQL 15), bufmgr.h:230 (PostgreSQL 16), bufmgr.h:280 (PostgreSQL 17), bufmgr.h:283 (PostgreSQL 18), bufmgr.h:309 (PostgreSQL 19)
///
/// ```text
/// #define RelationGetNumberOfBlocks( reln ) RelationGetNumberOfBlocksInFork ( reln , MAIN_FORKNUM )
/// ```
///
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! RelationGetNumberOfBlocks {
    ($reln:expr $(,)?) => {
        ::core::unimplemented!("pgrx documentation snapshot; C macros are generated for each build")
    };
}
#[cfg(any(feature = "pg15", feature = "pg16"))]
/// Typed call adapter for C inline function TestForOldSnapshot from bufmgr.h:284 (PostgreSQL 15), bufmgr.h:380 (PostgreSQL 16)
///
/// ```c
/// static inline void
/// TestForOldSnapshot(Snapshot snapshot, Relation relation, Page page)
/// {
/// 	Assert(relation != NULL);
///
/// 	if (old_snapshot_threshold >= 0
/// 		&& (snapshot) != NULL
/// 		&& ((snapshot)->snapshot_type == SNAPSHOT_MVCC
/// 			|| (snapshot)->snapshot_type == SNAPSHOT_TOAST)
/// 		&& !XLogRecPtrIsInvalid((snapshot)->lsn)
/// 		&& PageGetLSN(page) > (snapshot)->lsn)
/// 		TestForOldSnapshot_impl(snapshot, relation);
/// }
/// ```
///
///
/// Calls the original function through its inspected C prototype. Each operand is evaluated once and converted using C parameter assignment rules. The result retains the function's original C type; `.get()` extracts its native storage, including `()` for a void result. Native calls retain the backend thread, PostgreSQL error, and caller safety contracts of the generated guarded binding.
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! TestForOldSnapshot {
    ($snapshot:expr, $relation:expr, $page:expr $(,)?) => {
        ::core::unimplemented!("pgrx documentation snapshot; C macros are generated for each build")
    };
}
#[cfg(feature = "pg19")]
pub use BMR_GET_SMGR;
pub use BufferGetBlock;
pub use BufferGetPage;
pub use BufferGetPageSize;
pub use BufferIsValid;
#[cfg(feature = "pg19")]
pub use LockBuffer;
pub use RelationGetNumberOfBlocks;
#[cfg(any(feature = "pg15", feature = "pg16"))]
pub use TestForOldSnapshot;
