// Automatically generated by pgrx-c-macros for documentation. Do not hand-edit.
// C macros from shm_toc.h.

/// C macro shm_toc_estimate_chunk from shm_toc.h:51 (PostgreSQL 15–19)
///
/// ```text
/// #define shm_toc_estimate_chunk( e , sz ) ( ( e ) -> space_for_chunks = add_size ( ( e ) -> space_for_chunks , BUFFERALIGN ( sz ) ) )
/// ```
///
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Checked signed arithmetic rejects overflow when the recorded C profile does not define wrapping; pointer arithmetic checks representable offsets and distances but still requires valid allocation bounds. Conversions involving floats reject nonfinite or out-of-range integer results; conversions into Rust enums reject values without a represented discriminant. Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! shm_toc_estimate_chunk {
    ($e:expr, $sz:expr $(,)?) => {
        ::core::unimplemented!("pgrx documentation snapshot; C macros are generated for each build")
    };
}
/// C macro shm_toc_estimate_keys from shm_toc.h:53 (PostgreSQL 15–19)
///
/// ```text
/// #define shm_toc_estimate_keys( e , cnt ) ( ( e ) -> number_of_keys = add_size ( ( e ) -> number_of_keys , cnt ) )
/// ```
///
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! shm_toc_estimate_keys {
    ($e:expr, $cnt:expr $(,)?) => {
        ::core::unimplemented!("pgrx documentation snapshot; C macros are generated for each build")
    };
}
/// C macro shm_toc_initialize_estimator from shm_toc.h:49 (PostgreSQL 15–19)
///
/// ```text
/// #define shm_toc_initialize_estimator( e ) ( ( e ) -> space_for_chunks = 0 , ( e ) -> number_of_keys = 0 )
/// ```
///
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
#[macro_export]
macro_rules! shm_toc_initialize_estimator {
    ($e:expr $(,)?) => {
        ::core::unimplemented!("pgrx documentation snapshot; C macros are generated for each build")
    };
}
pub use shm_toc_estimate_chunk;
pub use shm_toc_estimate_keys;
pub use shm_toc_initialize_estimator;
