// Automatically generated by pgrx-c-macros for documentation. Do not hand-edit.
// C macros from smgr.h.

#[cfg(feature = "pg15")]
/// C macro SmgrIsTemp from smgr.h:77 (PostgreSQL 15)
///
/// ```text
/// #define SmgrIsTemp( smgr ) RelFileNodeBackendIsTemp ( ( smgr ) -> smgr_rnode )
/// ```
///
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
#[macro_export]
macro_rules! SmgrIsTemp {
    ($smgr:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(any(feature = "pg16", feature = "pg17", feature = "pg18", feature = "pg19"))]
/// C macro SmgrIsTemp from smgr.h:77 (PostgreSQL 16), smgr.h:73 (PostgreSQL 17), smgr.h:74 (PostgreSQL 18–19)
///
/// ```text
/// #define SmgrIsTemp( smgr ) RelFileLocatorBackendIsTemp ( ( smgr ) -> smgr_rlocator )
/// ```
///
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
#[macro_export]
macro_rules! SmgrIsTemp {
    ($smgr:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(any(feature = "pg17", feature = "pg18", feature = "pg19"))]
/// Typed call adapter for C inline function smgrread from smgr.h:116 (PostgreSQL 17), smgr.h:123 (PostgreSQL 18–19)
///
/// ```c
/// static inline void
/// smgrread(SMgrRelation reln, ForkNumber forknum, BlockNumber blocknum,
/// 		 void *buffer)
/// {
/// 	smgrreadv(reln, forknum, blocknum, &buffer, 1);
/// }
/// ```
///
///
#[doc = crate::__pgrx_c_doc_inline_call!()]
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! smgrread {
    ($reln:expr, $forknum:expr, $blocknum:expr, $buffer:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(any(feature = "pg17", feature = "pg18", feature = "pg19"))]
/// Typed call adapter for C inline function smgrwrite from smgr.h:123 (PostgreSQL 17), smgr.h:130 (PostgreSQL 18–19)
///
/// ```c
/// static inline void
/// smgrwrite(SMgrRelation reln, ForkNumber forknum, BlockNumber blocknum,
/// 		  const void *buffer, bool skipFsync)
/// {
/// 	smgrwritev(reln, forknum, blocknum, &buffer, 1, skipFsync);
/// }
/// ```
///
///
#[doc = crate::__pgrx_c_doc_inline_call!()]
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! smgrwrite {
    ($reln:expr, $forknum:expr, $blocknum:expr, $buffer:expr, $skipFsync:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
pub use SmgrIsTemp;
#[cfg(any(feature = "pg17", feature = "pg18", feature = "pg19"))]
pub use smgrread;
#[cfg(any(feature = "pg17", feature = "pg18", feature = "pg19"))]
pub use smgrwrite;
