// Automatically generated by pgrx-c-macros for documentation. Do not hand-edit.
// C macros from relpath.h.

#[cfg(any(feature = "pg16", feature = "pg17", feature = "pg18", feature = "pg19"))]
/// C macro RelFileNumberIsValid from relpath.h:27 (PostgreSQL 16–19)
///
/// ```text
/// #define RelFileNumberIsValid( relnumber ) ( ( bool ) ( ( relnumber ) != InvalidRelFileNumber ) )
/// ```
///
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Conversions involving floats reject nonfinite or out-of-range integer results; conversions into Rust enums reject values without a represented discriminant. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! RelFileNumberIsValid {
    ($relnumber:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(feature = "pg15")]
/// C macro relpath from relpath.h:87 (PostgreSQL 15)
///
/// ```text
/// #define relpath( rnode , forknum ) relpathbackend ( ( rnode ) . node , ( rnode ) . backend , forknum )
/// ```
///
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! relpath {
    ($rnode:expr, $forknum:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(any(feature = "pg16", feature = "pg17", feature = "pg18", feature = "pg19"))]
/// C macro relpath from relpath.h:94 (PostgreSQL 16–17), relpath.h:151 (PostgreSQL 18–19)
///
/// ```text
/// #define relpath( rlocator , forknum ) relpathbackend ( ( rlocator ) . locator , ( rlocator ) . backend , forknum )
/// ```
///
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! relpath {
    ($rlocator:expr, $forknum:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(feature = "pg15")]
/// C macro relpathbackend from relpath.h:78 (PostgreSQL 15)
///
/// ```text
/// #define relpathbackend( rnode , backend , forknum ) GetRelationPath ( ( rnode ) . dbNode , ( rnode ) . spcNode , ( rnode ) . relNode , backend , forknum )
/// ```
///
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! relpathbackend {
    ($rnode:expr, $backend:expr, $forknum:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(any(feature = "pg16", feature = "pg17", feature = "pg18", feature = "pg19"))]
/// C macro relpathbackend from relpath.h:85 (PostgreSQL 16–17), relpath.h:142 (PostgreSQL 18–19)
///
/// ```text
/// #define relpathbackend( rlocator , backend , forknum ) GetRelationPath ( ( rlocator ) . dbOid , ( rlocator ) . spcOid , ( rlocator ) . relNumber , backend , forknum )
/// ```
///
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! relpathbackend {
    ($rlocator:expr, $backend:expr, $forknum:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(feature = "pg15")]
/// C macro relpathperm from relpath.h:83 (PostgreSQL 15)
///
/// ```text
/// #define relpathperm( rnode , forknum ) relpathbackend ( rnode , InvalidBackendId , forknum )
/// ```
///
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! relpathperm {
    ($rnode:expr, $forknum:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(feature = "pg16")]
/// C macro relpathperm from relpath.h:90 (PostgreSQL 16)
///
/// ```text
/// #define relpathperm( rlocator , forknum ) relpathbackend ( rlocator , InvalidBackendId , forknum )
/// ```
///
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! relpathperm {
    ($rlocator:expr, $forknum:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(any(feature = "pg17", feature = "pg18", feature = "pg19"))]
/// C macro relpathperm from relpath.h:90 (PostgreSQL 17), relpath.h:147 (PostgreSQL 18–19)
///
/// ```text
/// #define relpathperm( rlocator , forknum ) relpathbackend ( rlocator , INVALID_PROC_NUMBER , forknum )
/// ```
///
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! relpathperm {
    ($rlocator:expr, $forknum:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(any(feature = "pg16", feature = "pg17", feature = "pg18", feature = "pg19"))]
pub use RelFileNumberIsValid;
pub use relpath;
pub use relpathbackend;
pub use relpathperm;
