// Automatically generated by pgrx-c-macros for documentation. Do not hand-edit.
// C macros from syncrep.h.

/// C macro SyncRepRequested from syncrep.h:19 (PostgreSQL 15), syncrep.h:18 (PostgreSQL 16–19)
///
/// ```text
/// #define SyncRepRequested( ) ( max_wal_senders > 0 && synchronous_commit > SYNCHRONOUS_COMMIT_LOCAL_FLUSH )
/// ```
///
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
#[macro_export]
macro_rules! SyncRepRequested {
    () => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
pub use SyncRepRequested;
