// Automatically generated by pgrx-c-macros for documentation. Do not hand-edit.
// C macros from walsender.h.

#[cfg(feature = "pg15")]
/// C macro WalSndWakeupProcessRequests from walsender.h:63 (PostgreSQL 15)
///
/// ```text
/// #define WalSndWakeupProcessRequests( ) do { if ( wake_wal_senders ) { wake_wal_senders = false ; if ( max_wal_senders > 0 ) WalSndWakeup ( ) ; } } while ( 0 )
/// ```
///
///
/// This macro executes C statements in order and yields no value. Local blocks retain their C scope. Pointer access and native calls keep their usual caller safety obligations.
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! WalSndWakeupProcessRequests {
    () => {
        ::core::unimplemented!("pgrx documentation snapshot; C macros are generated for each build")
    };
}
#[cfg(any(feature = "pg16", feature = "pg17", feature = "pg18", feature = "pg19"))]
/// Typed call adapter for C inline function WalSndWakeupProcessRequests from walsender.h:63 (PostgreSQL 16, 19), walsender.h:65 (PostgreSQL 17), walsender.h:64 (PostgreSQL 18)
///
/// ```c
/// static inline void
/// WalSndWakeupProcessRequests(bool physical, bool logical)
/// {
/// 	if (wake_wal_senders)
/// 	{
/// 		wake_wal_senders = false;
/// 		if (max_wal_senders > 0)
/// 			WalSndWakeup(physical, logical);
/// 	}
/// }
/// ```
///
///
/// Calls the original function through its inspected C prototype. Each operand is evaluated once and converted using C parameter assignment rules. The result retains the function's original C type; `.get()` extracts its native storage, including `()` for a void result. Native calls retain the backend thread, PostgreSQL error, and caller safety contracts of the generated guarded binding.
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! WalSndWakeupProcessRequests {
    ($physical:expr, $logical:expr $(,)?) => {
        ::core::unimplemented!("pgrx documentation snapshot; C macros are generated for each build")
    };
}
/// C macro WalSndWakeupRequest from walsender.h:57 (PostgreSQL 15–16, 19), walsender.h:59 (PostgreSQL 17), walsender.h:58 (PostgreSQL 18)
///
/// ```text
/// #define WalSndWakeupRequest( ) do { wake_wal_senders = true ; } while ( 0 )
/// ```
///
///
/// This macro executes C statements in order and yields no value. Local blocks retain their C scope. Pointer access and native calls keep their usual caller safety obligations.
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
#[macro_export]
macro_rules! WalSndWakeupRequest {
    () => {
        ::core::unimplemented!("pgrx documentation snapshot; C macros are generated for each build")
    };
}
pub use WalSndWakeupProcessRequests;
pub use WalSndWakeupRequest;
