// Automatically generated by pgrx-c-macros for documentation. Do not hand-edit.
// C macros from extendplan.h.

#[cfg(feature = "pg19")]
/// Typed call adapter for C inline function GetPlannerGlobalExtensionState from extendplan.h:24 (PostgreSQL 19)
///
/// ```c
/// static inline void *
/// GetPlannerGlobalExtensionState(PlannerGlobal *glob, int extension_id)
/// {
/// 	Assert(extension_id >= 0);
///
/// 	if (extension_id >= glob->extension_state_allocated)
/// 		return NULL;
///
/// 	return glob->extension_state[extension_id];
/// }
/// ```
///
///
/// Calls the original function through its inspected C prototype. Each operand is evaluated once and converted using C parameter assignment rules. The result retains the function's original C type; `.get()` extracts its native storage, including `()` for a void result. Native calls retain the backend thread, PostgreSQL error, and caller safety contracts of the generated guarded binding.
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! GetPlannerGlobalExtensionState {
    ($glob:expr, $extension_id:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(feature = "pg19")]
/// Typed call adapter for C inline function GetPlannerInfoExtensionState from extendplan.h:38 (PostgreSQL 19)
///
/// ```c
/// static inline void *
/// GetPlannerInfoExtensionState(PlannerInfo *root, int extension_id)
/// {
/// 	Assert(extension_id >= 0);
///
/// 	if (extension_id >= root->extension_state_allocated)
/// 		return NULL;
///
/// 	return root->extension_state[extension_id];
/// }
/// ```
///
///
/// Calls the original function through its inspected C prototype. Each operand is evaluated once and converted using C parameter assignment rules. The result retains the function's original C type; `.get()` extracts its native storage, including `()` for a void result. Native calls retain the backend thread, PostgreSQL error, and caller safety contracts of the generated guarded binding.
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! GetPlannerInfoExtensionState {
    ($root:expr, $extension_id:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(feature = "pg19")]
/// Typed call adapter for C inline function GetRelOptInfoExtensionState from extendplan.h:52 (PostgreSQL 19)
///
/// ```c
/// static inline void *
/// GetRelOptInfoExtensionState(RelOptInfo *rel, int extension_id)
/// {
/// 	Assert(extension_id >= 0);
///
/// 	if (extension_id >= rel->extension_state_allocated)
/// 		return NULL;
///
/// 	return rel->extension_state[extension_id];
/// }
/// ```
///
///
/// Calls the original function through its inspected C prototype. Each operand is evaluated once and converted using C parameter assignment rules. The result retains the function's original C type; `.get()` extracts its native storage, including `()` for a void result. Native calls retain the backend thread, PostgreSQL error, and caller safety contracts of the generated guarded binding.
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! GetRelOptInfoExtensionState {
    ($rel:expr, $extension_id:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(feature = "pg19")]
pub use GetPlannerGlobalExtensionState;
#[cfg(feature = "pg19")]
pub use GetPlannerInfoExtensionState;
#[cfg(feature = "pg19")]
pub use GetRelOptInfoExtensionState;
