/* Automatically generated by bindgen. Do not hand-edit.

This code is generated for documentation purposes, so that it is easy to reference on docs.rs. Bindings are regenerated for your build of pgrx, and the values of your Postgres version may differ.
*/
// C macros from multixact.h.

#[cfg(not(all(
    target_arch = "aarch64",
    target_os = "macos",
    target_pointer_width = "64",
    target_endian = "little"
)))]
#[cfg(not(docsrs))]
compile_error!("generated C macros require their inspected C target profile");
#[doc(hidden)]
#[macro_export]
macro_rules! __pgrx_c_args_ISUPDATE_from_mxstatus {
    (@collect $mode:ident [$($done:tt)*]; $($raw:tt)*) => {
        $crate::__pgrx_c_args_ISUPDATE_from_mxstatus!(@p0 $mode [$($done)*]; $($raw)*)
    };
    (@classified [$next:ident $mode:ident [$($done:tt)*] [$($rest:tt)*]] $descriptor:tt) => {
        $crate::__pgrx_c_args_ISUPDATE_from_mxstatus!(
            @$next $mode [$($done)* $descriptor,];
            $($rest)*
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; - $argument:literal) => {
        $crate::__pgrx_c_args_ISUPDATE_from_mxstatus!(
            @p1 $mode [$($done)* (@literal [- $argument]),];
        )
    };
    (@negative0 $mode:ident [$($done:tt)*]; $argument:expr) => {
        $crate::__pgrx_c_args_ISUPDATE_from_mxstatus!(@p1 $mode [$($done)* (@native [$argument]),];)
    };
    (@p0 $mode:ident [$($done:tt)*]; - $argument:literal, $($rest:tt)*) => {
        $crate::__pgrx_c_args_ISUPDATE_from_mxstatus!(
            @p1 $mode [$($done)* (@literal [- $argument]),];
            $($rest)*
        )
    };
    (@negative0 $mode:ident [$($done:tt)*]; $argument:expr, $($rest:tt)*) => {
        $crate::__pgrx_c_args_ISUPDATE_from_mxstatus!(
            @p1 $mode [$($done)* (@native [$argument]),];
            $($rest)*
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; - $($raw:tt)*) => {
        $crate::__pgrx_c_args_ISUPDATE_from_mxstatus!(@negative0 $mode [$($done)*]; - $($raw)*)
    };
    (@p0 $mode:ident [$($done:tt)*]; (@__pgrx_c_native [$argument:expr])) => {
        $crate::__pgrx_c_args_ISUPDATE_from_mxstatus!(@p1 $mode [$($done)* (@native [$argument]),];)
    };
    (@p0 $mode:ident [$($done:tt)*]; $head:ident $(::$tail:ident)* ! $group:tt) => {
        $crate::__pgrx_c_classify!(
            @argument [__pgrx_c_args_ISUPDATE_from_mxstatus] [p1 $mode [$($done)*] []] [
                $head $(::$tail)* ! $group
            ]
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; ::$head:ident $(::$tail:ident)* ! $group:tt) => {
        $crate::__pgrx_c_classify!(
            @argument [__pgrx_c_args_ISUPDATE_from_mxstatus] [p1 $mode [$($done)*] []] [
                ::$head $(::$tail)* ! $group
            ]
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; ($($inner:tt)*)) => {
        $crate::__pgrx_c_classify!(
            @argument [__pgrx_c_args_ISUPDATE_from_mxstatus] [p1 $mode [$($done)*] []] [
                ($($inner)*)
            ]
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; $argument:literal) => {
        $crate::__pgrx_c_args_ISUPDATE_from_mxstatus!(
            @p1 $mode [$($done)* (@literal [$argument]),];
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; $argument:expr) => {
        $crate::__pgrx_c_args_ISUPDATE_from_mxstatus!(@p1 $mode [$($done)* (@native [$argument]),];)
    };
    (@p0 $mode:ident [$($done:tt)*]; (@__pgrx_c_native [$argument:expr]), $($rest:tt)*) => {
        $crate::__pgrx_c_args_ISUPDATE_from_mxstatus!(
            @p1 $mode [$($done)* (@native [$argument]),];
            $($rest)*
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; $head:ident $(::$tail:ident)* ! $group:tt, $($rest:tt)*) => {
        $crate::__pgrx_c_classify!(
            @argument [__pgrx_c_args_ISUPDATE_from_mxstatus] [p1 $mode [$($done)*] [$($rest)*]] [
                $head $(::$tail)* ! $group
            ]
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; ::$head:ident $(::$tail:ident)* ! $group:tt, $($rest:tt)*) => {
        $crate::__pgrx_c_classify!(
            @argument [__pgrx_c_args_ISUPDATE_from_mxstatus] [p1 $mode [$($done)*] [$($rest)*]] [
                ::$head $(::$tail)* ! $group
            ]
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; ($($inner:tt)*), $($rest:tt)*) => {
        $crate::__pgrx_c_classify!(
            @argument [__pgrx_c_args_ISUPDATE_from_mxstatus] [p1 $mode [$($done)*] [$($rest)*]] [
                ($($inner)*)
            ]
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; $argument:literal, $($rest:tt)*) => {
        $crate::__pgrx_c_args_ISUPDATE_from_mxstatus!(
            @p1 $mode [$($done)* (@literal [$argument]),];
            $($rest)*
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; $argument:expr, $($rest:tt)*) => {
        $crate::__pgrx_c_args_ISUPDATE_from_mxstatus!(
            @p1 $mode [$($done)* (@native [$argument]),];
            $($rest)*
        )
    };
    (@p1 $mode:ident [$($done:tt)*];) => {
        $crate::ISUPDATE_from_mxstatus!(@$mode; $($done)*)
    };
    ($($invalid:tt)*) => {
        compile_error!("arguments do not satisfy this C macro's invocation contract")
    };
}
/// C macro ISUPDATE_from_mxstatus from multixact.h:52
///
/// ```text
/// #define ISUPDATE_from_mxstatus( status ) ( ( status ) > MultiXactStatusForUpdate )
/// ```
#[macro_export]
macro_rules! ISUPDATE_from_mxstatus {
    (@__pgrx_emit_public; $status:tt $(,)?) => {
        $crate::__pgrx_c_macros::expression_result::finish(
            $crate::ISUPDATE_from_mxstatus!(@__pgrx_emit_value; $status)
        )
    };
    (@__pgrx_emit_value; $status:tt $(,)?) => {
        (
            $crate::__pgrx_c_macros::expression::profile_value::<true, _>(
                $crate::__pgrx_c_macros::expression::gt(
                    (
                        $crate::__pgrx_c_macros::expression::profile_value::<true, _>(
                            $crate::__pgrx_c_operand!(@value [true]; $status)
                        )
                    ),
                    $crate::__pgrx_c_macros::expression::profile_value::<true, _>(
                        $crate::__pgrx_c_macros::CValue::<$crate::__pgrx_c_macros::CInt>::new(
                            $crate::MultiXactStatus::MultiXactStatusForUpdate as i32
                        )
                    )
                )
            )
        )
    };
    (@__pgrx_c_value; $($raw:tt)*) => {
        $crate::__pgrx_c_args_ISUPDATE_from_mxstatus!(@collect __pgrx_emit_value []; $($raw)*)
    };
    (@__pgrx_emit_place; $status:tt $(,)?) => {
        compile_error!("C expression is not a place in this operation")
    };
    (@__pgrx_c_place; $($raw:tt)*) => {
        $crate::__pgrx_c_args_ISUPDATE_from_mxstatus!(@collect __pgrx_emit_place []; $($raw)*)
    };
    (@__pgrx_emit_read_place; $status:tt $(,)?) => {
        compile_error!("C expression is not a place in this operation")
    };
    (@__pgrx_c_read_place; $($raw:tt)*) => {
        $crate::__pgrx_c_args_ISUPDATE_from_mxstatus!(@collect __pgrx_emit_read_place []; $($raw)*)
    };
    (@__pgrx_emit_size; $status:tt $(,)?) => {
        $crate::__pgrx_c_macros::expression::size_of_value_type(
            if false {
                Some(
                    unsafe {
                        $crate::__pgrx_c_macros::expression::profile_value::<true, _>(
                            $crate::__pgrx_c_macros::expression::gt(
                                (
                                    $crate::__pgrx_c_macros::expression::profile_value::<true, _>(
                                        $crate::__pgrx_c_operand!(@value [true]; $status)
                                    )
                                ),
                                $crate::__pgrx_c_macros::expression::profile_value::<true, _>(
                                    $crate::__pgrx_c_macros::CValue::<$crate::__pgrx_c_macros::CInt>::new(
                                        $crate::MultiXactStatus::MultiXactStatusForUpdate as i32
                                    )
                                )
                            )
                        )
                    }
                )
            } else {
                None
            }
        )
    };
    (@__pgrx_c_size; $($raw:tt)*) => {
        $crate::__pgrx_c_args_ISUPDATE_from_mxstatus!(@collect __pgrx_emit_size []; $($raw)*)
    };
    (@__pgrx_emit_discard; $status:tt $(,)?) => {
        {
            let _ = $crate::__pgrx_c_macros::expression::profile_value::<true, _>(
                $crate::__pgrx_c_macros::expression::gt(
                    (
                        $crate::__pgrx_c_macros::expression::profile_value::<true, _>(
                            $crate::__pgrx_c_operand!(@value [true]; $status)
                        )
                    ),
                    $crate::__pgrx_c_macros::expression::profile_value::<true, _>(
                        $crate::__pgrx_c_macros::CValue::<$crate::__pgrx_c_macros::CInt>::new(
                            $crate::MultiXactStatus::MultiXactStatusForUpdate as i32
                        )
                    )
                )
            );
        }
    };
    (@__pgrx_c_discard; $($raw:tt)*) => {
        $crate::__pgrx_c_args_ISUPDATE_from_mxstatus!(@collect __pgrx_emit_discard []; $($raw)*)
    };
    ($($raw:tt)*) => {
        $crate::__pgrx_c_args_ISUPDATE_from_mxstatus!(@collect __pgrx_emit_public []; $($raw)*)
    };
}

#[cfg(not(all(
    target_arch = "aarch64",
    target_os = "macos",
    target_pointer_width = "64",
    target_endian = "little"
)))]
#[cfg(not(docsrs))]
compile_error!("generated C macros require their inspected C target profile");
#[doc(hidden)]
#[macro_export]
macro_rules! __pgrx_c_args_MultiXactIdIsValid {
    (@collect $mode:ident [$($done:tt)*]; $($raw:tt)*) => {
        $crate::__pgrx_c_args_MultiXactIdIsValid!(@p0 $mode [$($done)*]; $($raw)*)
    };
    (@classified [$next:ident $mode:ident [$($done:tt)*] [$($rest:tt)*]] $descriptor:tt) => {
        $crate::__pgrx_c_args_MultiXactIdIsValid!(@$next $mode [$($done)* $descriptor,]; $($rest)*)
    };
    (@p0 $mode:ident [$($done:tt)*]; - $argument:literal) => {
        $crate::__pgrx_c_args_MultiXactIdIsValid!(@p1 $mode [$($done)* (@literal [- $argument]),];)
    };
    (@negative0 $mode:ident [$($done:tt)*]; $argument:expr) => {
        $crate::__pgrx_c_args_MultiXactIdIsValid!(@p1 $mode [$($done)* (@native [$argument]),];)
    };
    (@p0 $mode:ident [$($done:tt)*]; - $argument:literal, $($rest:tt)*) => {
        $crate::__pgrx_c_args_MultiXactIdIsValid!(
            @p1 $mode [$($done)* (@literal [- $argument]),];
            $($rest)*
        )
    };
    (@negative0 $mode:ident [$($done:tt)*]; $argument:expr, $($rest:tt)*) => {
        $crate::__pgrx_c_args_MultiXactIdIsValid!(
            @p1 $mode [$($done)* (@native [$argument]),];
            $($rest)*
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; - $($raw:tt)*) => {
        $crate::__pgrx_c_args_MultiXactIdIsValid!(@negative0 $mode [$($done)*]; - $($raw)*)
    };
    (@p0 $mode:ident [$($done:tt)*]; (@__pgrx_c_native [$argument:expr])) => {
        $crate::__pgrx_c_args_MultiXactIdIsValid!(@p1 $mode [$($done)* (@native [$argument]),];)
    };
    (@p0 $mode:ident [$($done:tt)*]; $head:ident $(::$tail:ident)* ! $group:tt) => {
        $crate::__pgrx_c_classify!(
            @argument [__pgrx_c_args_MultiXactIdIsValid] [p1 $mode [$($done)*] []] [
                $head $(::$tail)* ! $group
            ]
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; ::$head:ident $(::$tail:ident)* ! $group:tt) => {
        $crate::__pgrx_c_classify!(
            @argument [__pgrx_c_args_MultiXactIdIsValid] [p1 $mode [$($done)*] []] [
                ::$head $(::$tail)* ! $group
            ]
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; ($($inner:tt)*)) => {
        $crate::__pgrx_c_classify!(
            @argument [__pgrx_c_args_MultiXactIdIsValid] [p1 $mode [$($done)*] []] [($($inner)*)]
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; $argument:literal) => {
        $crate::__pgrx_c_args_MultiXactIdIsValid!(@p1 $mode [$($done)* (@literal [$argument]),];)
    };
    (@p0 $mode:ident [$($done:tt)*]; $argument:expr) => {
        $crate::__pgrx_c_args_MultiXactIdIsValid!(@p1 $mode [$($done)* (@native [$argument]),];)
    };
    (@p0 $mode:ident [$($done:tt)*]; (@__pgrx_c_native [$argument:expr]), $($rest:tt)*) => {
        $crate::__pgrx_c_args_MultiXactIdIsValid!(
            @p1 $mode [$($done)* (@native [$argument]),];
            $($rest)*
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; $head:ident $(::$tail:ident)* ! $group:tt, $($rest:tt)*) => {
        $crate::__pgrx_c_classify!(
            @argument [__pgrx_c_args_MultiXactIdIsValid] [p1 $mode [$($done)*] [$($rest)*]] [
                $head $(::$tail)* ! $group
            ]
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; ::$head:ident $(::$tail:ident)* ! $group:tt, $($rest:tt)*) => {
        $crate::__pgrx_c_classify!(
            @argument [__pgrx_c_args_MultiXactIdIsValid] [p1 $mode [$($done)*] [$($rest)*]] [
                ::$head $(::$tail)* ! $group
            ]
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; ($($inner:tt)*), $($rest:tt)*) => {
        $crate::__pgrx_c_classify!(
            @argument [__pgrx_c_args_MultiXactIdIsValid] [p1 $mode [$($done)*] [$($rest)*]] [
                ($($inner)*)
            ]
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; $argument:literal, $($rest:tt)*) => {
        $crate::__pgrx_c_args_MultiXactIdIsValid!(
            @p1 $mode [$($done)* (@literal [$argument]),];
            $($rest)*
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; $argument:expr, $($rest:tt)*) => {
        $crate::__pgrx_c_args_MultiXactIdIsValid!(
            @p1 $mode [$($done)* (@native [$argument]),];
            $($rest)*
        )
    };
    (@p1 $mode:ident [$($done:tt)*];) => {
        $crate::MultiXactIdIsValid!(@$mode; $($done)*)
    };
    ($($invalid:tt)*) => {
        compile_error!("arguments do not satisfy this C macro's invocation contract")
    };
}
/// C macro MultiXactIdIsValid from multixact.h:28
///
/// ```text
/// #define MultiXactIdIsValid( multi ) ( ( multi ) != InvalidMultiXactId )
/// ```
#[macro_export]
macro_rules! MultiXactIdIsValid {
    (@__pgrx_emit_public; $multi:tt $(,)?) => {
        $crate::__pgrx_c_macros::expression_result::finish(
            $crate::MultiXactIdIsValid!(@__pgrx_emit_value; $multi)
        )
    };
    (@__pgrx_emit_value; $multi:tt $(,)?) => {
        (
            $crate::__pgrx_c_macros::expression::profile_value::<true, _>(
                $crate::__pgrx_c_macros::expression::ne(
                    (
                        $crate::__pgrx_c_macros::expression::profile_value::<true, _>(
                            $crate::__pgrx_c_operand!(@value [true]; $multi)
                        )
                    ),
                    $crate::__pgrx_c_macros::expression::profile_value::<true, _>(
                        $crate::__pgrx_c_macros::expression::null_constant(
                            /* PGRX: InvalidMultiXactId remains expanded because no integer constant binding is available in the defining Rust crate. */
                            $crate::__pgrx_c_macros::CValue::<$crate::__pgrx_c_macros::CUnsignedInt>::new(
                                0u32
                            )
                        )
                    )
                )
            )
        )
    };
    (@__pgrx_c_value; $($raw:tt)*) => {
        $crate::__pgrx_c_args_MultiXactIdIsValid!(@collect __pgrx_emit_value []; $($raw)*)
    };
    (@__pgrx_emit_place; $multi:tt $(,)?) => {
        compile_error!("C expression is not a place in this operation")
    };
    (@__pgrx_c_place; $($raw:tt)*) => {
        $crate::__pgrx_c_args_MultiXactIdIsValid!(@collect __pgrx_emit_place []; $($raw)*)
    };
    (@__pgrx_emit_read_place; $multi:tt $(,)?) => {
        compile_error!("C expression is not a place in this operation")
    };
    (@__pgrx_c_read_place; $($raw:tt)*) => {
        $crate::__pgrx_c_args_MultiXactIdIsValid!(@collect __pgrx_emit_read_place []; $($raw)*)
    };
    (@__pgrx_emit_size; $multi:tt $(,)?) => {
        $crate::__pgrx_c_macros::expression::size_of_value_type(
            if false {
                Some(
                    unsafe {
                        $crate::__pgrx_c_macros::expression::profile_value::<true, _>(
                            $crate::__pgrx_c_macros::expression::ne(
                                (
                                    $crate::__pgrx_c_macros::expression::profile_value::<true, _>(
                                        $crate::__pgrx_c_operand!(@value [true]; $multi)
                                    )
                                ),
                                $crate::__pgrx_c_macros::expression::profile_value::<true, _>(
                                    $crate::__pgrx_c_macros::expression::null_constant(
                                        /* PGRX: InvalidMultiXactId remains expanded because no integer constant binding is available in the defining Rust crate. */
                                        $crate::__pgrx_c_macros::CValue::<
                                            $crate::__pgrx_c_macros::CUnsignedInt
                                        >::new(0u32)
                                    )
                                )
                            )
                        )
                    }
                )
            } else {
                None
            }
        )
    };
    (@__pgrx_c_size; $($raw:tt)*) => {
        $crate::__pgrx_c_args_MultiXactIdIsValid!(@collect __pgrx_emit_size []; $($raw)*)
    };
    (@__pgrx_emit_discard; $multi:tt $(,)?) => {
        {
            let _ = $crate::__pgrx_c_macros::expression::profile_value::<true, _>(
                $crate::__pgrx_c_macros::expression::ne(
                    (
                        $crate::__pgrx_c_macros::expression::profile_value::<true, _>(
                            $crate::__pgrx_c_operand!(@value [true]; $multi)
                        )
                    ),
                    $crate::__pgrx_c_macros::expression::profile_value::<true, _>(
                        $crate::__pgrx_c_macros::expression::null_constant(
                            /* PGRX: InvalidMultiXactId remains expanded because no integer constant binding is available in the defining Rust crate. */
                            $crate::__pgrx_c_macros::CValue::<$crate::__pgrx_c_macros::CUnsignedInt>::new(
                                0u32
                            )
                        )
                    )
                )
            );
        }
    };
    (@__pgrx_c_discard; $($raw:tt)*) => {
        $crate::__pgrx_c_args_MultiXactIdIsValid!(@collect __pgrx_emit_discard []; $($raw)*)
    };
    ($($raw:tt)*) => {
        $crate::__pgrx_c_args_MultiXactIdIsValid!(@collect __pgrx_emit_public []; $($raw)*)
    };
}

pub use ISUPDATE_from_mxstatus;
pub use MultiXactIdIsValid;
