mod anyarray_tests;
mod array_tests;
mod datetime_tests;
mod default_arg_value_tests;
mod enum_type_tests;
mod fcinfo_tests;
mod guc_tests;
mod hooks_tests;
mod json_tests;
mod log_tests;
mod node_tests;
mod pg_extern_args_tests;
mod schema_tests;
mod spi_tests;
mod struct_type_tests;
mod variadic_tests;
mod xact_callback_tests;
mod xid64_tests;

pgx::pg_module_magic!();
