/* Automatically generated by pgrx-c-macros. Do not hand-edit.

This code is generated for documentation purposes, so that it is easy to reference on docs.rs. C macros and their support code are regenerated for your build of pgrx, and your Postgres configuration may differ.
*/
#[path = "hashfn.rs"]
mod hashfn;
#[allow(unused_imports)]
pub use hashfn::*;
#[path = "kwlookup.rs"]
mod kwlookup;
#[allow(unused_imports)]
pub use kwlookup::*;
#[path = "pg_lzcompress.rs"]
mod pg_lzcompress;
#[allow(unused_imports)]
pub use pg_lzcompress::*;
#[path = "pg_prng.rs"]
mod pg_prng;
#[allow(unused_imports)]
pub use pg_prng::*;
#[path = "relpath.rs"]
mod relpath;
#[allow(unused_imports)]
pub use relpath::*;
