// Automatically generated by pgrx-c-macros for documentation. Do not hand-edit.
// C macros from generic-gcc.h.

/// Typed call adapter for C inline function pg_atomic_clear_flag_impl from generic-gcc.h:141 (PostgreSQL 15–17), generic-gcc.h:139 (PostgreSQL 18), generic-gcc.h:138 (PostgreSQL 19)
///
/// ```c
/// static inline void
/// pg_atomic_clear_flag_impl(volatile pg_atomic_flag *ptr)
/// {
/// 	__sync_lock_release(&ptr->value);
/// }
/// ```
///
///
#[doc = crate::__pgrx_c_doc_inline_call!()]
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! pg_atomic_clear_flag_impl {
    ($ptr:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
/// Typed call adapter for C inline function pg_atomic_compare_exchange_u32_impl from generic-gcc.h:162 (PostgreSQL 15–17), generic-gcc.h:160 (PostgreSQL 18), generic-gcc.h:159 (PostgreSQL 19)
///
/// ```c
/// static inline bool
/// pg_atomic_compare_exchange_u32_impl(volatile pg_atomic_uint32 *ptr,
/// 									uint32 *expected, uint32 newval)
/// {
/// 	/* FIXME: we can probably use a lower consistency model */
/// 	return __atomic_compare_exchange_n(&ptr->value, expected, newval, false,
/// 									   __ATOMIC_SEQ_CST, __ATOMIC_SEQ_CST);
/// }
/// ```
///
///
#[doc = crate::__pgrx_c_doc_inline_call!()]
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! pg_atomic_compare_exchange_u32_impl {
    ($ptr:expr, $expected:expr, $newval:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(any(feature = "pg15", feature = "pg16"))]
/// Typed call adapter for C inline function pg_atomic_compare_exchange_u64_impl from generic-gcc.h:230 (PostgreSQL 15–16)
///
/// ```c
/// static inline bool
/// pg_atomic_compare_exchange_u64_impl(volatile pg_atomic_uint64 *ptr,
/// 									uint64 *expected, uint64 newval)
/// {
/// 	return __atomic_compare_exchange_n(&ptr->value, expected, newval, false,
/// 									   __ATOMIC_SEQ_CST, __ATOMIC_SEQ_CST);
/// }
/// ```
///
///
#[doc = crate::__pgrx_c_doc_inline_call!()]
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! pg_atomic_compare_exchange_u64_impl {
    ($ptr:expr, $expected:expr, $newval:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(any(feature = "pg17", feature = "pg18", feature = "pg19"))]
/// Typed call adapter for C inline function pg_atomic_compare_exchange_u64_impl from generic-gcc.h:247 (PostgreSQL 17), generic-gcc.h:245 (PostgreSQL 18), generic-gcc.h:244 (PostgreSQL 19)
///
/// ```c
/// static inline bool
/// pg_atomic_compare_exchange_u64_impl(volatile pg_atomic_uint64 *ptr,
/// 									uint64 *expected, uint64 newval)
/// {
/// 	AssertPointerAlignment(expected, 8);
/// 	return __atomic_compare_exchange_n(&ptr->value, expected, newval, false,
/// 									   __ATOMIC_SEQ_CST, __ATOMIC_SEQ_CST);
/// }
/// ```
///
///
#[doc = crate::__pgrx_c_doc_inline_call!()]
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! pg_atomic_compare_exchange_u64_impl {
    ($ptr:expr, $expected:expr, $newval:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(any(feature = "pg17", feature = "pg18", feature = "pg19"))]
/// Typed call adapter for C inline function pg_atomic_exchange_u32_impl from generic-gcc.h:197 (PostgreSQL 17), generic-gcc.h:195 (PostgreSQL 18), generic-gcc.h:194 (PostgreSQL 19)
///
/// ```c
/// static inline uint32
/// pg_atomic_exchange_u32_impl(volatile pg_atomic_uint32 *ptr, uint32 newval)
/// {
/// 	return __atomic_exchange_n(&ptr->value, newval, __ATOMIC_SEQ_CST);
/// }
/// ```
///
///
#[doc = crate::__pgrx_c_doc_inline_call!()]
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! pg_atomic_exchange_u32_impl {
    ($ptr:expr, $newval:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(any(feature = "pg17", feature = "pg18", feature = "pg19"))]
/// Typed call adapter for C inline function pg_atomic_exchange_u64_impl from generic-gcc.h:284 (PostgreSQL 17), generic-gcc.h:282 (PostgreSQL 18), generic-gcc.h:281 (PostgreSQL 19)
///
/// ```c
/// static inline uint64
/// pg_atomic_exchange_u64_impl(volatile pg_atomic_uint64 *ptr, uint64 newval)
/// {
/// 	return __atomic_exchange_n(&ptr->value, newval, __ATOMIC_SEQ_CST);
/// }
/// ```
///
///
#[doc = crate::__pgrx_c_doc_inline_call!()]
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! pg_atomic_exchange_u64_impl {
    ($ptr:expr, $newval:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
/// Typed call adapter for C inline function pg_atomic_fetch_add_u32_impl from generic-gcc.h:191 (PostgreSQL 15–16), generic-gcc.h:208 (PostgreSQL 17), generic-gcc.h:206 (PostgreSQL 18), generic-gcc.h:205 (PostgreSQL 19)
///
/// ```c
/// static inline uint32
/// pg_atomic_fetch_add_u32_impl(volatile pg_atomic_uint32 *ptr, int32 add_)
/// {
/// 	return __sync_fetch_and_add(&ptr->value, add_);
/// }
/// ```
///
///
#[doc = crate::__pgrx_c_doc_inline_call!()]
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! pg_atomic_fetch_add_u32_impl {
    ($ptr:expr, $add_:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
/// Typed call adapter for C inline function pg_atomic_fetch_add_u64_impl from generic-gcc.h:258 (PostgreSQL 15–16), generic-gcc.h:295 (PostgreSQL 17), generic-gcc.h:293 (PostgreSQL 18), generic-gcc.h:292 (PostgreSQL 19)
///
/// ```c
/// static inline uint64
/// pg_atomic_fetch_add_u64_impl(volatile pg_atomic_uint64 *ptr, int64 add_)
/// {
/// 	return __sync_fetch_and_add(&ptr->value, add_);
/// }
/// ```
///
///
#[doc = crate::__pgrx_c_doc_inline_call!()]
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! pg_atomic_fetch_add_u64_impl {
    ($ptr:expr, $add_:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
/// Typed call adapter for C inline function pg_atomic_fetch_and_u32_impl from generic-gcc.h:209 (PostgreSQL 15–16), generic-gcc.h:226 (PostgreSQL 17), generic-gcc.h:224 (PostgreSQL 18), generic-gcc.h:223 (PostgreSQL 19)
///
/// ```c
/// static inline uint32
/// pg_atomic_fetch_and_u32_impl(volatile pg_atomic_uint32 *ptr, uint32 and_)
/// {
/// 	return __sync_fetch_and_and(&ptr->value, and_);
/// }
/// ```
///
///
#[doc = crate::__pgrx_c_doc_inline_call!()]
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! pg_atomic_fetch_and_u32_impl {
    ($ptr:expr, $and_:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
/// Typed call adapter for C inline function pg_atomic_fetch_and_u64_impl from generic-gcc.h:276 (PostgreSQL 15–16), generic-gcc.h:313 (PostgreSQL 17), generic-gcc.h:311 (PostgreSQL 18), generic-gcc.h:310 (PostgreSQL 19)
///
/// ```c
/// static inline uint64
/// pg_atomic_fetch_and_u64_impl(volatile pg_atomic_uint64 *ptr, uint64 and_)
/// {
/// 	return __sync_fetch_and_and(&ptr->value, and_);
/// }
/// ```
///
///
#[doc = crate::__pgrx_c_doc_inline_call!()]
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! pg_atomic_fetch_and_u64_impl {
    ($ptr:expr, $and_:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
/// Typed call adapter for C inline function pg_atomic_fetch_or_u32_impl from generic-gcc.h:218 (PostgreSQL 15–16), generic-gcc.h:235 (PostgreSQL 17), generic-gcc.h:233 (PostgreSQL 18), generic-gcc.h:232 (PostgreSQL 19)
///
/// ```c
/// static inline uint32
/// pg_atomic_fetch_or_u32_impl(volatile pg_atomic_uint32 *ptr, uint32 or_)
/// {
/// 	return __sync_fetch_and_or(&ptr->value, or_);
/// }
/// ```
///
///
#[doc = crate::__pgrx_c_doc_inline_call!()]
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! pg_atomic_fetch_or_u32_impl {
    ($ptr:expr, $or_:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
/// Typed call adapter for C inline function pg_atomic_fetch_or_u64_impl from generic-gcc.h:285 (PostgreSQL 15–16), generic-gcc.h:322 (PostgreSQL 17), generic-gcc.h:320 (PostgreSQL 18), generic-gcc.h:319 (PostgreSQL 19)
///
/// ```c
/// static inline uint64
/// pg_atomic_fetch_or_u64_impl(volatile pg_atomic_uint64 *ptr, uint64 or_)
/// {
/// 	return __sync_fetch_and_or(&ptr->value, or_);
/// }
/// ```
///
///
#[doc = crate::__pgrx_c_doc_inline_call!()]
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! pg_atomic_fetch_or_u64_impl {
    ($ptr:expr, $or_:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
/// Typed call adapter for C inline function pg_atomic_fetch_sub_u32_impl from generic-gcc.h:200 (PostgreSQL 15–16), generic-gcc.h:217 (PostgreSQL 17), generic-gcc.h:215 (PostgreSQL 18), generic-gcc.h:214 (PostgreSQL 19)
///
/// ```c
/// static inline uint32
/// pg_atomic_fetch_sub_u32_impl(volatile pg_atomic_uint32 *ptr, int32 sub_)
/// {
/// 	return __sync_fetch_and_sub(&ptr->value, sub_);
/// }
/// ```
///
///
#[doc = crate::__pgrx_c_doc_inline_call!()]
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! pg_atomic_fetch_sub_u32_impl {
    ($ptr:expr, $sub_:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
/// Typed call adapter for C inline function pg_atomic_fetch_sub_u64_impl from generic-gcc.h:267 (PostgreSQL 15–16), generic-gcc.h:304 (PostgreSQL 17), generic-gcc.h:302 (PostgreSQL 18), generic-gcc.h:301 (PostgreSQL 19)
///
/// ```c
/// static inline uint64
/// pg_atomic_fetch_sub_u64_impl(volatile pg_atomic_uint64 *ptr, int64 sub_)
/// {
/// 	return __sync_fetch_and_sub(&ptr->value, sub_);
/// }
/// ```
///
///
#[doc = crate::__pgrx_c_doc_inline_call!()]
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! pg_atomic_fetch_sub_u64_impl {
    ($ptr:expr, $sub_:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
/// Typed call adapter for C inline function pg_atomic_init_flag_impl from generic-gcc.h:150 (PostgreSQL 15–17), generic-gcc.h:148 (PostgreSQL 18), generic-gcc.h:147 (PostgreSQL 19)
///
/// ```c
/// static inline void
/// pg_atomic_init_flag_impl(volatile pg_atomic_flag *ptr)
/// {
/// 	pg_atomic_clear_flag_impl(ptr);
/// }
/// ```
///
///
#[doc = crate::__pgrx_c_doc_inline_call!()]
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! pg_atomic_init_flag_impl {
    ($ptr:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
/// Typed call adapter for C inline function pg_atomic_test_set_flag_impl from generic-gcc.h:119 (PostgreSQL 15–17), generic-gcc.h:117 (PostgreSQL 18), generic-gcc.h:116 (PostgreSQL 19)
///
/// ```c
/// static inline bool
/// pg_atomic_test_set_flag_impl(volatile pg_atomic_flag *ptr)
/// {
/// 	/* NB: only an acquire barrier, not a full one */
/// 	/* some platform only support a 1 here */
/// 	return __sync_lock_test_and_set(&ptr->value, 1) == 0;
/// }
/// ```
///
///
#[doc = crate::__pgrx_c_doc_inline_call!()]
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! pg_atomic_test_set_flag_impl {
    ($ptr:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
/// Typed call adapter for C inline function pg_atomic_unlocked_test_flag_impl from generic-gcc.h:132 (PostgreSQL 15–17), generic-gcc.h:130 (PostgreSQL 18), generic-gcc.h:129 (PostgreSQL 19)
///
/// ```c
/// static inline bool
/// pg_atomic_unlocked_test_flag_impl(volatile pg_atomic_flag *ptr)
/// {
/// 	return ptr->value == 0;
/// }
/// ```
///
///
#[doc = crate::__pgrx_c_doc_inline_call!()]
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! pg_atomic_unlocked_test_flag_impl {
    ($ptr:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
pub use pg_atomic_clear_flag_impl;
pub use pg_atomic_compare_exchange_u32_impl;
pub use pg_atomic_compare_exchange_u64_impl;
#[cfg(any(feature = "pg17", feature = "pg18", feature = "pg19"))]
pub use pg_atomic_exchange_u32_impl;
#[cfg(any(feature = "pg17", feature = "pg18", feature = "pg19"))]
pub use pg_atomic_exchange_u64_impl;
pub use pg_atomic_fetch_add_u32_impl;
pub use pg_atomic_fetch_add_u64_impl;
pub use pg_atomic_fetch_and_u32_impl;
pub use pg_atomic_fetch_and_u64_impl;
pub use pg_atomic_fetch_or_u32_impl;
pub use pg_atomic_fetch_or_u64_impl;
pub use pg_atomic_fetch_sub_u32_impl;
pub use pg_atomic_fetch_sub_u64_impl;
pub use pg_atomic_init_flag_impl;
pub use pg_atomic_test_set_flag_impl;
pub use pg_atomic_unlocked_test_flag_impl;
