// Automatically generated by pgrx-c-macros for documentation. Do not hand-edit.
// C macros from ts_utils.h.

#[cfg(feature = "pg15")]
/// C macro DatumGetTSQuerySign from ts_utils.h:245 (PostgreSQL 15)
///
/// ```text
/// #define DatumGetTSQuerySign( X ) ( ( TSQuerySign ) DatumGetInt64 ( X ) )
/// ```
///
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
///
/// # Panics
///
/// Conversions involving floats reject nonfinite or out-of-range integer results; conversions into Rust enums reject values without a represented discriminant. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! DatumGetTSQuerySign {
    ($X:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(any(feature = "pg16", feature = "pg17", feature = "pg18", feature = "pg19"))]
/// Typed call adapter for C inline function DatumGetTSQuerySign from ts_utils.h:257 (PostgreSQL 16–19)
///
/// ```c
/// static inline TSQuerySign
/// DatumGetTSQuerySign(Datum X)
/// {
/// 	return (TSQuerySign) DatumGetInt64(X);
/// }
/// ```
///
///
#[doc = crate::__pgrx_c_doc_inline_call!()]
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! DatumGetTSQuerySign {
    ($X:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
/// C macro ISOPERATOR from ts_utils.h:41 (PostgreSQL 15), ts_utils.h:43 (PostgreSQL 16–19)
///
/// ```text
/// #define ISOPERATOR( x ) ( * ( x ) == '!' || * ( x ) == '&' || * ( x ) == '|' || * ( x ) == '(' || * ( x ) == ')' || * ( x ) == '<' )
/// ```
///
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
#[macro_export]
macro_rules! ISOPERATOR {
    ($x:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(feature = "pg15")]
/// C macro PG_GETARG_TSQUERYSIGN from ts_utils.h:247 (PostgreSQL 15)
///
/// ```text
/// #define PG_GETARG_TSQUERYSIGN( n ) DatumGetTSQuerySign ( PG_GETARG_DATUM ( n ) )
/// ```
///
///
/// Rust callers supply 2 arguments: the 1 original C parameter, followed by explicit caller-scope operands in this order: `fcinfo`. Each operand must preserve its C type and place requirements.
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
///
/// # Panics
///
/// Conversions involving floats reject nonfinite or out-of-range integer results; conversions into Rust enums reject values without a represented discriminant. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! PG_GETARG_TSQUERYSIGN {
    ($n:expr, $fcinfo:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(any(feature = "pg16", feature = "pg17", feature = "pg18", feature = "pg19"))]
/// C macro PG_GETARG_TSQUERYSIGN from ts_utils.h:264 (PostgreSQL 16–19)
///
/// ```text
/// #define PG_GETARG_TSQUERYSIGN( n ) DatumGetTSQuerySign ( PG_GETARG_DATUM ( n ) )
/// ```
///
///
/// Rust callers supply 2 arguments: the 1 original C parameter, followed by explicit caller-scope operands in this order: `fcinfo`. Each operand must preserve its C type and place requirements.
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! PG_GETARG_TSQUERYSIGN {
    ($n:expr, $fcinfo:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(feature = "pg15")]
/// C macro PG_RETURN_TSQUERYSIGN from ts_utils.h:246 (PostgreSQL 15)
///
/// ```text
/// #define PG_RETURN_TSQUERYSIGN( X ) return TSQuerySignGetDatum ( X )
/// ```
///
///
#[doc = crate::__pgrx_c_doc_caller_returns!()]
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
///
/// # Panics
///
/// Conversions involving floats reject nonfinite or out-of-range integer results; conversions into Rust enums reject values without a represented discriminant. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! PG_RETURN_TSQUERYSIGN {
    ($X:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
    (@__pgrx_c_return_as [$__pgrx_c_return:ty]; $X:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(any(feature = "pg16", feature = "pg17", feature = "pg18", feature = "pg19"))]
/// C macro PG_RETURN_TSQUERYSIGN from ts_utils.h:263 (PostgreSQL 16–19)
///
/// ```text
/// #define PG_RETURN_TSQUERYSIGN( X ) return TSQuerySignGetDatum ( X )
/// ```
///
///
#[doc = crate::__pgrx_c_doc_caller_returns!()]
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! PG_RETURN_TSQUERYSIGN {
    ($X:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
    (@__pgrx_c_return_as [$__pgrx_c_return:ty]; $X:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(feature = "pg15")]
/// C macro TSQuerySignGetDatum from ts_utils.h:244 (PostgreSQL 15)
///
/// ```text
/// #define TSQuerySignGetDatum( X ) Int64GetDatum ( ( int64 ) ( X ) )
/// ```
///
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
///
/// # Panics
///
/// Conversions involving floats reject nonfinite or out-of-range integer results; conversions into Rust enums reject values without a represented discriminant. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! TSQuerySignGetDatum {
    ($X:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(any(feature = "pg16", feature = "pg17", feature = "pg18", feature = "pg19"))]
/// Typed call adapter for C inline function TSQuerySignGetDatum from ts_utils.h:251 (PostgreSQL 16–19)
///
/// ```c
/// static inline Datum
/// TSQuerySignGetDatum(TSQuerySign X)
/// {
/// 	return Int64GetDatum((int64) X);
/// }
/// ```
///
///
#[doc = crate::__pgrx_c_doc_inline_call!()]
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! TSQuerySignGetDatum {
    ($X:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
pub use DatumGetTSQuerySign;
pub use ISOPERATOR;
pub use PG_GETARG_TSQUERYSIGN;
pub use PG_RETURN_TSQUERYSIGN;
pub use TSQuerySignGetDatum;
