// Automatically generated by pgrx-c-macros for documentation. Do not hand-edit.
// C macros from gramparse.h.

#[cfg(feature = "pg15")]
/// C macro pg_yyget_extra from gramparse.h:64 (PostgreSQL 15)
///
/// ```text
/// #define pg_yyget_extra( yyscanner ) ( * ( ( base_yy_extra_type * * ) ( yyscanner ) ) )
/// ```
///
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
///
/// # Panics
///
/// Conversions involving floats reject nonfinite or out-of-range integer results; conversions into Rust enums reject values without a represented discriminant. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! pg_yyget_extra {
    ($yyscanner:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(feature = "pg15")]
pub use pg_yyget_extra;
