/* Automatically generated by pgrx-c-macros. Do not hand-edit.

This code is generated for documentation purposes, so that it is easy to reference on docs.rs. C macros and their support code are regenerated for your build of pgrx, and your Postgres configuration may differ.
*/
// C macros from vacuum.h.

#[cfg(not(all(
    target_arch = "aarch64",
    target_os = "macos",
    target_pointer_width = "64",
    target_endian = "little"
)))]
#[cfg(not(docsrs))]
compile_error!("generated C macros require their inspected C target profile");
const _: () = {
    use crate::__pgrx_c_macros::CInteger as _;
    assert!(crate::__pgrx_c_macros::CChar::SIGNED == true);
    assert!(crate::__pgrx_c_macros::CLong::BITS == 64);
    assert!(crate::__pgrx_c_macros::CSize::BITS == 64);
    assert!(crate::__pgrx_c_macros::CSize::RANK == 4);
    assert!(!crate::__pgrx_c_macros::CSize::SIGNED);
    assert!(crate::__pgrx_c_macros::CPtrDiff::BITS == 64);
    assert!(crate::__pgrx_c_macros::CPtrDiff::RANK == 4);
    assert!(crate::__pgrx_c_macros::CPtrDiff::SIGNED);
};
#[doc(hidden)]
#[macro_export]
macro_rules! __pgrx_c_args_MAXDEADITEMS {
    (@collect $mode:ident [$($done:tt)*]; $($raw:tt)*) => {
        $crate::__pgrx_c_args_MAXDEADITEMS!(@p0 $mode [$($done)*]; $($raw)*)
    };
    (@classified [$next:ident $mode:ident [$($done:tt)*] [$($rest:tt)*]] $descriptor:tt) => {
        $crate::__pgrx_c_args_MAXDEADITEMS!(@$next $mode [$($done)* $descriptor,]; $($rest)*)
    };
    (@p0 $mode:ident [$($done:tt)*]; - $argument:literal) => {
        $crate::__pgrx_c_args_MAXDEADITEMS!(@p1 $mode [$($done)* (@literal [- $argument]),];)
    };
    (@negative0 $mode:ident [$($done:tt)*]; $argument:expr) => {
        $crate::__pgrx_c_args_MAXDEADITEMS!(@p1 $mode [$($done)* (@native [$argument]),];)
    };
    (@p0 $mode:ident [$($done:tt)*]; - $argument:literal, $($rest:tt)*) => {
        $crate::__pgrx_c_args_MAXDEADITEMS!(
            @p1 $mode [$($done)* (@literal [- $argument]),];
            $($rest)*
        )
    };
    (@negative0 $mode:ident [$($done:tt)*]; $argument:expr, $($rest:tt)*) => {
        $crate::__pgrx_c_args_MAXDEADITEMS!(@p1 $mode [$($done)* (@native [$argument]),]; $($rest)*)
    };
    (@p0 $mode:ident [$($done:tt)*]; - $($raw:tt)*) => {
        $crate::__pgrx_c_args_MAXDEADITEMS!(@negative0 $mode [$($done)*]; - $($raw)*)
    };
    (@p0 $mode:ident [$($done:tt)*]; (@__pgrx_c_native [$argument:expr])) => {
        $crate::__pgrx_c_args_MAXDEADITEMS!(@p1 $mode [$($done)* (@native [$argument]),];)
    };
    (@p0 $mode:ident [$($done:tt)*]; $head:ident $(::$tail:ident)* ! $group:tt) => {
        $crate::__pgrx_c_classify!(
            @argument [__pgrx_c_args_MAXDEADITEMS] [p1 $mode [$($done)*] []] [
                $head $(::$tail)* ! $group
            ]
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; ::$head:ident $(::$tail:ident)* ! $group:tt) => {
        $crate::__pgrx_c_classify!(
            @argument [__pgrx_c_args_MAXDEADITEMS] [p1 $mode [$($done)*] []] [
                ::$head $(::$tail)* ! $group
            ]
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; ($($inner:tt)*)) => {
        $crate::__pgrx_c_classify!(
            @argument [__pgrx_c_args_MAXDEADITEMS] [p1 $mode [$($done)*] []] [($($inner)*)]
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; $argument:literal) => {
        $crate::__pgrx_c_args_MAXDEADITEMS!(@p1 $mode [$($done)* (@literal [$argument]),];)
    };
    (@p0 $mode:ident [$($done:tt)*]; $argument:expr) => {
        $crate::__pgrx_c_args_MAXDEADITEMS!(@p1 $mode [$($done)* (@native [$argument]),];)
    };
    (@p0 $mode:ident [$($done:tt)*]; (@__pgrx_c_native [$argument:expr]), $($rest:tt)*) => {
        $crate::__pgrx_c_args_MAXDEADITEMS!(@p1 $mode [$($done)* (@native [$argument]),]; $($rest)*)
    };
    (@p0 $mode:ident [$($done:tt)*]; $head:ident $(::$tail:ident)* ! $group:tt, $($rest:tt)*) => {
        $crate::__pgrx_c_classify!(
            @argument [__pgrx_c_args_MAXDEADITEMS] [p1 $mode [$($done)*] [$($rest)*]] [
                $head $(::$tail)* ! $group
            ]
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; ::$head:ident $(::$tail:ident)* ! $group:tt, $($rest:tt)*) => {
        $crate::__pgrx_c_classify!(
            @argument [__pgrx_c_args_MAXDEADITEMS] [p1 $mode [$($done)*] [$($rest)*]] [
                ::$head $(::$tail)* ! $group
            ]
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; ($($inner:tt)*), $($rest:tt)*) => {
        $crate::__pgrx_c_classify!(
            @argument [__pgrx_c_args_MAXDEADITEMS] [p1 $mode [$($done)*] [$($rest)*]] [($($inner)*)]
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; $argument:literal, $($rest:tt)*) => {
        $crate::__pgrx_c_args_MAXDEADITEMS!(
            @p1 $mode [$($done)* (@literal [$argument]),];
            $($rest)*
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; $argument:expr, $($rest:tt)*) => {
        $crate::__pgrx_c_args_MAXDEADITEMS!(@p1 $mode [$($done)* (@native [$argument]),]; $($rest)*)
    };
    (@p1 $mode:ident [$($done:tt)*];) => {
        $crate::MAXDEADITEMS!(@$mode; $($done)*)
    };
    ($($invalid:tt)*) => {
        compile_error!("arguments do not satisfy this C macro's invocation contract")
    };
}
/// C macro MAXDEADITEMS from vacuum.h:295
///
/// ```text
/// #define MAXDEADITEMS( avail_mem ) ( ( ( avail_mem ) - offsetof ( VacDeadItems , items ) ) / sizeof ( ItemPointerData ) )
/// ```
///
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Checked signed arithmetic rejects overflow when the recorded C profile does not define wrapping; pointer arithmetic checks representable offsets and distances but still requires valid allocation bounds. Integer division/remainder rejects zero divisors and signed MIN / -1 overflow. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! MAXDEADITEMS {
    (@__pgrx_emit_check_safety; $avail_mem:tt $(,)?) => {
        {
            if false {
                $crate::__pgrx_c_operand!(@check_safety; $avail_mem);
            }
        }
    };
    (@__pgrx_c_check_safety; $($raw:tt)*) => {
        $crate::__pgrx_c_args_MAXDEADITEMS!(@collect __pgrx_emit_check_safety []; $($raw)*)
    };
    (@__pgrx_emit_public; $avail_mem:tt $(,)?) => {
        $crate::__pgrx_c_macros::expression_result::finish(
            $crate::MAXDEADITEMS!(@__pgrx_emit_value; $avail_mem)
        )
    };
    (@__pgrx_emit_value; $avail_mem:tt $(,)?) => {
        /* PGRX: offsetof remains expanded because preserving a call inside this expression has not been proved equivalent to C substitution. */
        (
            $crate::__pgrx_c_macros::expression::profile_value::<true, _>(
                $crate::__pgrx_c_macros::expression::div(
                    (
                        $crate::__pgrx_c_macros::expression::profile_value::<true, _>(
                            $crate::__pgrx_c_macros::expression::sub::<
                                $crate::__pgrx_c_macros::Wrapping,
                                _,
                                _
                            >(
                                (
                                    $crate::__pgrx_c_macros::expression::profile_value::<true, _>(
                                        $crate::__pgrx_c_operand!(@value [true]; $avail_mem)
                                    )
                                ),
                                $crate::__pgrx_c_macros::expression::profile_value::<true, _>(
                                    $crate::__pgrx_c_macros::expression::offset_of::<
                                        $crate::__pgrx_c_macros::expression::CRecord<
                                            $crate::VacDeadItems
                                        >,
                                        $crate::__pgrx_c_field_marker!(@path; items)
                                    >()
                                )
                            )
                        )
                    ),
                    $crate::__pgrx_c_macros::expression::profile_value::<true, _>(
                        $crate::__pgrx_c_macros::expression::size_of::<
                            $crate::__pgrx_c_macros::expression::CRecord<$crate::ItemPointerData>>()
                    )
                )
            )
        )
    };
    (@__pgrx_c_value; $($raw:tt)*) => {
        $crate::__pgrx_c_args_MAXDEADITEMS!(@collect __pgrx_emit_value []; $($raw)*)
    };
    (@__pgrx_emit_place; $avail_mem:tt $(,)?) => {
        compile_error!("C expression is not a place in this operation")
    };
    (@__pgrx_c_place; $($raw:tt)*) => {
        $crate::__pgrx_c_args_MAXDEADITEMS!(@collect __pgrx_emit_place []; $($raw)*)
    };
    (@__pgrx_emit_read_place; $avail_mem:tt $(,)?) => {
        compile_error!("C expression is not a place in this operation")
    };
    (@__pgrx_c_read_place; $($raw:tt)*) => {
        $crate::__pgrx_c_args_MAXDEADITEMS!(@collect __pgrx_emit_read_place []; $($raw)*)
    };
    (@__pgrx_emit_size; $avail_mem:tt $(,)?) => {
        /* PGRX: offsetof remains expanded because preserving a call inside this expression has not been proved equivalent to C substitution. */
        $crate::__pgrx_c_macros::expression::size_of_value_type(
            if false {
                {
                    if false {
                        $crate::__pgrx_c_operand!(@check_safety; $avail_mem);
                    }
                }
                Some(
                    unsafe {
                        $crate::__pgrx_c_macros::expression::profile_value::<true, _>(
                            $crate::__pgrx_c_macros::expression::div(
                                (
                                    $crate::__pgrx_c_macros::expression::profile_value::<true, _>(
                                        $crate::__pgrx_c_macros::expression::sub::<
                                            $crate::__pgrx_c_macros::Wrapping,
                                            _,
                                            _
                                        >(
                                            (
                                                $crate::__pgrx_c_macros::expression::profile_value::<
                                                    true,
                                                    _
                                                >(
                                                    $crate::__pgrx_c_operand!(
                                                        @value [true];
                                                        $avail_mem
                                                    )
                                                )
                                            ),
                                            $crate::__pgrx_c_macros::expression::profile_value::<
                                                true,
                                                _
                                            >(
                                                $crate::__pgrx_c_macros::expression::offset_of::<
                                                    $crate::__pgrx_c_macros::expression::CRecord<
                                                        $crate::VacDeadItems
                                                    >,
                                                    $crate::__pgrx_c_field_marker!(@path; items)
                                                >()
                                            )
                                        )
                                    )
                                ),
                                $crate::__pgrx_c_macros::expression::profile_value::<true, _>(
                                    $crate::__pgrx_c_macros::expression::size_of::<
                                        $crate::__pgrx_c_macros::expression::CRecord<
                                            $crate::ItemPointerData
                                        >>()
                                )
                            )
                        )
                    }
                )
            } else {
                None
            }
        )
    };
    (@__pgrx_c_size; $($raw:tt)*) => {
        $crate::__pgrx_c_args_MAXDEADITEMS!(@collect __pgrx_emit_size []; $($raw)*)
    };
    (@__pgrx_emit_discard; $avail_mem:tt $(,)?) => {
        /* PGRX: offsetof remains expanded because preserving a call inside this expression has not been proved equivalent to C substitution. */
        {
            let _ = $crate::__pgrx_c_macros::expression::profile_value::<true, _>(
                $crate::__pgrx_c_macros::expression::div(
                    (
                        $crate::__pgrx_c_macros::expression::profile_value::<true, _>(
                            $crate::__pgrx_c_macros::expression::sub::<
                                $crate::__pgrx_c_macros::Wrapping,
                                _,
                                _
                            >(
                                (
                                    $crate::__pgrx_c_macros::expression::profile_value::<true, _>(
                                        $crate::__pgrx_c_operand!(@value [true]; $avail_mem)
                                    )
                                ),
                                $crate::__pgrx_c_macros::expression::profile_value::<true, _>(
                                    $crate::__pgrx_c_macros::expression::offset_of::<
                                        $crate::__pgrx_c_macros::expression::CRecord<
                                            $crate::VacDeadItems
                                        >,
                                        $crate::__pgrx_c_field_marker!(@path; items)
                                    >()
                                )
                            )
                        )
                    ),
                    $crate::__pgrx_c_macros::expression::profile_value::<true, _>(
                        $crate::__pgrx_c_macros::expression::size_of::<
                            $crate::__pgrx_c_macros::expression::CRecord<$crate::ItemPointerData>>()
                    )
                )
            );
        }
    };
    (@__pgrx_c_discard; $($raw:tt)*) => {
        $crate::__pgrx_c_args_MAXDEADITEMS!(@collect __pgrx_emit_discard []; $($raw)*)
    };
    ($($raw:tt)*) => {
        $crate::__pgrx_c_args_MAXDEADITEMS!(@collect __pgrx_emit_public []; $($raw)*)
    };
}

pub use MAXDEADITEMS;
