// Automatically generated by pgrx-c-macros for documentation. Do not hand-edit.
// C macros from trigger.h.

/// C macro CALLED_AS_TRIGGER from trigger.h:26 (PostgreSQL 15–19)
///
/// ```text
/// #define CALLED_AS_TRIGGER( fcinfo ) ( ( fcinfo ) -> context != NULL && IsA ( ( fcinfo ) -> context , TriggerData ) )
/// ```
///
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
///
/// # Panics
///
/// Conversions involving floats reject nonfinite or out-of-range integer results; conversions into Rust enums reject values without a represented discriminant. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! CALLED_AS_TRIGGER {
    ($fcinfo:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
/// C macro TRIGGER_FIRED_AFTER from trigger.h:133 (PostgreSQL 15–19)
///
/// ```text
/// #define TRIGGER_FIRED_AFTER( event ) ( ( ( event ) & TRIGGER_EVENT_TIMINGMASK ) == TRIGGER_EVENT_AFTER )
/// ```
///
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
#[macro_export]
macro_rules! TRIGGER_FIRED_AFTER {
    ($event:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
/// C macro TRIGGER_FIRED_BEFORE from trigger.h:130 (PostgreSQL 15–19)
///
/// ```text
/// #define TRIGGER_FIRED_BEFORE( event ) ( ( ( event ) & TRIGGER_EVENT_TIMINGMASK ) == TRIGGER_EVENT_BEFORE )
/// ```
///
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
#[macro_export]
macro_rules! TRIGGER_FIRED_BEFORE {
    ($event:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
/// C macro TRIGGER_FIRED_BY_DELETE from trigger.h:115 (PostgreSQL 15–19)
///
/// ```text
/// #define TRIGGER_FIRED_BY_DELETE( event ) ( ( ( event ) & TRIGGER_EVENT_OPMASK ) == TRIGGER_EVENT_DELETE )
/// ```
///
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
#[macro_export]
macro_rules! TRIGGER_FIRED_BY_DELETE {
    ($event:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
/// C macro TRIGGER_FIRED_BY_INSERT from trigger.h:112 (PostgreSQL 15–19)
///
/// ```text
/// #define TRIGGER_FIRED_BY_INSERT( event ) ( ( ( event ) & TRIGGER_EVENT_OPMASK ) == TRIGGER_EVENT_INSERT )
/// ```
///
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
#[macro_export]
macro_rules! TRIGGER_FIRED_BY_INSERT {
    ($event:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
/// C macro TRIGGER_FIRED_BY_TRUNCATE from trigger.h:121 (PostgreSQL 15–19)
///
/// ```text
/// #define TRIGGER_FIRED_BY_TRUNCATE( event ) ( ( ( event ) & TRIGGER_EVENT_OPMASK ) == TRIGGER_EVENT_TRUNCATE )
/// ```
///
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
#[macro_export]
macro_rules! TRIGGER_FIRED_BY_TRUNCATE {
    ($event:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
/// C macro TRIGGER_FIRED_BY_UPDATE from trigger.h:118 (PostgreSQL 15–19)
///
/// ```text
/// #define TRIGGER_FIRED_BY_UPDATE( event ) ( ( ( event ) & TRIGGER_EVENT_OPMASK ) == TRIGGER_EVENT_UPDATE )
/// ```
///
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
#[macro_export]
macro_rules! TRIGGER_FIRED_BY_UPDATE {
    ($event:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
/// C macro TRIGGER_FIRED_FOR_ROW from trigger.h:124 (PostgreSQL 15–19)
///
/// ```text
/// #define TRIGGER_FIRED_FOR_ROW( event ) ( ( event ) & TRIGGER_EVENT_ROW )
/// ```
///
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
#[macro_export]
macro_rules! TRIGGER_FIRED_FOR_ROW {
    ($event:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
/// C macro TRIGGER_FIRED_FOR_STATEMENT from trigger.h:127 (PostgreSQL 15–19)
///
/// ```text
/// #define TRIGGER_FIRED_FOR_STATEMENT( event ) ( ! TRIGGER_FIRED_FOR_ROW ( event ) )
/// ```
///
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
#[macro_export]
macro_rules! TRIGGER_FIRED_FOR_STATEMENT {
    ($event:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
/// C macro TRIGGER_FIRED_INSTEAD from trigger.h:136 (PostgreSQL 15–19)
///
/// ```text
/// #define TRIGGER_FIRED_INSTEAD( event ) ( ( ( event ) & TRIGGER_EVENT_TIMINGMASK ) == TRIGGER_EVENT_INSTEAD )
/// ```
///
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
#[macro_export]
macro_rules! TRIGGER_FIRED_INSTEAD {
    ($event:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
pub use CALLED_AS_TRIGGER;
pub use TRIGGER_FIRED_AFTER;
pub use TRIGGER_FIRED_BEFORE;
pub use TRIGGER_FIRED_BY_DELETE;
pub use TRIGGER_FIRED_BY_INSERT;
pub use TRIGGER_FIRED_BY_TRUNCATE;
pub use TRIGGER_FIRED_BY_UPDATE;
pub use TRIGGER_FIRED_FOR_ROW;
pub use TRIGGER_FIRED_FOR_STATEMENT;
pub use TRIGGER_FIRED_INSTEAD;
