// Automatically generated by pgrx-c-macros for documentation. Do not hand-edit.
// C macros from genbki.h.

/// C macro BKI_ARRAY_DEFAULT from genbki.h:37 (PostgreSQL 15–18), genbki.h:56 (PostgreSQL 19)
///
/// ```text
/// #define BKI_ARRAY_DEFAULT( value )
/// ```
///
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
#[macro_export]
macro_rules! BKI_ARRAY_DEFAULT {
    ($value:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
/// C macro BKI_DEFAULT from genbki.h:35 (PostgreSQL 15–18), genbki.h:54 (PostgreSQL 19)
///
/// ```text
/// #define BKI_DEFAULT( value )
/// ```
///
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
#[macro_export]
macro_rules! BKI_DEFAULT {
    ($value:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
/// C macro BKI_LOOKUP from genbki.h:46 (PostgreSQL 15–18), genbki.h:65 (PostgreSQL 19)
///
/// ```text
/// #define BKI_LOOKUP( catalog )
/// ```
///
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
#[macro_export]
macro_rules! BKI_LOOKUP {
    ($catalog:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
/// C macro BKI_LOOKUP_OPT from genbki.h:47 (PostgreSQL 15–18), genbki.h:66 (PostgreSQL 19)
///
/// ```text
/// #define BKI_LOOKUP_OPT( catalog )
/// ```
///
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
#[macro_export]
macro_rules! BKI_LOOKUP_OPT {
    ($catalog:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
/// C macro BKI_ROWTYPE_OID from genbki.h:28 (PostgreSQL 15–18), genbki.h:47 (PostgreSQL 19)
///
/// ```text
/// #define BKI_ROWTYPE_OID( oid , oidmacro )
/// ```
///
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
#[macro_export]
macro_rules! BKI_ROWTYPE_OID {
    ($oid:expr, $oidmacro:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
pub use BKI_ARRAY_DEFAULT;
pub use BKI_DEFAULT;
pub use BKI_LOOKUP;
pub use BKI_LOOKUP_OPT;
pub use BKI_ROWTYPE_OID;
