-- This file is auto generated by pgx.
-- `extension_sql!()` defined SQL.


-- Enums derived via `#[derive(PostgresEnum)]`


-- Shell types for types defined by `#[derive(PostgresType)]`


-- Functions defined by `#[pg_extern]`

-- src/lib.rs:31
-- srf::return_tuple
CREATE OR REPLACE FUNCTION "return_tuple"() RETURNS TABLE (
	"id" integer /* i32 */,
	"name" text /* &str */,
	"age" double precision /* f64 */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'return_tuple';

-- src/lib.rs:24
-- srf::vector_of_static_values
CREATE OR REPLACE FUNCTION "vector_of_static_values"() RETURNS SETOF str /* str */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'vector_of_static_values';

-- src/lib.rs:17
-- srf::random_values
CREATE OR REPLACE FUNCTION "random_values"(
	"num_rows" integer /* i32 */
) RETURNS TABLE (
	"index" integer /* i32 */,
	"value" double precision /* f64 */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'random_values';

-- src/lib.rs:8
-- srf::generate_series
CREATE OR REPLACE FUNCTION "generate_series"(
	"start" bigint ,/* i64 */
	"finish" bigint ,/* i64 */
	"step" bigint DEFAULT 1 /* i64 */
) RETURNS SETOF bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'generate_series';


-- Types defined by `#[derive(PostgresType)]`


-- Operator classes defined by `#[derive(PostgresHash, PostgresOrd)]`

