/* Automatically generated by pgrx-c-macros. Do not hand-edit.

This code is generated for documentation purposes, so that it is easy to reference on docs.rs. C macros and their support code are regenerated for your build of pgrx, and your Postgres configuration may differ.
*/
// C macros from off.h.

#[cfg(not(all(
    target_arch = "x86_64",
    target_os = "linux",
    target_pointer_width = "64",
    target_endian = "little"
)))]
#[cfg(not(docsrs))]
compile_error!("generated C macros require their inspected C target profile");
const _: () = {
    use crate::__pgrx_c_macros::CInteger as _;
    assert!(crate::__pgrx_c_macros::CChar::SIGNED == true);
    assert!(crate::__pgrx_c_macros::CLong::BITS == 64);
    assert!(crate::__pgrx_c_macros::CSize::BITS == 64);
    assert!(crate::__pgrx_c_macros::CSize::RANK == 4);
    assert!(!crate::__pgrx_c_macros::CSize::SIGNED);
    assert!(crate::__pgrx_c_macros::CPtrDiff::BITS == 64);
    assert!(crate::__pgrx_c_macros::CPtrDiff::RANK == 4);
    assert!(crate::__pgrx_c_macros::CPtrDiff::SIGNED);
};
#[doc(hidden)]
#[macro_export]
macro_rules! __pgrx_c_args_OffsetNumberIsValid {
    (@collect $mode:ident [$($done:tt)*]; $($raw:tt)*) => {
        $crate::__pgrx_c_args_OffsetNumberIsValid!(@p0 $mode [$($done)*]; $($raw)*)
    };
    (@classified [$next:ident $mode:ident [$($done:tt)*] [$($rest:tt)*]] $descriptor:tt) => {
        $crate::__pgrx_c_args_OffsetNumberIsValid!(@$next $mode [$($done)* $descriptor,]; $($rest)*)
    };
    (@p0 $mode:ident [$($done:tt)*]; - $argument:literal) => {
        compile_error!("an ungrouped C parameter requires a parenthesized negative literal")
    };
    (@negative0 $mode:ident [$($done:tt)*]; $argument:expr) => {
        $crate::__pgrx_c_args_OffsetNumberIsValid!(
            @p1 $mode [$($done)* (@original [$argument] (@native [$argument])),];
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; - $argument:literal, $($rest:tt)*) => {
        compile_error!("an ungrouped C parameter requires a parenthesized negative literal")
    };
    (@negative0 $mode:ident [$($done:tt)*]; $argument:expr, $($rest:tt)*) => {
        $crate::__pgrx_c_args_OffsetNumberIsValid!(
            @p1 $mode [$($done)* (@original [$argument] (@native [$argument])),];
            $($rest)*
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; - $($raw:tt)*) => {
        compile_error!("an ungrouped C parameter requires one token tree")
    };
    (@p0 $mode:ident [$($done:tt)*]; (@__pgrx_c_native [$argument:expr])) => {
        $crate::__pgrx_c_args_OffsetNumberIsValid!(
            @p1 $mode [$($done)* (@original [$argument] (@native [$argument])),];
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; $head:ident $(::$tail:ident)* ! $group:tt) => {
        $crate::__pgrx_c_classify!(
            @argument [__pgrx_c_args_OffsetNumberIsValid] [p1 $mode [$($done)*] []] [
                $head $(::$tail)* ! $group
            ]
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; ::$head:ident $(::$tail:ident)* ! $group:tt) => {
        $crate::__pgrx_c_classify!(
            @argument [__pgrx_c_args_OffsetNumberIsValid] [p1 $mode [$($done)*] []] [
                ::$head $(::$tail)* ! $group
            ]
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; ($($inner:tt)*)) => {
        $crate::__pgrx_c_classify!(
            @argument [__pgrx_c_args_OffsetNumberIsValid] [p1 $mode [$($done)*] []] [($($inner)*)]
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; $argument:literal) => {
        $crate::__pgrx_c_args_OffsetNumberIsValid!(
            @p1 $mode [$($done)* (@original [$argument] (@literal [$argument])),];
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; $argument:tt) => {
        $crate::__pgrx_c_args_OffsetNumberIsValid!(
            @p1 $mode [$($done)* (@original [$argument] (@native [$argument])),];
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; (@__pgrx_c_native [$argument:expr]), $($rest:tt)*) => {
        $crate::__pgrx_c_args_OffsetNumberIsValid!(
            @p1 $mode [$($done)* (@original [$argument] (@native [$argument])),];
            $($rest)*
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; $head:ident $(::$tail:ident)* ! $group:tt, $($rest:tt)*) => {
        $crate::__pgrx_c_classify!(
            @argument [__pgrx_c_args_OffsetNumberIsValid] [p1 $mode [$($done)*] [$($rest)*]] [
                $head $(::$tail)* ! $group
            ]
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; ::$head:ident $(::$tail:ident)* ! $group:tt, $($rest:tt)*) => {
        $crate::__pgrx_c_classify!(
            @argument [__pgrx_c_args_OffsetNumberIsValid] [p1 $mode [$($done)*] [$($rest)*]] [
                ::$head $(::$tail)* ! $group
            ]
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; ($($inner:tt)*), $($rest:tt)*) => {
        $crate::__pgrx_c_classify!(
            @argument [__pgrx_c_args_OffsetNumberIsValid] [p1 $mode [$($done)*] [$($rest)*]] [
                ($($inner)*)
            ]
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; $argument:literal, $($rest:tt)*) => {
        $crate::__pgrx_c_args_OffsetNumberIsValid!(
            @p1 $mode [$($done)* (@original [$argument] (@literal [$argument])),];
            $($rest)*
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; $argument:tt, $($rest:tt)*) => {
        $crate::__pgrx_c_args_OffsetNumberIsValid!(
            @p1 $mode [$($done)* (@original [$argument] (@native [$argument])),];
            $($rest)*
        )
    };
    (@p1 $mode:ident [$($done:tt)*];) => {
        $crate::OffsetNumberIsValid!(@$mode; $($done)*)
    };
    ($($invalid:tt)*) => {
        compile_error!("arguments do not satisfy this C macro's invocation contract")
    };
}
/// C macro OffsetNumberIsValid from off.h:39
///
/// ```text
/// #define OffsetNumberIsValid( offsetNumber ) ( ( bool ) ( ( offsetNumber != InvalidOffsetNumber ) && ( offsetNumber <= MaxOffsetNumber ) ) )
/// ```
///
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Conversions involving floats reject nonfinite or out-of-range integer results; conversions into Rust enums reject values without a represented discriminant. Integer division/remainder rejects zero divisors and signed MIN / -1 overflow. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! OffsetNumberIsValid {
    (@__pgrx_emit_check_safety; $offsetNumber:tt $(,)?) => {
        {
            if false {
                $crate::__pgrx_c_operand!(@check_safety; $offsetNumber);
            }
        }
    };
    (@__pgrx_c_check_safety; $($raw:tt)*) => {
        $crate::__pgrx_c_args_OffsetNumberIsValid!(@collect __pgrx_emit_check_safety []; $($raw)*)
    };
    (@__pgrx_emit_public; $offsetNumber:tt $(,)?) => {
        $crate::__pgrx_c_macros::expression_result::finish(
            $crate::OffsetNumberIsValid!(@__pgrx_emit_value; $offsetNumber)
        )
    };
    (@__pgrx_emit_value; $offsetNumber:tt $(,)?) => {
        /* PGRX: MaxOffsetNumber remains expanded because object macro is not a supported pure integer expression: constant probes cannot evaluate calls, variables, memory or mutation. */ /* PGRX: bool remains expanded because object macro is not a supported pure integer expression: compiler and declaration keywords require a dedicated syntax contract. */
        (
            $crate::__pgrx_c_macros::expression::profile_value::<true, _>(
                $crate::__pgrx_c_macros::expression::cast::<$crate::__pgrx_c_macros::CBool, _>(
                    (
                        $crate::__pgrx_c_macros::expression::profile_value::<true, _>(
                            $crate::__pgrx_c_macros::CValue::<$crate::__pgrx_c_macros::CInt>::new(
                                if $crate::__pgrx_c_macros::expression::truth(
                                    (
                                        $crate::__pgrx_c_macros::expression::profile_value::<
                                            true,
                                            _
                                        >(
                                            $crate::__pgrx_c_macros::expression::ne(
                                                $crate::__pgrx_c_macros::expression::profile_value::<
                                                    true,
                                                    _
                                                >(
                                                    $crate::__pgrx_c_operand!(
                                                        @value [true];
                                                        $offsetNumber
                                                    )
                                                ),
                                                $crate::__pgrx_c_macros::expression::profile_value::<
                                                    true,
                                                    _
                                                >(
                                                    $crate::__pgrx_c_macros::expression::null_constant(
                                                        $crate::__pgrx_c_macros::CValue::<
                                                            $crate::__pgrx_c_macros::CUnsignedShort
                                                        >::new(
                                                            $crate::__pgrx_c_bindings::InvalidOffsetNumber as u16
                                                        )
                                                    )
                                                )
                                            )
                                        )
                                    )
                                ) && $crate::__pgrx_c_macros::expression::truth(
                                    (
                                        $crate::__pgrx_c_macros::expression::profile_value::<
                                            true,
                                            _
                                        >(
                                            $crate::__pgrx_c_macros::expression::le(
                                                $crate::__pgrx_c_macros::expression::profile_value::<
                                                    true,
                                                    _
                                                >(
                                                    $crate::__pgrx_c_operand!(
                                                        @value [true];
                                                        $offsetNumber
                                                    )
                                                ),
                                                (
                                                    $crate::__pgrx_c_macros::expression::profile_value::<
                                                        true,
                                                        _
                                                    >(
                                                        $crate::__pgrx_c_macros::expression::cast_as::<
                                                            $crate::__pgrx_c_bindings::OffsetNumber,
                                                            $crate::__pgrx_c_macros::CUnsignedShort,
                                                            _
                                                        >(
                                                            (
                                                                $crate::__pgrx_c_macros::expression::profile_value::<
                                                                    true,
                                                                    _
                                                                >(
                                                                    $crate::__pgrx_c_macros::expression::div(
                                                                        $crate::__pgrx_c_macros::expression::profile_value::<
                                                                            true,
                                                                            _
                                                                        >(
                                                                            $crate::__pgrx_c_macros::CValue::<
                                                                                $crate::__pgrx_c_macros::CInt
                                                                            >::new(
                                                                                $crate::__pgrx_c_bindings::BLCKSZ as i32
                                                                            )
                                                                        ),
                                                                        $crate::__pgrx_c_macros::expression::profile_value::<
                                                                            true,
                                                                            _
                                                                        >(
                                                                            $crate::__pgrx_c_macros::expression::size_of::<
                                                                                $crate::__pgrx_c_macros::expression::CRecord<
                                                                                    $crate::__pgrx_c_bindings::ItemIdData
                                                                                >>()
                                                                        )
                                                                    )
                                                                )
                                                            )
                                                        )
                                                    )
                                                )
                                            )
                                        )
                                    )
                                ) {
                                    1
                                } else {
                                    0
                                }
                            )
                        )
                    )
                )
            )
        )
    };
    (@__pgrx_c_value; $($raw:tt)*) => {
        $crate::__pgrx_c_args_OffsetNumberIsValid!(@collect __pgrx_emit_value []; $($raw)*)
    };
    (@__pgrx_emit_place; $offsetNumber:tt $(,)?) => {
        compile_error!("C expression is not a place in this operation")
    };
    (@__pgrx_c_place; $($raw:tt)*) => {
        $crate::__pgrx_c_args_OffsetNumberIsValid!(@collect __pgrx_emit_place []; $($raw)*)
    };
    (@__pgrx_emit_read_place; $offsetNumber:tt $(,)?) => {
        compile_error!("C expression is not a place in this operation")
    };
    (@__pgrx_c_read_place; $($raw:tt)*) => {
        $crate::__pgrx_c_args_OffsetNumberIsValid!(@collect __pgrx_emit_read_place []; $($raw)*)
    };
    (@__pgrx_emit_size; $offsetNumber:tt $(,)?) => {
        /* PGRX: MaxOffsetNumber remains expanded because object macro is not a supported pure integer expression: constant probes cannot evaluate calls, variables, memory or mutation. */ /* PGRX: bool remains expanded because object macro is not a supported pure integer expression: compiler and declaration keywords require a dedicated syntax contract. */
        $crate::__pgrx_c_macros::expression::size_of_value_type(
            if false {
                {
                    if false {
                        $crate::__pgrx_c_operand!(@check_safety; $offsetNumber);
                    }
                }
                Some(
                    unsafe {
                        $crate::__pgrx_c_macros::expression::profile_value::<true, _>(
                            $crate::__pgrx_c_macros::expression::cast::<
                                $crate::__pgrx_c_macros::CBool,
                                _
                            >(
                                (
                                    $crate::__pgrx_c_macros::expression::profile_value::<true, _>(
                                        $crate::__pgrx_c_macros::CValue::<
                                            $crate::__pgrx_c_macros::CInt
                                        >::new(
                                            if $crate::__pgrx_c_macros::expression::truth(
                                                (
                                                    $crate::__pgrx_c_macros::expression::profile_value::<
                                                        true,
                                                        _
                                                    >(
                                                        $crate::__pgrx_c_macros::expression::ne(
                                                            $crate::__pgrx_c_macros::expression::profile_value::<
                                                                true,
                                                                _
                                                            >(
                                                                $crate::__pgrx_c_operand!(
                                                                    @value [true];
                                                                    $offsetNumber
                                                                )
                                                            ),
                                                            $crate::__pgrx_c_macros::expression::profile_value::<
                                                                true,
                                                                _
                                                            >(
                                                                $crate::__pgrx_c_macros::expression::null_constant(
                                                                    $crate::__pgrx_c_macros::CValue::<
                                                                        $crate::__pgrx_c_macros::CUnsignedShort
                                                                    >::new(
                                                                        $crate::__pgrx_c_bindings::InvalidOffsetNumber as u16
                                                                    )
                                                                )
                                                            )
                                                        )
                                                    )
                                                )
                                            ) && $crate::__pgrx_c_macros::expression::truth(
                                                (
                                                    $crate::__pgrx_c_macros::expression::profile_value::<
                                                        true,
                                                        _
                                                    >(
                                                        $crate::__pgrx_c_macros::expression::le(
                                                            $crate::__pgrx_c_macros::expression::profile_value::<
                                                                true,
                                                                _
                                                            >(
                                                                $crate::__pgrx_c_operand!(
                                                                    @value [true];
                                                                    $offsetNumber
                                                                )
                                                            ),
                                                            (
                                                                $crate::__pgrx_c_macros::expression::profile_value::<
                                                                    true,
                                                                    _
                                                                >(
                                                                    $crate::__pgrx_c_macros::expression::cast_as::<
                                                                        $crate::__pgrx_c_bindings::OffsetNumber,
                                                                        $crate::__pgrx_c_macros::CUnsignedShort,
                                                                        _
                                                                    >(
                                                                        (
                                                                            $crate::__pgrx_c_macros::expression::profile_value::<
                                                                                true,
                                                                                _
                                                                            >(
                                                                                $crate::__pgrx_c_macros::expression::div(
                                                                                    $crate::__pgrx_c_macros::expression::profile_value::<
                                                                                        true,
                                                                                        _
                                                                                    >(
                                                                                        $crate::__pgrx_c_macros::CValue::<
                                                                                            $crate::__pgrx_c_macros::CInt
                                                                                        >::new(
                                                                                            $crate::__pgrx_c_bindings::BLCKSZ as i32
                                                                                        )
                                                                                    ),
                                                                                    $crate::__pgrx_c_macros::expression::profile_value::<
                                                                                        true,
                                                                                        _
                                                                                    >(
                                                                                        $crate::__pgrx_c_macros::expression::size_of::<
                                                                                            $crate::__pgrx_c_macros::expression::CRecord<
                                                                                                $crate::__pgrx_c_bindings::ItemIdData
                                                                                            >>()
                                                                                    )
                                                                                )
                                                                            )
                                                                        )
                                                                    )
                                                                )
                                                            )
                                                        )
                                                    )
                                                )
                                            ) {
                                                1
                                            } else {
                                                0
                                            }
                                        )
                                    )
                                )
                            )
                        )
                    }
                )
            } else {
                None
            }
        )
    };
    (@__pgrx_c_size; $($raw:tt)*) => {
        $crate::__pgrx_c_args_OffsetNumberIsValid!(@collect __pgrx_emit_size []; $($raw)*)
    };
    (@__pgrx_emit_discard; $offsetNumber:tt $(,)?) => {
        /* PGRX: MaxOffsetNumber remains expanded because object macro is not a supported pure integer expression: constant probes cannot evaluate calls, variables, memory or mutation. */ /* PGRX: bool remains expanded because object macro is not a supported pure integer expression: compiler and declaration keywords require a dedicated syntax contract. */
        {
            let _ = $crate::__pgrx_c_macros::expression::profile_value::<true, _>(
                $crate::__pgrx_c_macros::expression::cast::<$crate::__pgrx_c_macros::CBool, _>(
                    (
                        $crate::__pgrx_c_macros::expression::profile_value::<true, _>(
                            $crate::__pgrx_c_macros::CValue::<$crate::__pgrx_c_macros::CInt>::new(
                                if $crate::__pgrx_c_macros::expression::truth(
                                    (
                                        $crate::__pgrx_c_macros::expression::profile_value::<
                                            true,
                                            _
                                        >(
                                            $crate::__pgrx_c_macros::expression::ne(
                                                $crate::__pgrx_c_macros::expression::profile_value::<
                                                    true,
                                                    _
                                                >(
                                                    $crate::__pgrx_c_operand!(
                                                        @value [true];
                                                        $offsetNumber
                                                    )
                                                ),
                                                $crate::__pgrx_c_macros::expression::profile_value::<
                                                    true,
                                                    _
                                                >(
                                                    $crate::__pgrx_c_macros::expression::null_constant(
                                                        $crate::__pgrx_c_macros::CValue::<
                                                            $crate::__pgrx_c_macros::CUnsignedShort
                                                        >::new(
                                                            $crate::__pgrx_c_bindings::InvalidOffsetNumber as u16
                                                        )
                                                    )
                                                )
                                            )
                                        )
                                    )
                                ) && $crate::__pgrx_c_macros::expression::truth(
                                    (
                                        $crate::__pgrx_c_macros::expression::profile_value::<
                                            true,
                                            _
                                        >(
                                            $crate::__pgrx_c_macros::expression::le(
                                                $crate::__pgrx_c_macros::expression::profile_value::<
                                                    true,
                                                    _
                                                >(
                                                    $crate::__pgrx_c_operand!(
                                                        @value [true];
                                                        $offsetNumber
                                                    )
                                                ),
                                                (
                                                    $crate::__pgrx_c_macros::expression::profile_value::<
                                                        true,
                                                        _
                                                    >(
                                                        $crate::__pgrx_c_macros::expression::cast_as::<
                                                            $crate::__pgrx_c_bindings::OffsetNumber,
                                                            $crate::__pgrx_c_macros::CUnsignedShort,
                                                            _
                                                        >(
                                                            (
                                                                $crate::__pgrx_c_macros::expression::profile_value::<
                                                                    true,
                                                                    _
                                                                >(
                                                                    $crate::__pgrx_c_macros::expression::div(
                                                                        $crate::__pgrx_c_macros::expression::profile_value::<
                                                                            true,
                                                                            _
                                                                        >(
                                                                            $crate::__pgrx_c_macros::CValue::<
                                                                                $crate::__pgrx_c_macros::CInt
                                                                            >::new(
                                                                                $crate::__pgrx_c_bindings::BLCKSZ as i32
                                                                            )
                                                                        ),
                                                                        $crate::__pgrx_c_macros::expression::profile_value::<
                                                                            true,
                                                                            _
                                                                        >(
                                                                            $crate::__pgrx_c_macros::expression::size_of::<
                                                                                $crate::__pgrx_c_macros::expression::CRecord<
                                                                                    $crate::__pgrx_c_bindings::ItemIdData
                                                                                >>()
                                                                        )
                                                                    )
                                                                )
                                                            )
                                                        )
                                                    )
                                                )
                                            )
                                        )
                                    )
                                ) {
                                    1
                                } else {
                                    0
                                }
                            )
                        )
                    )
                )
            );
        }
    };
    (@__pgrx_c_discard; $($raw:tt)*) => {
        $crate::__pgrx_c_args_OffsetNumberIsValid!(@collect __pgrx_emit_discard []; $($raw)*)
    };
    ($($raw:tt)*) => {
        $crate::__pgrx_c_args_OffsetNumberIsValid!(@collect __pgrx_emit_public []; $($raw)*)
    };
}

#[cfg(not(all(
    target_arch = "x86_64",
    target_os = "linux",
    target_pointer_width = "64",
    target_endian = "little"
)))]
#[cfg(not(docsrs))]
compile_error!("generated C macros require their inspected C target profile");
const _: () = {
    use crate::__pgrx_c_macros::CInteger as _;
    assert!(crate::__pgrx_c_macros::CChar::SIGNED == true);
    assert!(crate::__pgrx_c_macros::CLong::BITS == 64);
    assert!(crate::__pgrx_c_macros::CSize::BITS == 64);
    assert!(crate::__pgrx_c_macros::CSize::RANK == 4);
    assert!(!crate::__pgrx_c_macros::CSize::SIGNED);
    assert!(crate::__pgrx_c_macros::CPtrDiff::BITS == 64);
    assert!(crate::__pgrx_c_macros::CPtrDiff::RANK == 4);
    assert!(crate::__pgrx_c_macros::CPtrDiff::SIGNED);
};
#[doc(hidden)]
#[macro_export]
macro_rules! __pgrx_c_args_OffsetNumberNext {
    (@collect $mode:ident [$($done:tt)*]; $($raw:tt)*) => {
        $crate::__pgrx_c_args_OffsetNumberNext!(@p0 $mode [$($done)*]; $($raw)*)
    };
    (@classified [$next:ident $mode:ident [$($done:tt)*] [$($rest:tt)*]] $descriptor:tt) => {
        $crate::__pgrx_c_args_OffsetNumberNext!(@$next $mode [$($done)* $descriptor,]; $($rest)*)
    };
    (@p0 $mode:ident [$($done:tt)*]; - $argument:literal) => {
        $crate::__pgrx_c_args_OffsetNumberNext!(
            @p1 $mode [$($done)* (@original [- $argument] (@literal [- $argument])),];
        )
    };
    (@negative0 $mode:ident [$($done:tt)*]; $argument:expr) => {
        $crate::__pgrx_c_args_OffsetNumberNext!(
            @p1 $mode [$($done)* (@original [$argument] (@native [$argument])),];
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; - $argument:literal, $($rest:tt)*) => {
        $crate::__pgrx_c_args_OffsetNumberNext!(
            @p1 $mode [$($done)* (@original [- $argument] (@literal [- $argument])),];
            $($rest)*
        )
    };
    (@negative0 $mode:ident [$($done:tt)*]; $argument:expr, $($rest:tt)*) => {
        $crate::__pgrx_c_args_OffsetNumberNext!(
            @p1 $mode [$($done)* (@original [$argument] (@native [$argument])),];
            $($rest)*
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; - $($raw:tt)*) => {
        $crate::__pgrx_c_args_OffsetNumberNext!(@negative0 $mode [$($done)*]; - $($raw)*)
    };
    (@p0 $mode:ident [$($done:tt)*]; (@__pgrx_c_native [$argument:expr])) => {
        $crate::__pgrx_c_args_OffsetNumberNext!(
            @p1 $mode [$($done)* (@original [$argument] (@native [$argument])),];
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; $head:ident $(::$tail:ident)* ! $group:tt) => {
        $crate::__pgrx_c_classify!(
            @argument [__pgrx_c_args_OffsetNumberNext] [p1 $mode [$($done)*] []] [
                $head $(::$tail)* ! $group
            ]
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; ::$head:ident $(::$tail:ident)* ! $group:tt) => {
        $crate::__pgrx_c_classify!(
            @argument [__pgrx_c_args_OffsetNumberNext] [p1 $mode [$($done)*] []] [
                ::$head $(::$tail)* ! $group
            ]
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; ($($inner:tt)*)) => {
        $crate::__pgrx_c_classify!(
            @argument [__pgrx_c_args_OffsetNumberNext] [p1 $mode [$($done)*] []] [($($inner)*)]
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; $argument:literal) => {
        $crate::__pgrx_c_args_OffsetNumberNext!(
            @p1 $mode [$($done)* (@original [$argument] (@literal [$argument])),];
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; $argument:expr) => {
        $crate::__pgrx_c_args_OffsetNumberNext!(
            @p1 $mode [$($done)* (@original [$argument] (@native [$argument])),];
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; (@__pgrx_c_native [$argument:expr]), $($rest:tt)*) => {
        $crate::__pgrx_c_args_OffsetNumberNext!(
            @p1 $mode [$($done)* (@original [$argument] (@native [$argument])),];
            $($rest)*
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; $head:ident $(::$tail:ident)* ! $group:tt, $($rest:tt)*) => {
        $crate::__pgrx_c_classify!(
            @argument [__pgrx_c_args_OffsetNumberNext] [p1 $mode [$($done)*] [$($rest)*]] [
                $head $(::$tail)* ! $group
            ]
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; ::$head:ident $(::$tail:ident)* ! $group:tt, $($rest:tt)*) => {
        $crate::__pgrx_c_classify!(
            @argument [__pgrx_c_args_OffsetNumberNext] [p1 $mode [$($done)*] [$($rest)*]] [
                ::$head $(::$tail)* ! $group
            ]
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; ($($inner:tt)*), $($rest:tt)*) => {
        $crate::__pgrx_c_classify!(
            @argument [__pgrx_c_args_OffsetNumberNext] [p1 $mode [$($done)*] [$($rest)*]] [
                ($($inner)*)
            ]
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; $argument:literal, $($rest:tt)*) => {
        $crate::__pgrx_c_args_OffsetNumberNext!(
            @p1 $mode [$($done)* (@original [$argument] (@literal [$argument])),];
            $($rest)*
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; $argument:expr, $($rest:tt)*) => {
        $crate::__pgrx_c_args_OffsetNumberNext!(
            @p1 $mode [$($done)* (@original [$argument] (@native [$argument])),];
            $($rest)*
        )
    };
    (@p1 $mode:ident [$($done:tt)*];) => {
        $crate::OffsetNumberNext!(@$mode; $($done)*)
    };
    ($($invalid:tt)*) => {
        compile_error!("arguments do not satisfy this C macro's invocation contract")
    };
}
/// C macro OffsetNumberNext from off.h:52
///
/// ```text
/// #define OffsetNumberNext( offsetNumber ) ( ( OffsetNumber ) ( 1 + ( offsetNumber ) ) )
/// ```
///
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Checked signed arithmetic rejects overflow when the recorded C profile does not define wrapping; pointer arithmetic checks representable offsets and distances but still requires valid allocation bounds. Conversions involving floats reject nonfinite or out-of-range integer results; conversions into Rust enums reject values without a represented discriminant. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! OffsetNumberNext {
    (@__pgrx_emit_check_safety; $offsetNumber:tt $(,)?) => {
        {
            if false {
                $crate::__pgrx_c_operand!(@check_safety; $offsetNumber);
            }
        }
    };
    (@__pgrx_c_check_safety; $($raw:tt)*) => {
        $crate::__pgrx_c_args_OffsetNumberNext!(@collect __pgrx_emit_check_safety []; $($raw)*)
    };
    (@__pgrx_emit_public; $offsetNumber:tt $(,)?) => {
        $crate::__pgrx_c_macros::expression_result::finish(
            $crate::OffsetNumberNext!(@__pgrx_emit_value; $offsetNumber)
        )
    };
    (@__pgrx_emit_value; $offsetNumber:tt $(,)?) => {
        (
            $crate::__pgrx_c_macros::expression::profile_value::<true, _>(
                $crate::__pgrx_c_macros::expression::cast_as::<
                    $crate::__pgrx_c_bindings::OffsetNumber,
                    $crate::__pgrx_c_macros::CUnsignedShort,
                    _
                >(
                    (
                        $crate::__pgrx_c_macros::expression::profile_value::<true, _>(
                            $crate::__pgrx_c_macros::expression::add::<
                                $crate::__pgrx_c_macros::Wrapping,
                                _,
                                _
                            >(
                                $crate::__pgrx_c_macros::expression::profile_value::<true, _>(
                                    $crate::__pgrx_c_macros::CValue::<$crate::__pgrx_c_macros::CInt>::new(
                                        1i32
                                    )
                                ),
                                (
                                    $crate::__pgrx_c_macros::expression::profile_value::<true, _>(
                                        $crate::__pgrx_c_operand!(@value [true]; $offsetNumber)
                                    )
                                )
                            )
                        )
                    )
                )
            )
        )
    };
    (@__pgrx_c_value; $($raw:tt)*) => {
        $crate::__pgrx_c_args_OffsetNumberNext!(@collect __pgrx_emit_value []; $($raw)*)
    };
    (@__pgrx_emit_place; $offsetNumber:tt $(,)?) => {
        compile_error!("C expression is not a place in this operation")
    };
    (@__pgrx_c_place; $($raw:tt)*) => {
        $crate::__pgrx_c_args_OffsetNumberNext!(@collect __pgrx_emit_place []; $($raw)*)
    };
    (@__pgrx_emit_read_place; $offsetNumber:tt $(,)?) => {
        compile_error!("C expression is not a place in this operation")
    };
    (@__pgrx_c_read_place; $($raw:tt)*) => {
        $crate::__pgrx_c_args_OffsetNumberNext!(@collect __pgrx_emit_read_place []; $($raw)*)
    };
    (@__pgrx_emit_size; $offsetNumber:tt $(,)?) => {
        $crate::__pgrx_c_macros::expression::size_of_value_type(
            if false {
                {
                    if false {
                        $crate::__pgrx_c_operand!(@check_safety; $offsetNumber);
                    }
                }
                Some(
                    unsafe {
                        $crate::__pgrx_c_macros::expression::profile_value::<true, _>(
                            $crate::__pgrx_c_macros::expression::cast_as::<
                                $crate::__pgrx_c_bindings::OffsetNumber,
                                $crate::__pgrx_c_macros::CUnsignedShort,
                                _
                            >(
                                (
                                    $crate::__pgrx_c_macros::expression::profile_value::<true, _>(
                                        $crate::__pgrx_c_macros::expression::add::<
                                            $crate::__pgrx_c_macros::Wrapping,
                                            _,
                                            _
                                        >(
                                            $crate::__pgrx_c_macros::expression::profile_value::<
                                                true,
                                                _
                                            >(
                                                $crate::__pgrx_c_macros::CValue::<
                                                    $crate::__pgrx_c_macros::CInt
                                                >::new(1i32)
                                            ),
                                            (
                                                $crate::__pgrx_c_macros::expression::profile_value::<
                                                    true,
                                                    _
                                                >(
                                                    $crate::__pgrx_c_operand!(
                                                        @value [true];
                                                        $offsetNumber
                                                    )
                                                )
                                            )
                                        )
                                    )
                                )
                            )
                        )
                    }
                )
            } else {
                None
            }
        )
    };
    (@__pgrx_c_size; $($raw:tt)*) => {
        $crate::__pgrx_c_args_OffsetNumberNext!(@collect __pgrx_emit_size []; $($raw)*)
    };
    (@__pgrx_emit_discard; $offsetNumber:tt $(,)?) => {
        {
            let _ = $crate::__pgrx_c_macros::expression::profile_value::<true, _>(
                $crate::__pgrx_c_macros::expression::cast_as::<
                    $crate::__pgrx_c_bindings::OffsetNumber,
                    $crate::__pgrx_c_macros::CUnsignedShort,
                    _
                >(
                    (
                        $crate::__pgrx_c_macros::expression::profile_value::<true, _>(
                            $crate::__pgrx_c_macros::expression::add::<
                                $crate::__pgrx_c_macros::Wrapping,
                                _,
                                _
                            >(
                                $crate::__pgrx_c_macros::expression::profile_value::<true, _>(
                                    $crate::__pgrx_c_macros::CValue::<$crate::__pgrx_c_macros::CInt>::new(
                                        1i32
                                    )
                                ),
                                (
                                    $crate::__pgrx_c_macros::expression::profile_value::<true, _>(
                                        $crate::__pgrx_c_operand!(@value [true]; $offsetNumber)
                                    )
                                )
                            )
                        )
                    )
                )
            );
        }
    };
    (@__pgrx_c_discard; $($raw:tt)*) => {
        $crate::__pgrx_c_args_OffsetNumberNext!(@collect __pgrx_emit_discard []; $($raw)*)
    };
    ($($raw:tt)*) => {
        $crate::__pgrx_c_args_OffsetNumberNext!(@collect __pgrx_emit_public []; $($raw)*)
    };
}

#[cfg(not(all(
    target_arch = "x86_64",
    target_os = "linux",
    target_pointer_width = "64",
    target_endian = "little"
)))]
#[cfg(not(docsrs))]
compile_error!("generated C macros require their inspected C target profile");
const _: () = {
    use crate::__pgrx_c_macros::CInteger as _;
    assert!(crate::__pgrx_c_macros::CChar::SIGNED == true);
    assert!(crate::__pgrx_c_macros::CLong::BITS == 64);
    assert!(crate::__pgrx_c_macros::CSize::BITS == 64);
    assert!(crate::__pgrx_c_macros::CSize::RANK == 4);
    assert!(!crate::__pgrx_c_macros::CSize::SIGNED);
    assert!(crate::__pgrx_c_macros::CPtrDiff::BITS == 64);
    assert!(crate::__pgrx_c_macros::CPtrDiff::RANK == 4);
    assert!(crate::__pgrx_c_macros::CPtrDiff::SIGNED);
};
#[doc(hidden)]
#[macro_export]
macro_rules! __pgrx_c_args_OffsetNumberPrev {
    (@collect $mode:ident [$($done:tt)*]; $($raw:tt)*) => {
        $crate::__pgrx_c_args_OffsetNumberPrev!(@p0 $mode [$($done)*]; $($raw)*)
    };
    (@classified [$next:ident $mode:ident [$($done:tt)*] [$($rest:tt)*]] $descriptor:tt) => {
        $crate::__pgrx_c_args_OffsetNumberPrev!(@$next $mode [$($done)* $descriptor,]; $($rest)*)
    };
    (@p0 $mode:ident [$($done:tt)*]; - $argument:literal) => {
        $crate::__pgrx_c_args_OffsetNumberPrev!(
            @p1 $mode [$($done)* (@original [- $argument] (@literal [- $argument])),];
        )
    };
    (@negative0 $mode:ident [$($done:tt)*]; $argument:expr) => {
        $crate::__pgrx_c_args_OffsetNumberPrev!(
            @p1 $mode [$($done)* (@original [$argument] (@native [$argument])),];
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; - $argument:literal, $($rest:tt)*) => {
        $crate::__pgrx_c_args_OffsetNumberPrev!(
            @p1 $mode [$($done)* (@original [- $argument] (@literal [- $argument])),];
            $($rest)*
        )
    };
    (@negative0 $mode:ident [$($done:tt)*]; $argument:expr, $($rest:tt)*) => {
        $crate::__pgrx_c_args_OffsetNumberPrev!(
            @p1 $mode [$($done)* (@original [$argument] (@native [$argument])),];
            $($rest)*
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; - $($raw:tt)*) => {
        $crate::__pgrx_c_args_OffsetNumberPrev!(@negative0 $mode [$($done)*]; - $($raw)*)
    };
    (@p0 $mode:ident [$($done:tt)*]; (@__pgrx_c_native [$argument:expr])) => {
        $crate::__pgrx_c_args_OffsetNumberPrev!(
            @p1 $mode [$($done)* (@original [$argument] (@native [$argument])),];
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; $head:ident $(::$tail:ident)* ! $group:tt) => {
        $crate::__pgrx_c_classify!(
            @argument [__pgrx_c_args_OffsetNumberPrev] [p1 $mode [$($done)*] []] [
                $head $(::$tail)* ! $group
            ]
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; ::$head:ident $(::$tail:ident)* ! $group:tt) => {
        $crate::__pgrx_c_classify!(
            @argument [__pgrx_c_args_OffsetNumberPrev] [p1 $mode [$($done)*] []] [
                ::$head $(::$tail)* ! $group
            ]
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; ($($inner:tt)*)) => {
        $crate::__pgrx_c_classify!(
            @argument [__pgrx_c_args_OffsetNumberPrev] [p1 $mode [$($done)*] []] [($($inner)*)]
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; $argument:literal) => {
        $crate::__pgrx_c_args_OffsetNumberPrev!(
            @p1 $mode [$($done)* (@original [$argument] (@literal [$argument])),];
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; $argument:expr) => {
        $crate::__pgrx_c_args_OffsetNumberPrev!(
            @p1 $mode [$($done)* (@original [$argument] (@native [$argument])),];
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; (@__pgrx_c_native [$argument:expr]), $($rest:tt)*) => {
        $crate::__pgrx_c_args_OffsetNumberPrev!(
            @p1 $mode [$($done)* (@original [$argument] (@native [$argument])),];
            $($rest)*
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; $head:ident $(::$tail:ident)* ! $group:tt, $($rest:tt)*) => {
        $crate::__pgrx_c_classify!(
            @argument [__pgrx_c_args_OffsetNumberPrev] [p1 $mode [$($done)*] [$($rest)*]] [
                $head $(::$tail)* ! $group
            ]
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; ::$head:ident $(::$tail:ident)* ! $group:tt, $($rest:tt)*) => {
        $crate::__pgrx_c_classify!(
            @argument [__pgrx_c_args_OffsetNumberPrev] [p1 $mode [$($done)*] [$($rest)*]] [
                ::$head $(::$tail)* ! $group
            ]
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; ($($inner:tt)*), $($rest:tt)*) => {
        $crate::__pgrx_c_classify!(
            @argument [__pgrx_c_args_OffsetNumberPrev] [p1 $mode [$($done)*] [$($rest)*]] [
                ($($inner)*)
            ]
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; $argument:literal, $($rest:tt)*) => {
        $crate::__pgrx_c_args_OffsetNumberPrev!(
            @p1 $mode [$($done)* (@original [$argument] (@literal [$argument])),];
            $($rest)*
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; $argument:expr, $($rest:tt)*) => {
        $crate::__pgrx_c_args_OffsetNumberPrev!(
            @p1 $mode [$($done)* (@original [$argument] (@native [$argument])),];
            $($rest)*
        )
    };
    (@p1 $mode:ident [$($done:tt)*];) => {
        $crate::OffsetNumberPrev!(@$mode; $($done)*)
    };
    ($($invalid:tt)*) => {
        compile_error!("arguments do not satisfy this C macro's invocation contract")
    };
}
/// C macro OffsetNumberPrev from off.h:54
///
/// ```text
/// #define OffsetNumberPrev( offsetNumber ) ( ( OffsetNumber ) ( - 1 + ( offsetNumber ) ) )
/// ```
///
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Checked signed arithmetic rejects overflow when the recorded C profile does not define wrapping. Checked signed arithmetic rejects overflow when the recorded C profile does not define wrapping; pointer arithmetic checks representable offsets and distances but still requires valid allocation bounds. Conversions involving floats reject nonfinite or out-of-range integer results; conversions into Rust enums reject values without a represented discriminant. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! OffsetNumberPrev {
    (@__pgrx_emit_check_safety; $offsetNumber:tt $(,)?) => {
        {
            if false {
                $crate::__pgrx_c_operand!(@check_safety; $offsetNumber);
            }
        }
    };
    (@__pgrx_c_check_safety; $($raw:tt)*) => {
        $crate::__pgrx_c_args_OffsetNumberPrev!(@collect __pgrx_emit_check_safety []; $($raw)*)
    };
    (@__pgrx_emit_public; $offsetNumber:tt $(,)?) => {
        $crate::__pgrx_c_macros::expression_result::finish(
            $crate::OffsetNumberPrev!(@__pgrx_emit_value; $offsetNumber)
        )
    };
    (@__pgrx_emit_value; $offsetNumber:tt $(,)?) => {
        (
            $crate::__pgrx_c_macros::expression::profile_value::<true, _>(
                $crate::__pgrx_c_macros::expression::cast_as::<
                    $crate::__pgrx_c_bindings::OffsetNumber,
                    $crate::__pgrx_c_macros::CUnsignedShort,
                    _
                >(
                    (
                        $crate::__pgrx_c_macros::expression::profile_value::<true, _>(
                            $crate::__pgrx_c_macros::expression::add::<
                                $crate::__pgrx_c_macros::Wrapping,
                                _,
                                _
                            >(
                                $crate::__pgrx_c_macros::expression::profile_value::<true, _>(
                                    $crate::__pgrx_c_macros::expression::neg::<
                                        $crate::__pgrx_c_macros::Wrapping,
                                        _
                                    >(
                                        $crate::__pgrx_c_macros::expression::profile_value::<
                                            true,
                                            _
                                        >(
                                            $crate::__pgrx_c_macros::CValue::<
                                                $crate::__pgrx_c_macros::CInt
                                            >::new(1i32)
                                        )
                                    )
                                ),
                                (
                                    $crate::__pgrx_c_macros::expression::profile_value::<true, _>(
                                        $crate::__pgrx_c_operand!(@value [true]; $offsetNumber)
                                    )
                                )
                            )
                        )
                    )
                )
            )
        )
    };
    (@__pgrx_c_value; $($raw:tt)*) => {
        $crate::__pgrx_c_args_OffsetNumberPrev!(@collect __pgrx_emit_value []; $($raw)*)
    };
    (@__pgrx_emit_place; $offsetNumber:tt $(,)?) => {
        compile_error!("C expression is not a place in this operation")
    };
    (@__pgrx_c_place; $($raw:tt)*) => {
        $crate::__pgrx_c_args_OffsetNumberPrev!(@collect __pgrx_emit_place []; $($raw)*)
    };
    (@__pgrx_emit_read_place; $offsetNumber:tt $(,)?) => {
        compile_error!("C expression is not a place in this operation")
    };
    (@__pgrx_c_read_place; $($raw:tt)*) => {
        $crate::__pgrx_c_args_OffsetNumberPrev!(@collect __pgrx_emit_read_place []; $($raw)*)
    };
    (@__pgrx_emit_size; $offsetNumber:tt $(,)?) => {
        $crate::__pgrx_c_macros::expression::size_of_value_type(
            if false {
                {
                    if false {
                        $crate::__pgrx_c_operand!(@check_safety; $offsetNumber);
                    }
                }
                Some(
                    unsafe {
                        $crate::__pgrx_c_macros::expression::profile_value::<true, _>(
                            $crate::__pgrx_c_macros::expression::cast_as::<
                                $crate::__pgrx_c_bindings::OffsetNumber,
                                $crate::__pgrx_c_macros::CUnsignedShort,
                                _
                            >(
                                (
                                    $crate::__pgrx_c_macros::expression::profile_value::<true, _>(
                                        $crate::__pgrx_c_macros::expression::add::<
                                            $crate::__pgrx_c_macros::Wrapping,
                                            _,
                                            _
                                        >(
                                            $crate::__pgrx_c_macros::expression::profile_value::<
                                                true,
                                                _
                                            >(
                                                $crate::__pgrx_c_macros::expression::neg::<
                                                    $crate::__pgrx_c_macros::Wrapping,
                                                    _
                                                >(
                                                    $crate::__pgrx_c_macros::expression::profile_value::<
                                                        true,
                                                        _
                                                    >(
                                                        $crate::__pgrx_c_macros::CValue::<
                                                            $crate::__pgrx_c_macros::CInt
                                                        >::new(1i32)
                                                    )
                                                )
                                            ),
                                            (
                                                $crate::__pgrx_c_macros::expression::profile_value::<
                                                    true,
                                                    _
                                                >(
                                                    $crate::__pgrx_c_operand!(
                                                        @value [true];
                                                        $offsetNumber
                                                    )
                                                )
                                            )
                                        )
                                    )
                                )
                            )
                        )
                    }
                )
            } else {
                None
            }
        )
    };
    (@__pgrx_c_size; $($raw:tt)*) => {
        $crate::__pgrx_c_args_OffsetNumberPrev!(@collect __pgrx_emit_size []; $($raw)*)
    };
    (@__pgrx_emit_discard; $offsetNumber:tt $(,)?) => {
        {
            let _ = $crate::__pgrx_c_macros::expression::profile_value::<true, _>(
                $crate::__pgrx_c_macros::expression::cast_as::<
                    $crate::__pgrx_c_bindings::OffsetNumber,
                    $crate::__pgrx_c_macros::CUnsignedShort,
                    _
                >(
                    (
                        $crate::__pgrx_c_macros::expression::profile_value::<true, _>(
                            $crate::__pgrx_c_macros::expression::add::<
                                $crate::__pgrx_c_macros::Wrapping,
                                _,
                                _
                            >(
                                $crate::__pgrx_c_macros::expression::profile_value::<true, _>(
                                    $crate::__pgrx_c_macros::expression::neg::<
                                        $crate::__pgrx_c_macros::Wrapping,
                                        _
                                    >(
                                        $crate::__pgrx_c_macros::expression::profile_value::<
                                            true,
                                            _
                                        >(
                                            $crate::__pgrx_c_macros::CValue::<
                                                $crate::__pgrx_c_macros::CInt
                                            >::new(1i32)
                                        )
                                    )
                                ),
                                (
                                    $crate::__pgrx_c_macros::expression::profile_value::<true, _>(
                                        $crate::__pgrx_c_operand!(@value [true]; $offsetNumber)
                                    )
                                )
                            )
                        )
                    )
                )
            );
        }
    };
    (@__pgrx_c_discard; $($raw:tt)*) => {
        $crate::__pgrx_c_args_OffsetNumberPrev!(@collect __pgrx_emit_discard []; $($raw)*)
    };
    ($($raw:tt)*) => {
        $crate::__pgrx_c_args_OffsetNumberPrev!(@collect __pgrx_emit_public []; $($raw)*)
    };
}

pub use OffsetNumberIsValid;
pub use OffsetNumberNext;
pub use OffsetNumberPrev;
