//LICENSE Portions Copyright 2023-2023 PgCentral Foundation, Inc. <contact@pgcentral.org>
//LICENSE
//LICENSE Use of this source code is governed by the MIT license that can be found in the LICENSE file.

use pgrx_pg_config::{PgConfig, PgConfigSelector, Pgrx};
use pgrx_sql_entity_graph::section::schema_section_sentinel_entry;
use std::fs;
use std::path::Path;
use std::process::Command;
use tempfile::TempDir;

fn pg_config() -> Option<PgConfig> {
    let config = Pgrx::from_config().ok().and_then(|pgrx| {
        pgrx.iter(PgConfigSelector::All)
            .filter_map(Result::ok)
            .find(|config| config.path().is_some_and(|path| path.is_file()))
    });
    if config.is_none() {
        eprintln!("skipping target-directory regression: no configured Postgres installation");
    }
    config
}

fn fixture() -> TempDir {
    let dir = tempfile::tempdir().unwrap();
    let extension = dir.path().join("extension");
    fs::create_dir_all(extension.join("src")).unwrap();
    fs::create_dir(extension.join("sql")).unwrap();
    fs::write(
        extension.join("Cargo.toml"),
        r#"
[package]
name = "target_directory_test"
version = "0.1.0"
edition = "2024"

[workspace]

[lib]
crate-type = ["cdylib", "rlib"]

[features]
pg13 = []
pg14 = []
pg15 = []
pg16 = []
pg17 = []
pg18 = []
pg19 = []
pg_test = []

[profile.custom]
inherits = "dev"
"#,
    )
    .unwrap();
    fs::write(
        extension.join("target_directory_test.control"),
        "comment = 'target directory regression'\ndefault_version = '@CARGO_VERSION@'\nmodule_pathname = '$libdir/target_directory_test'\nrelocatable = false\nsuperuser = false\n",
    )
    .unwrap();
    fs::write(extension.join("sql/target_directory_test--0.0.0--0.1.0.sql"), "SELECT 1;\n")
        .unwrap();
    let sentinel = schema_section_sentinel_entry();
    fs::write(
        extension.join("src/lib.rs"),
        format!(
            r#"
#[used]
#[unsafe(no_mangle)]
#[cfg_attr(target_os = "macos", unsafe(link_section = "__DATA,__pgrxsc"))]
#[cfg_attr(not(target_os = "macos"), unsafe(link_section = ".pgrxsc"))]
pub static PGRX_SCHEMA: [u8; {len}] = {sentinel:?};

#[test]
fn target_directory_reaches_test_process() {{
    assert_eq!(
        std::env::var_os("CARGO_TARGET_DIR"),
        std::env::var_os("EXPECTED_TARGET_DIR"),
    );
}}
"#,
            len = sentinel.len(),
        ),
    )
    .unwrap();
    let target_dir = dir.path().join("configured-target");
    let mut config = toml::Table::new();
    config.insert(
        "build".into(),
        toml::Value::Table(toml::Table::from_iter([(
            "target-dir".into(),
            toml::Value::String(target_dir.to_str().unwrap().into()),
        )])),
    );
    fs::write(dir.path().join("extension-cargo.toml"), config.to_string()).unwrap();
    dir
}

fn command(dir: &Path, subcommand: &str) -> Command {
    let mut command = Command::new(env!("CARGO_BIN_EXE_cargo-pgrx"));
    // The working directory has no Cargo.toml; only --manifest-path identifies the crate.
    command
        .current_dir(dir)
        .env_remove("CARGO_TARGET_DIR")
        .env_remove("CARGO_BUILD_TARGET_DIR")
        .args(["pgrx", subcommand, "--manifest-path", "extension/Cargo.toml"])
        .arg("--cargo=--config=extension-cargo.toml");
    command
}

fn run(command: &mut Command) -> String {
    let output = command.output().expect("cargo-pgrx should launch");
    assert!(
        output.status.success(),
        "{command:?} failed\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr),
    );
    String::from_utf8(output.stdout).unwrap()
}

#[test]
fn schema_uses_configured_target_directory() {
    let Some(pg_config) = pg_config() else { return };
    let dir = fixture();
    let pg_feature = pg_config.label().unwrap();

    let schema = run(command(dir.path(), "schema").args([&pg_feature, "--profile", "custom"]));
    assert!(schema.contains("This file is auto generated by pgrx."), "{schema}");
    run(command(dir.path(), "schema").args([&pg_feature, "--profile", "custom", "--skip-build"]));
    run(Command::new(env!("CARGO_BIN_EXE_cargo-pgrx"))
        .current_dir(dir.path().join("extension"))
        .env_remove("CARGO_TARGET_DIR")
        .env_remove("CARGO_BUILD_TARGET_DIR")
        .args(["pgrx", "schema", &pg_feature, "--profile", "custom", "--skip-build"])
        .arg("--cargo=--config=../extension-cargo.toml"));
    assert!(!dir.path().join("extension/target").exists());
}

#[test]
fn package_uses_configured_target_directory() {
    let Some(pg_config) = pg_config() else { return };
    let dir = fixture();
    let pg_feature = pg_config.label().unwrap();
    let target_dir = dir.path().join("configured-target");

    run(command(dir.path(), "package")
        .arg("--pg-config")
        .arg(pg_config.path().unwrap())
        .args(["--profile", "custom"]));
    let package_dir = target_dir.join("custom").join(format!("target_directory_test-{pg_feature}"));
    let extension_dir = if cfg!(windows) {
        package_dir.join("share/extension")
    } else {
        package_dir.join(pg_config.extension_dir().unwrap().strip_prefix("/").unwrap())
    };
    let library_dir = if cfg!(windows) {
        package_dir.join("lib")
    } else {
        package_dir.join(pg_config.pkglibdir().unwrap().strip_prefix("/").unwrap())
    };
    let suffix = if cfg!(target_os = "macos") && pg_config.major_version().unwrap() < 16 {
        ".so"
    } else {
        std::env::consts::DLL_SUFFIX
    };
    assert!(library_dir.join(format!("target_directory_test{suffix}")).is_file());
    assert!(extension_dir.join("target_directory_test.control").is_file());
    assert!(extension_dir.join("target_directory_test--0.1.0.sql").is_file());
    assert!(extension_dir.join("target_directory_test--0.0.0--0.1.0.sql").is_file());
    assert!(!dir.path().join("extension/target").exists());
}

#[test]
fn test_uses_configured_target_directory() {
    let Some(pg_config) = pg_config() else { return };
    let dir = fixture();
    let target_dir = dir.path().join("configured-target");
    for inherited_target in [None, Some(dir.path().join("other-target"))] {
        let mut command = command(dir.path(), "test");
        let expected_target = inherited_target.as_ref().unwrap_or(&target_dir);
        command.arg(pg_config.label().unwrap()).env("EXPECTED_TARGET_DIR", expected_target);
        if let Some(inherited_target) = &inherited_target {
            command.env("CARGO_TARGET_DIR", inherited_target);
        }
        let output = run(&mut command);
        assert!(output.contains("1 passed"), "{output}");
        assert!(expected_target.join("debug").is_dir());
    }
    assert!(!dir.path().join("extension/target").exists());
}
