FROM fedora:36

ARG PG_MAJOR_VER
ENV PG_MAJOR_VER=${PG_MAJOR_VER}

# RUN echo ">>>>>>>>>>>>>>>>>>>>>>>> $PG_MAJOR_VER"
RUN adduser -G wheel rust
WORKDIR /checkout
RUN chown -R rust:rust /checkout
COPY --chown=rust:rust . /checkout

# RUN chmod a+rw /checkout && \
#   chown -R rust:rust /checkout


RUN dnf install -y https://download.postgresql.org/pub/repos/yum/reporpms/F-36-x86_64/pgdg-fedora-repo-latest.noarch.rpm
RUN dnf install -y \
  clang-tools-extra \
  cmake \
  make \
  gcc \
  openssl \
  openssl-devel \
  postgresql$PG_MAJOR_VER-server \
  postgresql$PG_MAJOR_VER-devel \
  redhat-rpm-config \
  util-linux

RUN chmod a+rwx `/usr/pgsql-$PG_MAJOR_VER/bin/pg_config --pkglibdir` \
  `/usr/pgsql-$PG_MAJOR_VER/bin/pg_config --sharedir`/extension \
  /var/run/postgresql/

USER rust
ENV PATH="/home/rust/.cargo/bin:${PATH}"
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
# RUN whoami && cargo --version

# RUN ls -lath /checkout

# CMD ["ls", "-lath"]
# CMD ["pwd"]


# RUN su rust -l -- -c curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
# RUN su rust -l -- -c cargo --version
# ENV PATH="/home/rust/.cargo/bin:${PATH}"

RUN cargo install cargo-pgx
RUN cargo pgx init --pg$PG_MAJOR_VER=/usr/pgsql-$PG_MAJOR_VER/bin/pg_config

# WORKDIR /app
# COPY . /app

ENV USER=rust
CMD ["cargo", "test", "--no-default-features", "--features", "pg${PG_MAJOR_VER}"]
