FROM amazonlinux:2
ARG PG_MAJOR_VER
ENV PG_MAJOR_VER=${PG_MAJOR_VER}

RUN amazon-linux-extras install epel

RUN yum -y remove python3
RUN amazon-linux-extras enable python3
RUN yum clean metadata
RUN yum install -y python3-3.6.* --disablerepo=amzn2-core
RUN yum install -y \
  bison \
  clang \
  flex \
  llvm13 \
  llvm13-* \
  openssl \
  openssl-devel \
  readline \
  readline-devel \
  which

RUN yum -y install http://mirror.centos.org/centos/7/extras/x86_64/Packages/centos-release-scl-rh-2-3.el7.centos.noarch.rpm
RUN yum -y install http://mirror.centos.org/centos/7/extras/x86_64/Packages/centos-release-scl-2-3.el7.centos.noarch.rpm
# RUN yum -y install http://mirror.centos.org/centos/7/sclo/x86_64/rh/Packages/l/llvm-toolset-7-clang-4.0.1-1.el7.x86_64.rpm
RUN yum -y install http://mirror.centos.org/centos/7/sclo/x86_64/rh/Packages/l/llvm-toolset-7-clang-5.0.1-4.el7.x86_64.rpm

# NOTE: Assumption here is x86_64, which might suffice for CI builds but care
# should be taken if this is used as a template elsewhere.
RUN echo -e "[pgdg$PG_MAJOR_VER]\n\
  name=PostgreSQL $PG_MAJOR_VER for RHEL/CentOS7 - x86_64\n\
  gpgkey=https://download.postgresql.org/pub/repos/yum/RPM-GPG-KEY-PGDG-$PG_MAJOR_VER\n\
  baseurl=https://download.postgresql.org/pub/repos/yum/$PG_MAJOR_VER/redhat/rhel-7-x86_64/\n\
  enabled=1\n\
  gpgcheck=0\n\
  " | sed -e 's/^[ \t]*//' >> /etc/yum.repos.d/pgdg.repo

RUN yum -y install postgresql$PG_MAJOR_VER postgresql$PG_MAJOR_VER-contrib postgresql$PG_MAJOR_VER-server postgresql$PG_MAJOR_VER-devel
# RUN yum install -y

ENV PATH="/usr/pgsql-$PG_MAJOR_VER/bin:$PATH"

RUN chmod a+rwx `$(which pg_config) --pkglibdir` \
  `$(which pg_config) --sharedir`/extension \
  /var/run/postgresql/

RUN adduser -G wheel rust
WORKDIR /checkout
RUN chown -R rust:rust /checkout
COPY --chown=rust:rust . /checkout

USER rust
ENV USER=rust

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash -s -- -y
ENV PATH="/home/rust/.cargo/bin:${PATH}"
RUN cargo install --path cargo-pgx/
RUN cargo pgx init --pg$PG_MAJOR_VER=$(which pg_config)
CMD ["cargo", "test", "--no-default-features", "--features", "pg${PG_MAJOR_VER}"]

# RUN amazon-linux-extras enable postgresql$PG_MAJOR_VER
# RUN yum clean metadata

# RUN yum install -y \
#   bison \
#   clang \
#   flex \
#   libpq \
#   libpq-devel \
#   openssl \
#   openssl-devel \
#   postgresql \
#   postgresql-devel \
#   postgresql-server \
#   postgresql-server-devel \
#   readline \
#   readline-devel \
#   vim \
#   which

# RUN chmod a+rwx `$(which pg_config) --pkglibdir` \
#   `$(which pg_config) --sharedir`/extension \
#   /var/run/postgresql/

# RUN adduser -G wheel rust
# WORKDIR /checkout
# RUN chown -R rust:rust /checkout
# COPY --chown=rust:rust . /checkout

# USER rust
# ENV USER=rust

# RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash -s -- -y
# ENV PATH="/home/rust/.cargo/bin:${PATH}"
# RUN cargo install --path cargo-pgx/
# RUN cargo pgx init --pg$PG_MAJOR_VER=$(which pg_config)
# CMD ["cargo", "test", "--no-default-features", "--features", "pg${PG_MAJOR_VER}"]
