[target.'cfg(target_os="macos")']
# Postgres symbols won't be available until runtime
rustflags = ["-Clink-arg=-Wl,-undefined,dynamic_lookup"]
[target.x86_64-unknown-linux-gnu]
rustflags = ["-Clink-arg=-Wl,-V"]
