// Automatically generated by pgrx-c-macros for documentation. Do not hand-edit.
// C macros from hashjoin.h.

/// C macro EstimateParallelHashJoinBatch from hashjoin.h:181 (PostgreSQL 15), hashjoin.h:193 (PostgreSQL 16–18), hashjoin.h:204 (PostgreSQL 19)
///
/// ```text
/// #define EstimateParallelHashJoinBatch( hashtable ) ( MAXALIGN ( sizeof ( ParallelHashJoinBatch ) ) + MAXALIGN ( sts_estimate ( ( hashtable ) -> parallel_state -> nparticipants ) ) * 2 )
/// ```
///
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Checked signed arithmetic rejects overflow when the recorded C profile does not define wrapping; pointer arithmetic checks representable offsets and distances but still requires valid allocation bounds. Conversions involving floats reject nonfinite or out-of-range integer results; conversions into Rust enums reject values without a represented discriminant. Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! EstimateParallelHashJoinBatch {
    ($hashtable:expr $(,)?) => {
        ::core::unimplemented!("pgrx documentation snapshot; C macros are generated for each build")
    };
}
/// C macro HASH_CHUNK_DATA from hashjoin.h:141 (PostgreSQL 15), hashjoin.h:152 (PostgreSQL 16–18), hashjoin.h:163 (PostgreSQL 19)
///
/// ```text
/// #define HASH_CHUNK_DATA( hc ) ( ( ( char * ) ( hc ) ) + HASH_CHUNK_HEADER_SIZE )
/// ```
///
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Checked signed arithmetic rejects overflow when the recorded C profile does not define wrapping; pointer arithmetic checks representable offsets and distances but still requires valid allocation bounds. Conversions involving floats reject nonfinite or out-of-range integer results; conversions into Rust enums reject values without a represented discriminant. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! HASH_CHUNK_DATA {
    ($hc:expr $(,)?) => {
        ::core::unimplemented!("pgrx documentation snapshot; C macros are generated for each build")
    };
}
/// C macro HJTUPLE_MINTUPLE from hashjoin.h:80 (PostgreSQL 15), hashjoin.h:91 (PostgreSQL 16–18), hashjoin.h:102 (PostgreSQL 19)
///
/// ```text
/// #define HJTUPLE_MINTUPLE( hjtup ) ( ( MinimalTuple ) ( ( char * ) ( hjtup ) + HJTUPLE_OVERHEAD ) )
/// ```
///
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Checked signed arithmetic rejects overflow when the recorded C profile does not define wrapping; pointer arithmetic checks representable offsets and distances but still requires valid allocation bounds. Conversions involving floats reject nonfinite or out-of-range integer results; conversions into Rust enums reject values without a represented discriminant. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! HJTUPLE_MINTUPLE {
    ($hjtup:expr $(,)?) => {
        ::core::unimplemented!("pgrx documentation snapshot; C macros are generated for each build")
    };
}
/// C macro NthParallelHashJoinBatch from hashjoin.h:186 (PostgreSQL 15), hashjoin.h:198 (PostgreSQL 16–18), hashjoin.h:209 (PostgreSQL 19)
///
/// ```text
/// #define NthParallelHashJoinBatch( base , n ) ( ( ParallelHashJoinBatch * ) ( ( char * ) ( base ) + EstimateParallelHashJoinBatch ( hashtable ) * ( n ) ) )
/// ```
///
///
/// Rust callers supply 3 arguments: the 2 original C parameters, followed by explicit caller-scope operands in this order: `hashtable`. Each operand must preserve its C type and place requirements.
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Checked signed arithmetic rejects overflow when the recorded C profile does not define wrapping; pointer arithmetic checks representable offsets and distances but still requires valid allocation bounds. Conversions involving floats reject nonfinite or out-of-range integer results; conversions into Rust enums reject values without a represented discriminant. Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! NthParallelHashJoinBatch {
    ($base:expr, $n:expr, $hashtable:expr $(,)?) => {
        ::core::unimplemented!("pgrx documentation snapshot; C macros are generated for each build")
    };
}
/// C macro PHJ_GROW_BATCHES_PHASE from hashjoin.h:277 (PostgreSQL 15), hashjoin.h:290 (PostgreSQL 16–18), hashjoin.h:301 (PostgreSQL 19)
///
/// ```text
/// #define PHJ_GROW_BATCHES_PHASE( n ) ( ( n ) % 5 )
/// ```
///
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Integer division/remainder rejects zero divisors and signed MIN / -1 overflow. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! PHJ_GROW_BATCHES_PHASE {
    ($n:expr $(,)?) => {
        ::core::unimplemented!("pgrx documentation snapshot; C macros are generated for each build")
    };
}
/// C macro PHJ_GROW_BUCKETS_PHASE from hashjoin.h:283 (PostgreSQL 15), hashjoin.h:296 (PostgreSQL 16–18), hashjoin.h:307 (PostgreSQL 19)
///
/// ```text
/// #define PHJ_GROW_BUCKETS_PHASE( n ) ( ( n ) % 3 )
/// ```
///
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Integer division/remainder rejects zero divisors and signed MIN / -1 overflow. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! PHJ_GROW_BUCKETS_PHASE {
    ($n:expr $(,)?) => {
        ::core::unimplemented!("pgrx documentation snapshot; C macros are generated for each build")
    };
}
/// C macro ParallelHashJoinBatchInner from hashjoin.h:170 (PostgreSQL 15), hashjoin.h:182 (PostgreSQL 16–18), hashjoin.h:193 (PostgreSQL 19)
///
/// ```text
/// #define ParallelHashJoinBatchInner( batch ) ( ( SharedTuplestore * ) ( ( char * ) ( batch ) + MAXALIGN ( sizeof ( ParallelHashJoinBatch ) ) ) )
/// ```
///
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Checked signed arithmetic rejects overflow when the recorded C profile does not define wrapping; pointer arithmetic checks representable offsets and distances but still requires valid allocation bounds. Conversions involving floats reject nonfinite or out-of-range integer results; conversions into Rust enums reject values without a represented discriminant. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! ParallelHashJoinBatchInner {
    ($batch:expr $(,)?) => {
        ::core::unimplemented!("pgrx documentation snapshot; C macros are generated for each build")
    };
}
/// C macro ParallelHashJoinBatchOuter from hashjoin.h:175 (PostgreSQL 15), hashjoin.h:187 (PostgreSQL 16–18), hashjoin.h:198 (PostgreSQL 19)
///
/// ```text
/// #define ParallelHashJoinBatchOuter( batch , nparticipants ) ( ( SharedTuplestore * ) ( ( char * ) ParallelHashJoinBatchInner ( batch ) + MAXALIGN ( sts_estimate ( nparticipants ) ) ) )
/// ```
///
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Checked signed arithmetic rejects overflow when the recorded C profile does not define wrapping; pointer arithmetic checks representable offsets and distances but still requires valid allocation bounds. Conversions involving floats reject nonfinite or out-of-range integer results; conversions into Rust enums reject values without a represented discriminant. Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! ParallelHashJoinBatchOuter {
    ($batch:expr, $nparticipants:expr $(,)?) => {
        ::core::unimplemented!("pgrx documentation snapshot; C macros are generated for each build")
    };
}
pub use EstimateParallelHashJoinBatch;
pub use HASH_CHUNK_DATA;
pub use HJTUPLE_MINTUPLE;
pub use NthParallelHashJoinBatch;
pub use PHJ_GROW_BATCHES_PHASE;
pub use PHJ_GROW_BUCKETS_PHASE;
pub use ParallelHashJoinBatchInner;
pub use ParallelHashJoinBatchOuter;
