// Automatically generated by pgrx-c-macros for documentation. Do not hand-edit.
// C macros from spi.h.

#[cfg(any(feature = "pg15", feature = "pg16"))]
/// C macro SPI_pop from spi.h:105 (PostgreSQL 15–16)
///
/// ```text
/// #define SPI_pop( ) ( ( void ) 0 )
/// ```
///
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Conversions involving floats reject nonfinite or out-of-range integer results; conversions into Rust enums reject values without a represented discriminant. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! SPI_pop {
    () => {
        ::core::unimplemented!("pgrx documentation snapshot; C macros are generated for each build")
    };
}
#[cfg(any(feature = "pg15", feature = "pg16"))]
/// C macro SPI_pop_conditional from spi.h:107 (PostgreSQL 15–16)
///
/// ```text
/// #define SPI_pop_conditional( pushed ) ( ( void ) 0 )
/// ```
///
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Conversions involving floats reject nonfinite or out-of-range integer results; conversions into Rust enums reject values without a represented discriminant. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! SPI_pop_conditional {
    ($pushed:expr $(,)?) => {
        ::core::unimplemented!("pgrx documentation snapshot; C macros are generated for each build")
    };
}
#[cfg(any(feature = "pg15", feature = "pg16"))]
/// C macro SPI_push from spi.h:104 (PostgreSQL 15–16)
///
/// ```text
/// #define SPI_push( ) ( ( void ) 0 )
/// ```
///
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Conversions involving floats reject nonfinite or out-of-range integer results; conversions into Rust enums reject values without a represented discriminant. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! SPI_push {
    () => {
        ::core::unimplemented!("pgrx documentation snapshot; C macros are generated for each build")
    };
}
#[cfg(any(feature = "pg15", feature = "pg16"))]
/// C macro SPI_push_conditional from spi.h:106 (PostgreSQL 15–16)
///
/// ```text
/// #define SPI_push_conditional( ) false
/// ```
///
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
#[macro_export]
macro_rules! SPI_push_conditional {
    () => {
        ::core::unimplemented!("pgrx documentation snapshot; C macros are generated for each build")
    };
}
#[cfg(any(feature = "pg15", feature = "pg16"))]
/// C macro SPI_restore_connection from spi.h:108 (PostgreSQL 15–16)
///
/// ```text
/// #define SPI_restore_connection( ) ( ( void ) 0 )
/// ```
///
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Conversions involving floats reject nonfinite or out-of-range integer results; conversions into Rust enums reject values without a represented discriminant. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! SPI_restore_connection {
    () => {
        ::core::unimplemented!("pgrx documentation snapshot; C macros are generated for each build")
    };
}
#[cfg(any(feature = "pg15", feature = "pg16"))]
pub use SPI_pop;
#[cfg(any(feature = "pg15", feature = "pg16"))]
pub use SPI_pop_conditional;
#[cfg(any(feature = "pg15", feature = "pg16"))]
pub use SPI_push;
#[cfg(any(feature = "pg15", feature = "pg16"))]
pub use SPI_push_conditional;
#[cfg(any(feature = "pg15", feature = "pg16"))]
pub use SPI_restore_connection;
