// Automatically generated by pgrx-c-macros for documentation. Do not hand-edit.
// C macros from pgstat.h.

#[cfg(feature = "pg15")]
/// C macro pgstat_count_buffer_hit from pgstat.h:561 (PostgreSQL 15)
///
/// ```text
/// #define pgstat_count_buffer_hit( rel ) do { if ( pgstat_should_count_relation ( rel ) ) ( rel ) -> pgstat_info -> t_counts . t_blocks_hit ++ ; } while ( 0 )
/// ```
///
///
#[doc = crate::__pgrx_c_doc_statements!()]
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
///
/// # Panics
///
/// Checked signed arithmetic rejects overflow when the recorded C profile does not define wrapping. Conversions involving floats reject nonfinite or out-of-range integer results; conversions into Rust enums reject values without a represented discriminant. Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! pgstat_count_buffer_hit {
    ($rel:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(any(feature = "pg16", feature = "pg17", feature = "pg18", feature = "pg19"))]
/// C macro pgstat_count_buffer_hit from pgstat.h:638 (PostgreSQL 16), pgstat.h:640 (PostgreSQL 17), pgstat.h:710 (PostgreSQL 18), pgstat.h:747 (PostgreSQL 19)
///
/// ```text
/// #define pgstat_count_buffer_hit( rel ) do { if ( pgstat_should_count_relation ( rel ) ) ( rel ) -> pgstat_info -> counts . blocks_hit ++ ; } while ( 0 )
/// ```
///
///
#[doc = crate::__pgrx_c_doc_statements!()]
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
///
/// # Panics
///
/// Checked signed arithmetic rejects overflow when the recorded C profile does not define wrapping. Conversions involving floats reject nonfinite or out-of-range integer results; conversions into Rust enums reject values without a represented discriminant. Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! pgstat_count_buffer_hit {
    ($rel:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(feature = "pg15")]
/// C macro pgstat_count_buffer_read from pgstat.h:556 (PostgreSQL 15)
///
/// ```text
/// #define pgstat_count_buffer_read( rel ) do { if ( pgstat_should_count_relation ( rel ) ) ( rel ) -> pgstat_info -> t_counts . t_blocks_fetched ++ ; } while ( 0 )
/// ```
///
///
#[doc = crate::__pgrx_c_doc_statements!()]
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
///
/// # Panics
///
/// Checked signed arithmetic rejects overflow when the recorded C profile does not define wrapping. Conversions involving floats reject nonfinite or out-of-range integer results; conversions into Rust enums reject values without a represented discriminant. Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! pgstat_count_buffer_read {
    ($rel:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(any(feature = "pg16", feature = "pg17", feature = "pg18", feature = "pg19"))]
/// C macro pgstat_count_buffer_read from pgstat.h:633 (PostgreSQL 16), pgstat.h:635 (PostgreSQL 17), pgstat.h:705 (PostgreSQL 18), pgstat.h:742 (PostgreSQL 19)
///
/// ```text
/// #define pgstat_count_buffer_read( rel ) do { if ( pgstat_should_count_relation ( rel ) ) ( rel ) -> pgstat_info -> counts . blocks_fetched ++ ; } while ( 0 )
/// ```
///
///
#[doc = crate::__pgrx_c_doc_statements!()]
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
///
/// # Panics
///
/// Checked signed arithmetic rejects overflow when the recorded C profile does not define wrapping. Conversions involving floats reject nonfinite or out-of-range integer results; conversions into Rust enums reject values without a represented discriminant. Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! pgstat_count_buffer_read {
    ($rel:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
/// C macro pgstat_count_buffer_read_time from pgstat.h:474 (PostgreSQL 15), pgstat.h:550 (PostgreSQL 16), pgstat.h:552 (PostgreSQL 17), pgstat.h:621 (PostgreSQL 18), pgstat.h:658 (PostgreSQL 19)
///
/// ```text
/// #define pgstat_count_buffer_read_time( n ) ( pgStatBlockReadTime += ( n ) )
/// ```
///
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
///
/// # Panics
///
/// Checked signed arithmetic rejects overflow when the recorded C profile does not define wrapping; pointer arithmetic checks representable offsets and distances but still requires valid allocation bounds. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! pgstat_count_buffer_read_time {
    ($n:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
/// C macro pgstat_count_buffer_write_time from pgstat.h:476 (PostgreSQL 15), pgstat.h:552 (PostgreSQL 16), pgstat.h:554 (PostgreSQL 17), pgstat.h:623 (PostgreSQL 18), pgstat.h:660 (PostgreSQL 19)
///
/// ```text
/// #define pgstat_count_buffer_write_time( n ) ( pgStatBlockWriteTime += ( n ) )
/// ```
///
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
///
/// # Panics
///
/// Checked signed arithmetic rejects overflow when the recorded C profile does not define wrapping; pointer arithmetic checks representable offsets and distances but still requires valid allocation bounds. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! pgstat_count_buffer_write_time {
    ($n:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
/// C macro pgstat_count_conn_active_time from pgstat.h:478 (PostgreSQL 15), pgstat.h:554 (PostgreSQL 16), pgstat.h:556 (PostgreSQL 17), pgstat.h:625 (PostgreSQL 18), pgstat.h:662 (PostgreSQL 19)
///
/// ```text
/// #define pgstat_count_conn_active_time( n ) ( pgStatActiveTime += ( n ) )
/// ```
///
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
///
/// # Panics
///
/// Checked signed arithmetic rejects overflow when the recorded C profile does not define wrapping; pointer arithmetic checks representable offsets and distances but still requires valid allocation bounds. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! pgstat_count_conn_active_time {
    ($n:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
/// C macro pgstat_count_conn_txn_idle_time from pgstat.h:480 (PostgreSQL 15), pgstat.h:556 (PostgreSQL 16), pgstat.h:558 (PostgreSQL 17), pgstat.h:627 (PostgreSQL 18), pgstat.h:664 (PostgreSQL 19)
///
/// ```text
/// #define pgstat_count_conn_txn_idle_time( n ) ( pgStatTransactionIdleTime += ( n ) )
/// ```
///
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
///
/// # Panics
///
/// Checked signed arithmetic rejects overflow when the recorded C profile does not define wrapping; pointer arithmetic checks representable offsets and distances but still requires valid allocation bounds. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! pgstat_count_conn_txn_idle_time {
    ($n:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(feature = "pg15")]
/// C macro pgstat_count_heap_fetch from pgstat.h:541 (PostgreSQL 15)
///
/// ```text
/// #define pgstat_count_heap_fetch( rel ) do { if ( pgstat_should_count_relation ( rel ) ) ( rel ) -> pgstat_info -> t_counts . t_tuples_fetched ++ ; } while ( 0 )
/// ```
///
///
#[doc = crate::__pgrx_c_doc_statements!()]
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
///
/// # Panics
///
/// Checked signed arithmetic rejects overflow when the recorded C profile does not define wrapping. Conversions involving floats reject nonfinite or out-of-range integer results; conversions into Rust enums reject values without a represented discriminant. Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! pgstat_count_heap_fetch {
    ($rel:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(any(feature = "pg16", feature = "pg17", feature = "pg18", feature = "pg19"))]
/// C macro pgstat_count_heap_fetch from pgstat.h:618 (PostgreSQL 16), pgstat.h:620 (PostgreSQL 17), pgstat.h:690 (PostgreSQL 18), pgstat.h:727 (PostgreSQL 19)
///
/// ```text
/// #define pgstat_count_heap_fetch( rel ) do { if ( pgstat_should_count_relation ( rel ) ) ( rel ) -> pgstat_info -> counts . tuples_fetched ++ ; } while ( 0 )
/// ```
///
///
#[doc = crate::__pgrx_c_doc_statements!()]
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
///
/// # Panics
///
/// Checked signed arithmetic rejects overflow when the recorded C profile does not define wrapping. Conversions involving floats reject nonfinite or out-of-range integer results; conversions into Rust enums reject values without a represented discriminant. Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! pgstat_count_heap_fetch {
    ($rel:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(feature = "pg15")]
/// C macro pgstat_count_heap_getnext from pgstat.h:536 (PostgreSQL 15)
///
/// ```text
/// #define pgstat_count_heap_getnext( rel ) do { if ( pgstat_should_count_relation ( rel ) ) ( rel ) -> pgstat_info -> t_counts . t_tuples_returned ++ ; } while ( 0 )
/// ```
///
///
#[doc = crate::__pgrx_c_doc_statements!()]
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
///
/// # Panics
///
/// Checked signed arithmetic rejects overflow when the recorded C profile does not define wrapping. Conversions involving floats reject nonfinite or out-of-range integer results; conversions into Rust enums reject values without a represented discriminant. Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! pgstat_count_heap_getnext {
    ($rel:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(any(feature = "pg16", feature = "pg17", feature = "pg18", feature = "pg19"))]
/// C macro pgstat_count_heap_getnext from pgstat.h:613 (PostgreSQL 16), pgstat.h:615 (PostgreSQL 17), pgstat.h:685 (PostgreSQL 18), pgstat.h:722 (PostgreSQL 19)
///
/// ```text
/// #define pgstat_count_heap_getnext( rel ) do { if ( pgstat_should_count_relation ( rel ) ) ( rel ) -> pgstat_info -> counts . tuples_returned ++ ; } while ( 0 )
/// ```
///
///
#[doc = crate::__pgrx_c_doc_statements!()]
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
///
/// # Panics
///
/// Checked signed arithmetic rejects overflow when the recorded C profile does not define wrapping. Conversions involving floats reject nonfinite or out-of-range integer results; conversions into Rust enums reject values without a represented discriminant. Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! pgstat_count_heap_getnext {
    ($rel:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(feature = "pg15")]
/// C macro pgstat_count_heap_scan from pgstat.h:531 (PostgreSQL 15)
///
/// ```text
/// #define pgstat_count_heap_scan( rel ) do { if ( pgstat_should_count_relation ( rel ) ) ( rel ) -> pgstat_info -> t_counts . t_numscans ++ ; } while ( 0 )
/// ```
///
///
#[doc = crate::__pgrx_c_doc_statements!()]
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
///
/// # Panics
///
/// Checked signed arithmetic rejects overflow when the recorded C profile does not define wrapping. Conversions involving floats reject nonfinite or out-of-range integer results; conversions into Rust enums reject values without a represented discriminant. Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! pgstat_count_heap_scan {
    ($rel:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(any(feature = "pg16", feature = "pg17", feature = "pg18", feature = "pg19"))]
/// C macro pgstat_count_heap_scan from pgstat.h:608 (PostgreSQL 16), pgstat.h:610 (PostgreSQL 17), pgstat.h:680 (PostgreSQL 18), pgstat.h:717 (PostgreSQL 19)
///
/// ```text
/// #define pgstat_count_heap_scan( rel ) do { if ( pgstat_should_count_relation ( rel ) ) ( rel ) -> pgstat_info -> counts . numscans ++ ; } while ( 0 )
/// ```
///
///
#[doc = crate::__pgrx_c_doc_statements!()]
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
///
/// # Panics
///
/// Checked signed arithmetic rejects overflow when the recorded C profile does not define wrapping. Conversions involving floats reject nonfinite or out-of-range integer results; conversions into Rust enums reject values without a represented discriminant. Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! pgstat_count_heap_scan {
    ($rel:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(feature = "pg15")]
/// C macro pgstat_count_index_scan from pgstat.h:546 (PostgreSQL 15)
///
/// ```text
/// #define pgstat_count_index_scan( rel ) do { if ( pgstat_should_count_relation ( rel ) ) ( rel ) -> pgstat_info -> t_counts . t_numscans ++ ; } while ( 0 )
/// ```
///
///
#[doc = crate::__pgrx_c_doc_statements!()]
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
///
/// # Panics
///
/// Checked signed arithmetic rejects overflow when the recorded C profile does not define wrapping. Conversions involving floats reject nonfinite or out-of-range integer results; conversions into Rust enums reject values without a represented discriminant. Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! pgstat_count_index_scan {
    ($rel:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(any(feature = "pg16", feature = "pg17", feature = "pg18", feature = "pg19"))]
/// C macro pgstat_count_index_scan from pgstat.h:623 (PostgreSQL 16), pgstat.h:625 (PostgreSQL 17), pgstat.h:695 (PostgreSQL 18), pgstat.h:732 (PostgreSQL 19)
///
/// ```text
/// #define pgstat_count_index_scan( rel ) do { if ( pgstat_should_count_relation ( rel ) ) ( rel ) -> pgstat_info -> counts . numscans ++ ; } while ( 0 )
/// ```
///
///
#[doc = crate::__pgrx_c_doc_statements!()]
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
///
/// # Panics
///
/// Checked signed arithmetic rejects overflow when the recorded C profile does not define wrapping. Conversions involving floats reject nonfinite or out-of-range integer results; conversions into Rust enums reject values without a represented discriminant. Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! pgstat_count_index_scan {
    ($rel:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(feature = "pg15")]
/// C macro pgstat_count_index_tuples from pgstat.h:551 (PostgreSQL 15)
///
/// ```text
/// #define pgstat_count_index_tuples( rel , n ) do { if ( pgstat_should_count_relation ( rel ) ) ( rel ) -> pgstat_info -> t_counts . t_tuples_returned += ( n ) ; } while ( 0 )
/// ```
///
///
#[doc = crate::__pgrx_c_doc_statements!()]
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
///
/// # Panics
///
/// Checked signed arithmetic rejects overflow when the recorded C profile does not define wrapping; pointer arithmetic checks representable offsets and distances but still requires valid allocation bounds. Conversions involving floats reject nonfinite or out-of-range integer results; conversions into Rust enums reject values without a represented discriminant. Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! pgstat_count_index_tuples {
    ($rel:expr, $n:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(any(feature = "pg16", feature = "pg17", feature = "pg18", feature = "pg19"))]
/// C macro pgstat_count_index_tuples from pgstat.h:628 (PostgreSQL 16), pgstat.h:630 (PostgreSQL 17), pgstat.h:700 (PostgreSQL 18), pgstat.h:737 (PostgreSQL 19)
///
/// ```text
/// #define pgstat_count_index_tuples( rel , n ) do { if ( pgstat_should_count_relation ( rel ) ) ( rel ) -> pgstat_info -> counts . tuples_returned += ( n ) ; } while ( 0 )
/// ```
///
///
#[doc = crate::__pgrx_c_doc_statements!()]
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
///
/// # Panics
///
/// Checked signed arithmetic rejects overflow when the recorded C profile does not define wrapping; pointer arithmetic checks representable offsets and distances but still requires valid allocation bounds. Conversions involving floats reject nonfinite or out-of-range integer results; conversions into Rust enums reject values without a represented discriminant. Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! pgstat_count_index_tuples {
    ($rel:expr, $n:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(any(feature = "pg18", feature = "pg19"))]
/// C macro pgstat_is_ioop_tracked_in_bytes from pgstat.h:319 (PostgreSQL 18), pgstat.h:325 (PostgreSQL 19)
///
/// ```text
/// #define pgstat_is_ioop_tracked_in_bytes( io_op ) ( ( ( unsigned int ) ( io_op ) ) < IOOP_NUM_TYPES && ( ( unsigned int ) ( io_op ) ) >= IOOP_EXTEND )
/// ```
///
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
///
/// # Panics
///
/// Conversions involving floats reject nonfinite or out-of-range integer results; conversions into Rust enums reject values without a represented discriminant. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! pgstat_is_ioop_tracked_in_bytes {
    ($io_op:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
/// C macro pgstat_should_count_relation from pgstat.h:525 (PostgreSQL 15), pgstat.h:602 (PostgreSQL 16), pgstat.h:604 (PostgreSQL 17), pgstat.h:674 (PostgreSQL 18), pgstat.h:711 (PostgreSQL 19)
///
/// ```text
/// #define pgstat_should_count_relation( rel ) ( likely ( ( rel ) -> pgstat_info != NULL ) ? true : ( ( rel ) -> pgstat_enabled ? pgstat_assoc_relation ( rel ) , true : false ) )
/// ```
///
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
///
/// # Panics
///
/// Conversions involving floats reject nonfinite or out-of-range integer results; conversions into Rust enums reject values without a represented discriminant. Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! pgstat_should_count_relation {
    ($rel:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
pub use pgstat_count_buffer_hit;
pub use pgstat_count_buffer_read;
pub use pgstat_count_buffer_read_time;
pub use pgstat_count_buffer_write_time;
pub use pgstat_count_conn_active_time;
pub use pgstat_count_conn_txn_idle_time;
pub use pgstat_count_heap_fetch;
pub use pgstat_count_heap_getnext;
pub use pgstat_count_heap_scan;
pub use pgstat_count_index_scan;
pub use pgstat_count_index_tuples;
#[cfg(any(feature = "pg18", feature = "pg19"))]
pub use pgstat_is_ioop_tracked_in_bytes;
pub use pgstat_should_count_relation;
