/* Automatically generated by pgrx-c-macros. Do not hand-edit.

This code is generated for documentation purposes, so that it is easy to reference on docs.rs. C macros and their support code are regenerated for your build of pgrx, and your Postgres configuration may differ.
*/
// C macros from guc.h.

#[cfg(not(all(
    target_arch = "aarch64",
    target_os = "macos",
    target_pointer_width = "64",
    target_endian = "little"
)))]
#[cfg(not(docsrs))]
compile_error!("generated C macros require their inspected C target profile");
#[doc(hidden)]
#[macro_export]
macro_rules! __pgrx_c_args_EmitWarningsOnPlaceholders {
    (@collect $mode:ident [$($done:tt)*]; $($raw:tt)*) => {
        $crate::__pgrx_c_args_EmitWarningsOnPlaceholders!(@p0 $mode [$($done)*]; $($raw)*)
    };
    (@classified [$next:ident $mode:ident [$($done:tt)*] [$($rest:tt)*]] $descriptor:tt) => {
        $crate::__pgrx_c_args_EmitWarningsOnPlaceholders!(
            @$next $mode [$($done)* $descriptor,];
            $($rest)*
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; - $argument:literal) => {
        $crate::__pgrx_c_args_EmitWarningsOnPlaceholders!(
            @p1 $mode [$($done)* (@literal [- $argument]),];
        )
    };
    (@negative0 $mode:ident [$($done:tt)*]; $argument:expr) => {
        $crate::__pgrx_c_args_EmitWarningsOnPlaceholders!(
            @p1 $mode [$($done)* (@native [$argument]),];
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; - $argument:literal, $($rest:tt)*) => {
        $crate::__pgrx_c_args_EmitWarningsOnPlaceholders!(
            @p1 $mode [$($done)* (@literal [- $argument]),];
            $($rest)*
        )
    };
    (@negative0 $mode:ident [$($done:tt)*]; $argument:expr, $($rest:tt)*) => {
        $crate::__pgrx_c_args_EmitWarningsOnPlaceholders!(
            @p1 $mode [$($done)* (@native [$argument]),];
            $($rest)*
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; - $($raw:tt)*) => {
        $crate::__pgrx_c_args_EmitWarningsOnPlaceholders!(@negative0 $mode [$($done)*]; - $($raw)*)
    };
    (@p0 $mode:ident [$($done:tt)*]; (@__pgrx_c_native [$argument:expr])) => {
        $crate::__pgrx_c_args_EmitWarningsOnPlaceholders!(
            @p1 $mode [$($done)* (@native [$argument]),];
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; $head:ident $(::$tail:ident)* ! $group:tt) => {
        $crate::__pgrx_c_classify!(
            @argument [__pgrx_c_args_EmitWarningsOnPlaceholders] [p1 $mode [$($done)*] []] [
                $head $(::$tail)* ! $group
            ]
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; ::$head:ident $(::$tail:ident)* ! $group:tt) => {
        $crate::__pgrx_c_classify!(
            @argument [__pgrx_c_args_EmitWarningsOnPlaceholders] [p1 $mode [$($done)*] []] [
                ::$head $(::$tail)* ! $group
            ]
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; ($($inner:tt)*)) => {
        $crate::__pgrx_c_classify!(
            @argument [__pgrx_c_args_EmitWarningsOnPlaceholders] [p1 $mode [$($done)*] []] [
                ($($inner)*)
            ]
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; $argument:literal) => {
        $crate::__pgrx_c_args_EmitWarningsOnPlaceholders!(
            @p1 $mode [$($done)* (@literal [$argument]),];
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; $argument:expr) => {
        $crate::__pgrx_c_args_EmitWarningsOnPlaceholders!(
            @p1 $mode [$($done)* (@native [$argument]),];
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; (@__pgrx_c_native [$argument:expr]), $($rest:tt)*) => {
        $crate::__pgrx_c_args_EmitWarningsOnPlaceholders!(
            @p1 $mode [$($done)* (@native [$argument]),];
            $($rest)*
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; $head:ident $(::$tail:ident)* ! $group:tt, $($rest:tt)*) => {
        $crate::__pgrx_c_classify!(
            @argument [__pgrx_c_args_EmitWarningsOnPlaceholders] [p1 $mode [$($done)*] [$($rest)*]] [
                $head $(::$tail)* ! $group
            ]
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; ::$head:ident $(::$tail:ident)* ! $group:tt, $($rest:tt)*) => {
        $crate::__pgrx_c_classify!(
            @argument [__pgrx_c_args_EmitWarningsOnPlaceholders] [p1 $mode [$($done)*] [$($rest)*]] [
                ::$head $(::$tail)* ! $group
            ]
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; ($($inner:tt)*), $($rest:tt)*) => {
        $crate::__pgrx_c_classify!(
            @argument [__pgrx_c_args_EmitWarningsOnPlaceholders] [p1 $mode [$($done)*] [$($rest)*]] [
                ($($inner)*)
            ]
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; $argument:literal, $($rest:tt)*) => {
        $crate::__pgrx_c_args_EmitWarningsOnPlaceholders!(
            @p1 $mode [$($done)* (@literal [$argument]),];
            $($rest)*
        )
    };
    (@p0 $mode:ident [$($done:tt)*]; $argument:expr, $($rest:tt)*) => {
        $crate::__pgrx_c_args_EmitWarningsOnPlaceholders!(
            @p1 $mode [$($done)* (@native [$argument]),];
            $($rest)*
        )
    };
    (@p1 $mode:ident [$($done:tt)*];) => {
        $crate::EmitWarningsOnPlaceholders!(@$mode; $($done)*)
    };
    ($($invalid:tt)*) => {
        compile_error!("arguments do not satisfy this C macro's invocation contract")
    };
}
/// C macro EmitWarningsOnPlaceholders from guc.h:365
///
/// ```text
/// #define EmitWarningsOnPlaceholders( className ) MarkGUCPrefixReserved ( className )
/// ```
#[macro_export]
macro_rules! EmitWarningsOnPlaceholders {
    (@__pgrx_emit_public; $className:tt $(,)?) => {
        $crate::__pgrx_c_macros::expression_result::finish(
            $crate::EmitWarningsOnPlaceholders!(@__pgrx_emit_value; $className)
        )
    };
    (@__pgrx_emit_value; $className:tt $(,)?) => {
        /* PGRX: EmitWarningsOnPlaceholders remains expanded because MarkGUCPrefixReserved is not an active function-like macro. */
        $crate::__pgrx_c_macros::expression::profile_value::<true, _>(
            $crate::MarkGUCPrefixReserved(
                <
                    $crate::__pgrx_c_macros::expression::CPointer<
                        $crate::__pgrx_c_macros::CChar,
                        $crate::__pgrx_c_macros::expression::ReadOnly
                    > as $crate::__pgrx_c_macros::expression::CType
                >::into_storage(
                    $crate::__pgrx_c_macros::expression::implicit::<
                        $crate::__pgrx_c_macros::expression::CPointer<
                            $crate::__pgrx_c_macros::CChar,
                            $crate::__pgrx_c_macros::expression::ReadOnly
                        >,
                        _
                    >(
                        $crate::__pgrx_c_macros::expression::profile_value::<true, _>(
                            $crate::__pgrx_c_operand!(@value [true]; $className)
                        )
                    )
                ),
            )
        )
    };
    (@__pgrx_c_value; $($raw:tt)*) => {
        $crate::__pgrx_c_args_EmitWarningsOnPlaceholders!(@collect __pgrx_emit_value []; $($raw)*)
    };
    (@__pgrx_emit_place; $className:tt $(,)?) => {
        compile_error!("C expression is not a place in this operation")
    };
    (@__pgrx_c_place; $($raw:tt)*) => {
        $crate::__pgrx_c_args_EmitWarningsOnPlaceholders!(@collect __pgrx_emit_place []; $($raw)*)
    };
    (@__pgrx_emit_read_place; $className:tt $(,)?) => {
        compile_error!("C expression is not a place in this operation")
    };
    (@__pgrx_c_read_place; $($raw:tt)*) => {
        $crate::__pgrx_c_args_EmitWarningsOnPlaceholders!(
            @collect __pgrx_emit_read_place [];
            $($raw)*
        )
    };
    (@__pgrx_emit_size; $className:tt $(,)?) => {
        /* PGRX: EmitWarningsOnPlaceholders remains expanded because MarkGUCPrefixReserved is not an active function-like macro. */
        $crate::__pgrx_c_macros::expression::size_of_value_type(
            if false {
                Some(
                    unsafe {
                        $crate::__pgrx_c_macros::expression::profile_value::<true, _>(
                            $crate::MarkGUCPrefixReserved(
                                <
                                    $crate::__pgrx_c_macros::expression::CPointer<
                                        $crate::__pgrx_c_macros::CChar,
                                        $crate::__pgrx_c_macros::expression::ReadOnly
                                    > as $crate::__pgrx_c_macros::expression::CType
                                >::into_storage(
                                    $crate::__pgrx_c_macros::expression::implicit::<
                                        $crate::__pgrx_c_macros::expression::CPointer<
                                            $crate::__pgrx_c_macros::CChar,
                                            $crate::__pgrx_c_macros::expression::ReadOnly
                                        >,
                                        _
                                    >(
                                        $crate::__pgrx_c_macros::expression::profile_value::<
                                            true,
                                            _
                                        >($crate::__pgrx_c_operand!(@value [true]; $className))
                                    )
                                ),
                            )
                        )
                    }
                )
            } else {
                None
            }
        )
    };
    (@__pgrx_c_size; $($raw:tt)*) => {
        $crate::__pgrx_c_args_EmitWarningsOnPlaceholders!(@collect __pgrx_emit_size []; $($raw)*)
    };
    (@__pgrx_emit_discard; $className:tt $(,)?) => {
        /* PGRX: EmitWarningsOnPlaceholders remains expanded because MarkGUCPrefixReserved is not an active function-like macro. */
        {
            let _ = $crate::__pgrx_c_macros::expression::profile_value::<true, _>(
                $crate::MarkGUCPrefixReserved(
                    <
                        $crate::__pgrx_c_macros::expression::CPointer<
                            $crate::__pgrx_c_macros::CChar,
                            $crate::__pgrx_c_macros::expression::ReadOnly
                        > as $crate::__pgrx_c_macros::expression::CType
                    >::into_storage(
                        $crate::__pgrx_c_macros::expression::implicit::<
                            $crate::__pgrx_c_macros::expression::CPointer<
                                $crate::__pgrx_c_macros::CChar,
                                $crate::__pgrx_c_macros::expression::ReadOnly
                            >,
                            _
                        >(
                            $crate::__pgrx_c_macros::expression::profile_value::<true, _>(
                                $crate::__pgrx_c_operand!(@value [true]; $className)
                            )
                        )
                    ),
                )
            );
        }
    };
    (@__pgrx_c_discard; $($raw:tt)*) => {
        $crate::__pgrx_c_args_EmitWarningsOnPlaceholders!(@collect __pgrx_emit_discard []; $($raw)*)
    };
    ($($raw:tt)*) => {
        $crate::__pgrx_c_args_EmitWarningsOnPlaceholders!(@collect __pgrx_emit_public []; $($raw)*)
    };
}

pub use EmitWarningsOnPlaceholders;
