// Automatically generated by pgrx-c-macros for documentation. Do not hand-edit.
// C macros from heaptoast.h.

/// C macro MaximumBytesPerTuple from heaptoast.h:23 (PostgreSQL 15–19)
///
/// ```text
/// #define MaximumBytesPerTuple( tuplesPerPage ) MAXALIGN_DOWN ( ( BLCKSZ - MAXALIGN ( SizeOfPageHeaderData + ( tuplesPerPage ) * sizeof ( ItemIdData ) ) ) / ( tuplesPerPage ) )
/// ```
///
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
///
/// # Panics
///
/// Checked signed arithmetic rejects overflow when the recorded C profile does not define wrapping; pointer arithmetic checks representable offsets and distances but still requires valid allocation bounds. Conversions involving floats reject nonfinite or out-of-range integer results; conversions into Rust enums reject values without a represented discriminant. Integer division/remainder rejects zero divisors and signed MIN / -1 overflow. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! MaximumBytesPerTuple {
    ($tuplesPerPage:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
pub use MaximumBytesPerTuple;
