// Automatically generated by pgrx-c-macros for documentation. Do not hand-edit.
// C macros from xlogutils.h.

/// C macro InHotStandby from xlogutils.h:57 (PostgreSQL 15–17), xlogutils.h:60 (PostgreSQL 18–19)
///
/// ```text
/// #define InHotStandby ( standbyState >= STANDBY_SNAPSHOT_PENDING )
/// ```
///
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
#[macro_export]
macro_rules! InHotStandby {
    () => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
pub use InHotStandby;
