// Automatically generated by pgrx-c-macros for documentation. Do not hand-edit.
// C macros from xlog.h.

#[cfg(any(feature = "pg15", feature = "pg16", feature = "pg17", feature = "pg19"))]
/// C macro XLogArchivingActive from xlog.h:94 (PostgreSQL 15–16), xlog.h:97 (PostgreSQL 17), xlog.h:102 (PostgreSQL 19)
///
/// ```text
/// #define XLogArchivingActive( ) ( AssertMacro ( XLogArchiveMode == ARCHIVE_MODE_OFF || wal_level >= WAL_LEVEL_REPLICA ) , XLogArchiveMode > ARCHIVE_MODE_OFF )
/// ```
///
///
/// Invocation diagnostics use Rust `file!()` and `line!()` at the outer Rust source invocation. The filename is a static UTF-8 byte array with a final zero; the line must fit the inspected C int. Source-line-dependent C preprocessing and integer-constant-expression identity are outside this diagnostic contract. String arrays retain their complete char-array extent for size and address operations, and decay to read-only pointers for values. Literal mutation is rejected because C string-literal writes are undefined.
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Conversions involving floats reject nonfinite or out-of-range integer results; conversions into Rust enums reject values without a represented discriminant. Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! XLogArchivingActive {
    () => {
        ::core::unimplemented!("pgrx documentation snapshot; C macros are generated for each build")
    };
}
#[cfg(feature = "pg18")]
/// C macro XLogArchivingActive from xlog.h:99 (PostgreSQL 18)
///
/// ```text
/// #define XLogArchivingActive( ) ( AssertMacro ( XLogArchiveMode == ARCHIVE_MODE_OFF || wal_level >= WAL_LEVEL_REPLICA ) , XLogArchiveMode > ARCHIVE_MODE_OFF )
/// ```
///
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Conversions involving floats reject nonfinite or out-of-range integer results; conversions into Rust enums reject values without a represented discriminant. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! XLogArchivingActive {
    () => {
        ::core::unimplemented!("pgrx documentation snapshot; C macros are generated for each build")
    };
}
#[cfg(any(feature = "pg15", feature = "pg16", feature = "pg17", feature = "pg19"))]
/// C macro XLogArchivingAlways from xlog.h:97 (PostgreSQL 15–16), xlog.h:100 (PostgreSQL 17), xlog.h:105 (PostgreSQL 19)
///
/// ```text
/// #define XLogArchivingAlways( ) ( AssertMacro ( XLogArchiveMode == ARCHIVE_MODE_OFF || wal_level >= WAL_LEVEL_REPLICA ) , XLogArchiveMode == ARCHIVE_MODE_ALWAYS )
/// ```
///
///
/// Invocation diagnostics use Rust `file!()` and `line!()` at the outer Rust source invocation. The filename is a static UTF-8 byte array with a final zero; the line must fit the inspected C int. Source-line-dependent C preprocessing and integer-constant-expression identity are outside this diagnostic contract. String arrays retain their complete char-array extent for size and address operations, and decay to read-only pointers for values. Literal mutation is rejected because C string-literal writes are undefined.
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Conversions involving floats reject nonfinite or out-of-range integer results; conversions into Rust enums reject values without a represented discriminant. Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! XLogArchivingAlways {
    () => {
        ::core::unimplemented!("pgrx documentation snapshot; C macros are generated for each build")
    };
}
#[cfg(feature = "pg18")]
/// C macro XLogArchivingAlways from xlog.h:102 (PostgreSQL 18)
///
/// ```text
/// #define XLogArchivingAlways( ) ( AssertMacro ( XLogArchiveMode == ARCHIVE_MODE_OFF || wal_level >= WAL_LEVEL_REPLICA ) , XLogArchiveMode == ARCHIVE_MODE_ALWAYS )
/// ```
///
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Conversions involving floats reject nonfinite or out-of-range integer results; conversions into Rust enums reject values without a represented discriminant. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! XLogArchivingAlways {
    () => {
        ::core::unimplemented!("pgrx documentation snapshot; C macros are generated for each build")
    };
}
#[cfg(any(feature = "pg15", feature = "pg16", feature = "pg17", feature = "pg18"))]
/// C macro XLogHintBitIsNeeded from xlog.h:115 (PostgreSQL 15–16), xlog.h:118 (PostgreSQL 17), xlog.h:120 (PostgreSQL 18)
///
/// ```text
/// #define XLogHintBitIsNeeded( ) ( DataChecksumsEnabled ( ) || wal_log_hints )
/// ```
///
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! XLogHintBitIsNeeded {
    () => {
        ::core::unimplemented!("pgrx documentation snapshot; C macros are generated for each build")
    };
}
#[cfg(feature = "pg19")]
/// C macro XLogHintBitIsNeeded from xlog.h:123 (PostgreSQL 19)
///
/// ```text
/// #define XLogHintBitIsNeeded( ) ( wal_log_hints || DataChecksumsNeedWrite ( ) )
/// ```
///
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! XLogHintBitIsNeeded {
    () => {
        ::core::unimplemented!("pgrx documentation snapshot; C macros are generated for each build")
    };
}
/// C macro XLogIsNeeded from xlog.h:104 (PostgreSQL 15–16), xlog.h:107 (PostgreSQL 17), xlog.h:109 (PostgreSQL 18), xlog.h:112 (PostgreSQL 19)
///
/// ```text
/// #define XLogIsNeeded( ) ( wal_level >= WAL_LEVEL_REPLICA )
/// ```
///
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
#[macro_export]
macro_rules! XLogIsNeeded {
    () => {
        ::core::unimplemented!("pgrx documentation snapshot; C macros are generated for each build")
    };
}
#[cfg(any(feature = "pg15", feature = "pg16", feature = "pg17", feature = "pg18"))]
/// C macro XLogLogicalInfoActive from xlog.h:121 (PostgreSQL 15–16), xlog.h:124 (PostgreSQL 17), xlog.h:126 (PostgreSQL 18)
///
/// ```text
/// #define XLogLogicalInfoActive( ) ( wal_level >= WAL_LEVEL_LOGICAL )
/// ```
///
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
#[macro_export]
macro_rules! XLogLogicalInfoActive {
    () => {
        ::core::unimplemented!("pgrx documentation snapshot; C macros are generated for each build")
    };
}
#[cfg(feature = "pg19")]
/// C macro XLogLogicalInfoActive from xlog.h:137 (PostgreSQL 19)
///
/// ```text
/// #define XLogLogicalInfoActive( ) ( wal_level >= WAL_LEVEL_LOGICAL || XLogLogicalInfo )
/// ```
///
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
#[macro_export]
macro_rules! XLogLogicalInfoActive {
    () => {
        ::core::unimplemented!("pgrx documentation snapshot; C macros are generated for each build")
    };
}
/// C macro XLogStandbyInfoActive from xlog.h:118 (PostgreSQL 15–16), xlog.h:121 (PostgreSQL 17), xlog.h:123 (PostgreSQL 18), xlog.h:126 (PostgreSQL 19)
///
/// ```text
/// #define XLogStandbyInfoActive( ) ( wal_level >= WAL_LEVEL_REPLICA )
/// ```
///
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
#[macro_export]
macro_rules! XLogStandbyInfoActive {
    () => {
        ::core::unimplemented!("pgrx documentation snapshot; C macros are generated for each build")
    };
}
pub use XLogArchivingActive;
pub use XLogArchivingAlways;
pub use XLogHintBitIsNeeded;
pub use XLogIsNeeded;
pub use XLogLogicalInfoActive;
pub use XLogStandbyInfoActive;
