// Automatically generated by pgrx-c-macros for documentation. Do not hand-edit.
// C macros from pg_crc32c.h.

#[cfg(any(feature = "pg15", feature = "pg16", feature = "pg17", feature = "pg18"))]
/// C macro COMP_CRC32C from pg_crc32c.h:55 (PostgreSQL 15–17), pg_crc32c.h:120 (PostgreSQL 18)
///
/// ```text
/// #define COMP_CRC32C( crc , data , len ) ( ( crc ) = pg_comp_crc32c_armv8 ( ( crc ) , ( data ) , ( len ) ) )
/// ```
///
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! COMP_CRC32C {
    ($crc:expr, $data:expr, $len:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
/// C macro EQ_CRC32C from pg_crc32c.h:42 (PostgreSQL 15–19)
///
/// ```text
/// #define EQ_CRC32C( c1 , c2 ) ( ( c1 ) == ( c2 ) )
/// ```
///
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
#[macro_export]
macro_rules! EQ_CRC32C {
    ($c1:expr, $c2:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
/// C macro FIN_CRC32C from pg_crc32c.h:57 (PostgreSQL 15–17), pg_crc32c.h:122 (PostgreSQL 18), pg_crc32c.h:135 (PostgreSQL 19)
///
/// ```text
/// #define FIN_CRC32C( crc ) ( ( crc ) ^= 0xFFFFFFFF )
/// ```
///
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
#[macro_export]
macro_rules! FIN_CRC32C {
    ($crc:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
/// C macro INIT_CRC32C from pg_crc32c.h:41 (PostgreSQL 15–19)
///
/// ```text
/// #define INIT_CRC32C( crc ) ( ( crc ) = 0xFFFFFFFF )
/// ```
///
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
#[macro_export]
macro_rules! INIT_CRC32C {
    ($crc:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(any(feature = "pg15", feature = "pg16", feature = "pg17", feature = "pg18"))]
pub use COMP_CRC32C;
pub use EQ_CRC32C;
pub use FIN_CRC32C;
pub use INIT_CRC32C;
