-- This file is auto generated by pgx.
-- `extension_sql!()` defined SQL.


-- Enums derived via `#[derive(PostgresEnum)]`


-- Shell types for types defined by `#[derive(PostgresType)]`


-- Functions defined by `#[pg_extern]`

-- src/lib.rs:36
-- strings::split_set
CREATE OR REPLACE FUNCTION "split_set"(
	"input" text ,/* &str */
	"pattern" text /* &str */
) RETURNS SETOF str /* str */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'split_set';

-- src/lib.rs:31
-- strings::split
CREATE OR REPLACE FUNCTION "split"(
	"input" text ,/* &str */
	"pattern" text /* &str */
) RETURNS text[] /* alloc::vec::Vec<&str> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'split';

-- src/lib.rs:24
-- strings::append
CREATE OR REPLACE FUNCTION "append"(
	"input" text ,/* alloc::string::String */
	"extra" text /* &str */
) RETURNS text /* alloc::string::String */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'append';

-- src/lib.rs:19
-- strings::substring
CREATE OR REPLACE FUNCTION "substring"(
	"input" text ,/* &str */
	"start" integer ,/* i32 */
	"end" integer /* i32 */
) RETURNS text /* &str */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'substring';

-- src/lib.rs:14
-- strings::to_lowercase
CREATE OR REPLACE FUNCTION "to_lowercase"(
	"input" text /* &str */
) RETURNS text /* alloc::string::String */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'to_lowercase';

-- src/lib.rs:9
-- strings::return_static
CREATE OR REPLACE FUNCTION "return_static"() RETURNS text /* &str */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'return_static';


-- Types defined by `#[derive(PostgresType)]`


-- Operator classes defined by `#[derive(PostgresHash, PostgresOrd)]`

