// Automatically generated by pgrx-c-macros for documentation. Do not hand-edit.
// C macros from dsa.h.

/// C macro DsaPointerIsValid from dsa.h:81 (PostgreSQL 15–16), dsa.h:106 (PostgreSQL 17–19)
///
/// ```text
/// #define DsaPointerIsValid( x ) ( ( x ) != InvalidDsaPointer )
/// ```
///
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
#[macro_export]
macro_rules! DsaPointerIsValid {
    ($x:expr $(,)?) => {
        ::core::unimplemented!("pgrx documentation snapshot; C macros are generated for each build")
    };
}
/// C macro dsa_allocate from dsa.h:84 (PostgreSQL 15–16), dsa.h:109 (PostgreSQL 17–19)
///
/// ```text
/// #define dsa_allocate( area , size ) dsa_allocate_extended ( area , size , 0 )
/// ```
///
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! dsa_allocate {
    ($area:expr, $size:expr $(,)?) => {
        ::core::unimplemented!("pgrx documentation snapshot; C macros are generated for each build")
    };
}
/// C macro dsa_allocate0 from dsa.h:88 (PostgreSQL 15–16), dsa.h:113 (PostgreSQL 17–19)
///
/// ```text
/// #define dsa_allocate0( area , size ) dsa_allocate_extended ( area , size , DSA_ALLOC_ZERO )
/// ```
///
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! dsa_allocate0 {
    ($area:expr, $size:expr $(,)?) => {
        ::core::unimplemented!("pgrx documentation snapshot; C macros are generated for each build")
    };
}
#[cfg(any(feature = "pg17", feature = "pg18"))]
/// C macro dsa_create from dsa.h:117 (PostgreSQL 17–18)
///
/// ```text
/// #define dsa_create( tranch_id ) dsa_create_ext ( tranch_id , DSA_DEFAULT_INIT_SEGMENT_SIZE , DSA_MAX_SEGMENT_SIZE )
/// ```
///
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! dsa_create {
    ($tranch_id:expr $(,)?) => {
        ::core::unimplemented!("pgrx documentation snapshot; C macros are generated for each build")
    };
}
#[cfg(feature = "pg19")]
/// C macro dsa_create from dsa.h:117 (PostgreSQL 19)
///
/// ```text
/// #define dsa_create( tranche_id ) dsa_create_ext ( tranche_id , DSA_DEFAULT_INIT_SEGMENT_SIZE , DSA_MAX_SEGMENT_SIZE )
/// ```
///
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! dsa_create {
    ($tranche_id:expr $(,)?) => {
        ::core::unimplemented!("pgrx documentation snapshot; C macros are generated for each build")
    };
}
#[cfg(any(feature = "pg17", feature = "pg18"))]
/// C macro dsa_create_in_place from dsa.h:122 (PostgreSQL 17–18)
///
/// ```text
/// #define dsa_create_in_place( place , size , tranch_id , segment ) dsa_create_in_place_ext ( place , size , tranch_id , segment , DSA_DEFAULT_INIT_SEGMENT_SIZE , DSA_MAX_SEGMENT_SIZE )
/// ```
///
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! dsa_create_in_place {
    ($place:expr, $size:expr, $tranch_id:expr, $segment:expr $(,)?) => {
        ::core::unimplemented!("pgrx documentation snapshot; C macros are generated for each build")
    };
}
#[cfg(feature = "pg19")]
/// C macro dsa_create_in_place from dsa.h:122 (PostgreSQL 19)
///
/// ```text
/// #define dsa_create_in_place( place , size , tranche_id , segment ) dsa_create_in_place_ext ( place , size , tranche_id , segment , DSA_DEFAULT_INIT_SEGMENT_SIZE , DSA_MAX_SEGMENT_SIZE )
/// ```
///
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! dsa_create_in_place {
    ($place:expr, $size:expr, $tranche_id:expr, $segment:expr $(,)?) => {
        ::core::unimplemented!("pgrx documentation snapshot; C macros are generated for each build")
    };
}
pub use DsaPointerIsValid;
pub use dsa_allocate;
pub use dsa_allocate0;
#[cfg(any(feature = "pg17", feature = "pg18", feature = "pg19"))]
pub use dsa_create;
#[cfg(any(feature = "pg17", feature = "pg18", feature = "pg19"))]
pub use dsa_create_in_place;
