// Automatically generated by pgrx-c-macros for documentation. Do not hand-edit.
// C macros from float.h.

#[cfg(any(feature = "pg15", feature = "pg16", feature = "pg17", feature = "pg18"))]
/// Typed call adapter for C inline function get_float4_infinity from float.h:72 (PostgreSQL 15), float.h:73 (PostgreSQL 16–18)
///
/// ```c
/// static inline float4
/// get_float4_infinity(void)
/// {
/// #ifdef INFINITY
/// 	/* C99 standard way */
/// 	return (float4) INFINITY;
/// #else
/// #ifdef _MSC_VER
/// #pragma warning(default:4756)
/// #endif
///
/// 	/*
/// 	 * On some platforms, HUGE_VAL is an infinity, elsewhere it's just the
/// 	 * largest normal float8.  We assume forcing an overflow will get us a
/// 	 * true infinity.
/// 	 */
/// 	return (float4) (HUGE_VAL * HUGE_VAL);
/// #endif
/// }
/// ```
///
///
/// Calls the original function through its inspected C prototype. Each operand is evaluated once and converted using C parameter assignment rules. The result retains the function's original C type; `.get()` extracts its native storage, including `()` for a void result. Native calls retain the backend thread, PostgreSQL error, and caller safety contracts of the generated guarded binding.
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! get_float4_infinity {
    () => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(feature = "pg19")]
/// Typed call adapter for C inline function get_float4_infinity from float.h:60 (PostgreSQL 19)
///
/// ```c
/// static inline float4
/// get_float4_infinity(void)
/// {
/// 	/* C99 standard way */
/// 	return (float4) INFINITY;
/// }
/// ```
///
///
/// Calls the original function through its inspected C prototype. Each operand is evaluated once and converted using C parameter assignment rules. The result retains the function's original C type; `.get()` extracts its native storage, including `()` for a void result. Native calls retain the backend thread, PostgreSQL error, and caller safety contracts of the generated guarded binding.
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! get_float4_infinity {
    () => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(any(feature = "pg15", feature = "pg16", feature = "pg17", feature = "pg18"))]
/// Typed call adapter for C inline function get_float4_nan from float.h:109 (PostgreSQL 15), float.h:110 (PostgreSQL 16–18)
///
/// ```c
/// static inline float4
/// get_float4_nan(void)
/// {
/// #ifdef NAN
/// 	/* C99 standard way */
/// 	return (float4) NAN;
/// #else
/// 	/* Assume we can get a NAN via zero divide */
/// 	return (float4) (0.0 / 0.0);
/// #endif
/// }
/// ```
///
///
/// Calls the original function through its inspected C prototype. Each operand is evaluated once and converted using C parameter assignment rules. The result retains the function's original C type; `.get()` extracts its native storage, including `()` for a void result. Native calls retain the backend thread, PostgreSQL error, and caller safety contracts of the generated guarded binding.
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! get_float4_nan {
    () => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(feature = "pg19")]
/// Typed call adapter for C inline function get_float4_nan from float.h:79 (PostgreSQL 19)
///
/// ```c
/// static inline float4
/// get_float4_nan(void)
/// {
/// 	/* C99 standard way */
/// 	return (float4) NAN;
/// }
/// ```
///
///
/// Calls the original function through its inspected C prototype. Each operand is evaluated once and converted using C parameter assignment rules. The result retains the function's original C type; `.get()` extracts its native storage, including `()` for a void result. Native calls retain the backend thread, PostgreSQL error, and caller safety contracts of the generated guarded binding.
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! get_float4_nan {
    () => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(any(feature = "pg15", feature = "pg16", feature = "pg17", feature = "pg18"))]
/// Typed call adapter for C inline function get_float8_infinity from float.h:92 (PostgreSQL 15), float.h:93 (PostgreSQL 16–18)
///
/// ```c
/// static inline float8
/// get_float8_infinity(void)
/// {
/// #ifdef INFINITY
/// 	/* C99 standard way */
/// 	return (float8) INFINITY;
/// #else
///
/// 	/*
/// 	 * On some platforms, HUGE_VAL is an infinity, elsewhere it's just the
/// 	 * largest normal float8.  We assume forcing an overflow will get us a
/// 	 * true infinity.
/// 	 */
/// 	return (float8) (HUGE_VAL * HUGE_VAL);
/// #endif
/// }
/// ```
///
///
/// Calls the original function through its inspected C prototype. Each operand is evaluated once and converted using C parameter assignment rules. The result retains the function's original C type; `.get()` extracts its native storage, including `()` for a void result. Native calls retain the backend thread, PostgreSQL error, and caller safety contracts of the generated guarded binding.
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! get_float8_infinity {
    () => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(feature = "pg19")]
/// Typed call adapter for C inline function get_float8_infinity from float.h:67 (PostgreSQL 19)
///
/// ```c
/// static inline float8
/// get_float8_infinity(void)
/// {
/// 	/* C99 standard way */
/// 	return (float8) INFINITY;
/// }
/// ```
///
///
/// Calls the original function through its inspected C prototype. Each operand is evaluated once and converted using C parameter assignment rules. The result retains the function's original C type; `.get()` extracts its native storage, including `()` for a void result. Native calls retain the backend thread, PostgreSQL error, and caller safety contracts of the generated guarded binding.
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! get_float8_infinity {
    () => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(any(feature = "pg15", feature = "pg16", feature = "pg17", feature = "pg18"))]
/// Typed call adapter for C inline function get_float8_nan from float.h:121 (PostgreSQL 15), float.h:122 (PostgreSQL 16–18)
///
/// ```c
/// static inline float8
/// get_float8_nan(void)
/// {
/// 	/* (float8) NAN doesn't work on some NetBSD/MIPS releases */
/// #if defined(NAN) && !(defined(__NetBSD__) && defined(__mips__))
/// 	/* C99 standard way */
/// 	return (float8) NAN;
/// #else
/// 	/* Assume we can get a NaN via zero divide */
/// 	return (float8) (0.0 / 0.0);
/// #endif
/// }
/// ```
///
///
/// Calls the original function through its inspected C prototype. Each operand is evaluated once and converted using C parameter assignment rules. The result retains the function's original C type; `.get()` extracts its native storage, including `()` for a void result. Native calls retain the backend thread, PostgreSQL error, and caller safety contracts of the generated guarded binding.
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! get_float8_nan {
    () => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(feature = "pg19")]
/// Typed call adapter for C inline function get_float8_nan from float.h:86 (PostgreSQL 19)
///
/// ```c
/// static inline float8
/// get_float8_nan(void)
/// {
/// 	/* C99 standard way */
/// 	return (float8) NAN;
/// }
/// ```
///
///
/// Calls the original function through its inspected C prototype. Each operand is evaluated once and converted using C parameter assignment rules. The result retains the function's original C type; `.get()` extracts its native storage, including `()` for a void result. Native calls retain the backend thread, PostgreSQL error, and caller safety contracts of the generated guarded binding.
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! get_float8_nan {
    () => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
pub use get_float4_infinity;
pub use get_float4_nan;
pub use get_float8_infinity;
pub use get_float8_nan;
