// Automatically generated by pgrx-c-macros for documentation. Do not hand-edit.
// C macros from guc.h.

/// C macro EmitWarningsOnPlaceholders from guc.h:365 (PostgreSQL 15), guc.h:359 (PostgreSQL 16), guc.h:362 (PostgreSQL 17), guc.h:395 (PostgreSQL 18), guc.h:421 (PostgreSQL 19)
///
/// ```text
/// #define EmitWarningsOnPlaceholders( className ) MarkGUCPrefixReserved ( className )
/// ```
///
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! EmitWarningsOnPlaceholders {
    ($className:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
pub use EmitWarningsOnPlaceholders;
