// Automatically generated by pgrx-c-macros for documentation. Do not hand-edit.
// C macros from jsonb.h.

#[cfg(feature = "pg15")]
/// C macro DatumGetJsonbP from jsonb.h:71 (PostgreSQL 15)
///
/// ```text
/// #define DatumGetJsonbP( d ) ( ( Jsonb * ) PG_DETOAST_DATUM ( d ) )
/// ```
///
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Conversions involving floats reject nonfinite or out-of-range integer results; conversions into Rust enums reject values without a represented discriminant. Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! DatumGetJsonbP {
    ($d:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(any(feature = "pg16", feature = "pg17", feature = "pg18", feature = "pg19"))]
/// Typed call adapter for C inline function DatumGetJsonbP from jsonb.h:373 (PostgreSQL 16–18), jsonb.h:400 (PostgreSQL 19)
///
/// ```c
/// static inline Jsonb *
/// DatumGetJsonbP(Datum d)
/// {
/// 	return (Jsonb *) PG_DETOAST_DATUM(d);
/// }
/// ```
///
///
/// Calls the original function through its inspected C prototype. Each operand is evaluated once and converted using C parameter assignment rules. The result retains the function's original C type; `.get()` extracts its native storage, including `()` for a void result. Native calls retain the backend thread, PostgreSQL error, and caller safety contracts of the generated guarded binding.
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! DatumGetJsonbP {
    ($d:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(feature = "pg15")]
/// C macro DatumGetJsonbPCopy from jsonb.h:72 (PostgreSQL 15)
///
/// ```text
/// #define DatumGetJsonbPCopy( d ) ( ( Jsonb * ) PG_DETOAST_DATUM_COPY ( d ) )
/// ```
///
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Conversions involving floats reject nonfinite or out-of-range integer results; conversions into Rust enums reject values without a represented discriminant. Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! DatumGetJsonbPCopy {
    ($d:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(any(feature = "pg16", feature = "pg17", feature = "pg18", feature = "pg19"))]
/// Typed call adapter for C inline function DatumGetJsonbPCopy from jsonb.h:379 (PostgreSQL 16–18), jsonb.h:406 (PostgreSQL 19)
///
/// ```c
/// static inline Jsonb *
/// DatumGetJsonbPCopy(Datum d)
/// {
/// 	return (Jsonb *) PG_DETOAST_DATUM_COPY(d);
/// }
/// ```
///
///
/// Calls the original function through its inspected C prototype. Each operand is evaluated once and converted using C parameter assignment rules. The result retains the function's original C type; `.get()` extracts its native storage, including `()` for a void result. Native calls retain the backend thread, PostgreSQL error, and caller safety contracts of the generated guarded binding.
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! DatumGetJsonbPCopy {
    ($d:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
/// C macro IsAJsonbScalar from jsonb.h:305 (PostgreSQL 15), jsonb.h:297 (PostgreSQL 16–18), jsonb.h:299 (PostgreSQL 19)
///
/// ```text
/// #define IsAJsonbScalar( jsonbval ) ( ( ( jsonbval ) -> type >= jbvNull && ( jsonbval ) -> type <= jbvBool ) || ( jsonbval ) -> type == jbvDatetime )
/// ```
///
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
#[macro_export]
macro_rules! IsAJsonbScalar {
    ($jsonbval:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
/// C macro JBE_ADVANCE_OFFSET from jsonb.h:170 (PostgreSQL 15), jsonb.h:162 (PostgreSQL 16–18), jsonb.h:164 (PostgreSQL 19)
///
/// ```text
/// #define JBE_ADVANCE_OFFSET( offset , je ) do { JEntry je_ = ( je ) ; if ( JBE_HAS_OFF ( je_ ) ) ( offset ) = JBE_OFFLENFLD ( je_ ) ; else ( offset ) += JBE_OFFLENFLD ( je_ ) ; } while ( 0 )
/// ```
///
///
/// This macro executes C statements in order and yields no value. Local blocks retain their C scope. Pointer access and native calls keep their usual caller safety obligations. Caller argument tokens must not mention the macro's C local names, even inside groups: those invocations are rejected because C substitution can capture locals that Rust hygiene would resolve differently. The scope check also inspects forwarded expression fragments and is bounded to 4096 stringified bytes. Matches in fields, paths or strings are conservatively rejected.
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Checked signed arithmetic rejects overflow when the recorded C profile does not define wrapping; pointer arithmetic checks representable offsets and distances but still requires valid allocation bounds. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! JBE_ADVANCE_OFFSET {
    ($offset:expr, $je:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
/// C macro JBE_HAS_OFF from jsonb.h:160 (PostgreSQL 15), jsonb.h:152 (PostgreSQL 16–18), jsonb.h:154 (PostgreSQL 19)
///
/// ```text
/// #define JBE_HAS_OFF( je_ ) ( ( ( je_ ) & JENTRY_HAS_OFF ) != 0 )
/// ```
///
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
#[macro_export]
macro_rules! JBE_HAS_OFF {
    ($je_:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
/// C macro JBE_ISBOOL from jsonb.h:167 (PostgreSQL 15), jsonb.h:159 (PostgreSQL 16–18), jsonb.h:161 (PostgreSQL 19)
///
/// ```text
/// #define JBE_ISBOOL( je_ ) ( JBE_ISBOOL_TRUE ( je_ ) || JBE_ISBOOL_FALSE ( je_ ) )
/// ```
///
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
#[macro_export]
macro_rules! JBE_ISBOOL {
    ($je_:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
/// C macro JBE_ISBOOL_FALSE from jsonb.h:166 (PostgreSQL 15), jsonb.h:158 (PostgreSQL 16–18), jsonb.h:160 (PostgreSQL 19)
///
/// ```text
/// #define JBE_ISBOOL_FALSE( je_ ) ( ( ( je_ ) & JENTRY_TYPEMASK ) == JENTRY_ISBOOL_FALSE )
/// ```
///
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
#[macro_export]
macro_rules! JBE_ISBOOL_FALSE {
    ($je_:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
/// C macro JBE_ISBOOL_TRUE from jsonb.h:165 (PostgreSQL 15), jsonb.h:157 (PostgreSQL 16–18), jsonb.h:159 (PostgreSQL 19)
///
/// ```text
/// #define JBE_ISBOOL_TRUE( je_ ) ( ( ( je_ ) & JENTRY_TYPEMASK ) == JENTRY_ISBOOL_TRUE )
/// ```
///
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
#[macro_export]
macro_rules! JBE_ISBOOL_TRUE {
    ($je_:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
/// C macro JBE_ISCONTAINER from jsonb.h:163 (PostgreSQL 15), jsonb.h:155 (PostgreSQL 16–18), jsonb.h:157 (PostgreSQL 19)
///
/// ```text
/// #define JBE_ISCONTAINER( je_ ) ( ( ( je_ ) & JENTRY_TYPEMASK ) == JENTRY_ISCONTAINER )
/// ```
///
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
#[macro_export]
macro_rules! JBE_ISCONTAINER {
    ($je_:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
/// C macro JBE_ISNULL from jsonb.h:164 (PostgreSQL 15), jsonb.h:156 (PostgreSQL 16–18), jsonb.h:158 (PostgreSQL 19)
///
/// ```text
/// #define JBE_ISNULL( je_ ) ( ( ( je_ ) & JENTRY_TYPEMASK ) == JENTRY_ISNULL )
/// ```
///
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
#[macro_export]
macro_rules! JBE_ISNULL {
    ($je_:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
/// C macro JBE_ISNUMERIC from jsonb.h:162 (PostgreSQL 15), jsonb.h:154 (PostgreSQL 16–18), jsonb.h:156 (PostgreSQL 19)
///
/// ```text
/// #define JBE_ISNUMERIC( je_ ) ( ( ( je_ ) & JENTRY_TYPEMASK ) == JENTRY_ISNUMERIC )
/// ```
///
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
#[macro_export]
macro_rules! JBE_ISNUMERIC {
    ($je_:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
/// C macro JBE_ISSTRING from jsonb.h:161 (PostgreSQL 15), jsonb.h:153 (PostgreSQL 16–18), jsonb.h:155 (PostgreSQL 19)
///
/// ```text
/// #define JBE_ISSTRING( je_ ) ( ( ( je_ ) & JENTRY_TYPEMASK ) == JENTRY_ISSTRING )
/// ```
///
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
#[macro_export]
macro_rules! JBE_ISSTRING {
    ($je_:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
/// C macro JBE_OFFLENFLD from jsonb.h:159 (PostgreSQL 15), jsonb.h:151 (PostgreSQL 16–18), jsonb.h:153 (PostgreSQL 19)
///
/// ```text
/// #define JBE_OFFLENFLD( je_ ) ( ( je_ ) & JENTRY_OFFLENMASK )
/// ```
///
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
#[macro_export]
macro_rules! JBE_OFFLENFLD {
    ($je_:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(any(feature = "pg15", feature = "pg16", feature = "pg17", feature = "pg18"))]
/// C macro JB_ROOT_COUNT from jsonb.h:227 (PostgreSQL 15), jsonb.h:219 (PostgreSQL 16–18)
///
/// ```text
/// #define JB_ROOT_COUNT( jbp_ ) ( * ( uint32 * ) VARDATA ( jbp_ ) & JB_CMASK )
/// ```
///
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Conversions involving floats reject nonfinite or out-of-range integer results; conversions into Rust enums reject values without a represented discriminant. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! JB_ROOT_COUNT {
    ($jbp_:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(feature = "pg19")]
/// C macro JB_ROOT_COUNT from jsonb.h:221 (PostgreSQL 19)
///
/// ```text
/// #define JB_ROOT_COUNT( jbp_ ) ( * ( uint32 * ) VARDATA ( jbp_ ) & JB_CMASK )
/// ```
///
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Conversions involving floats reject nonfinite or out-of-range integer results; conversions into Rust enums reject values without a represented discriminant. Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! JB_ROOT_COUNT {
    ($jbp_:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(any(feature = "pg15", feature = "pg16", feature = "pg17", feature = "pg18"))]
/// C macro JB_ROOT_IS_ARRAY from jsonb.h:230 (PostgreSQL 15), jsonb.h:222 (PostgreSQL 16–18)
///
/// ```text
/// #define JB_ROOT_IS_ARRAY( jbp_ ) ( ( * ( uint32 * ) VARDATA ( jbp_ ) & JB_FARRAY ) != 0 )
/// ```
///
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Conversions involving floats reject nonfinite or out-of-range integer results; conversions into Rust enums reject values without a represented discriminant. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! JB_ROOT_IS_ARRAY {
    ($jbp_:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(feature = "pg19")]
/// C macro JB_ROOT_IS_ARRAY from jsonb.h:224 (PostgreSQL 19)
///
/// ```text
/// #define JB_ROOT_IS_ARRAY( jbp_ ) ( ( * ( uint32 * ) VARDATA ( jbp_ ) & JB_FARRAY ) != 0 )
/// ```
///
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Conversions involving floats reject nonfinite or out-of-range integer results; conversions into Rust enums reject values without a represented discriminant. Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! JB_ROOT_IS_ARRAY {
    ($jbp_:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(any(feature = "pg15", feature = "pg16", feature = "pg17", feature = "pg18"))]
/// C macro JB_ROOT_IS_OBJECT from jsonb.h:229 (PostgreSQL 15), jsonb.h:221 (PostgreSQL 16–18)
///
/// ```text
/// #define JB_ROOT_IS_OBJECT( jbp_ ) ( ( * ( uint32 * ) VARDATA ( jbp_ ) & JB_FOBJECT ) != 0 )
/// ```
///
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Conversions involving floats reject nonfinite or out-of-range integer results; conversions into Rust enums reject values without a represented discriminant. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! JB_ROOT_IS_OBJECT {
    ($jbp_:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(feature = "pg19")]
/// C macro JB_ROOT_IS_OBJECT from jsonb.h:223 (PostgreSQL 19)
///
/// ```text
/// #define JB_ROOT_IS_OBJECT( jbp_ ) ( ( * ( uint32 * ) VARDATA ( jbp_ ) & JB_FOBJECT ) != 0 )
/// ```
///
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Conversions involving floats reject nonfinite or out-of-range integer results; conversions into Rust enums reject values without a represented discriminant. Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! JB_ROOT_IS_OBJECT {
    ($jbp_:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(any(feature = "pg15", feature = "pg16", feature = "pg17", feature = "pg18"))]
/// C macro JB_ROOT_IS_SCALAR from jsonb.h:228 (PostgreSQL 15), jsonb.h:220 (PostgreSQL 16–18)
///
/// ```text
/// #define JB_ROOT_IS_SCALAR( jbp_ ) ( ( * ( uint32 * ) VARDATA ( jbp_ ) & JB_FSCALAR ) != 0 )
/// ```
///
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Conversions involving floats reject nonfinite or out-of-range integer results; conversions into Rust enums reject values without a represented discriminant. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! JB_ROOT_IS_SCALAR {
    ($jbp_:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(feature = "pg19")]
/// C macro JB_ROOT_IS_SCALAR from jsonb.h:222 (PostgreSQL 19)
///
/// ```text
/// #define JB_ROOT_IS_SCALAR( jbp_ ) ( ( * ( uint32 * ) VARDATA ( jbp_ ) & JB_FSCALAR ) != 0 )
/// ```
///
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Conversions involving floats reject nonfinite or out-of-range integer results; conversions into Rust enums reject values without a represented discriminant. Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! JB_ROOT_IS_SCALAR {
    ($jbp_:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
/// C macro JsonContainerIsArray from jsonb.h:217 (PostgreSQL 15), jsonb.h:209 (PostgreSQL 16–18), jsonb.h:211 (PostgreSQL 19)
///
/// ```text
/// #define JsonContainerIsArray( jc ) ( ( ( jc ) -> header & JB_FARRAY ) != 0 )
/// ```
///
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
#[macro_export]
macro_rules! JsonContainerIsArray {
    ($jc:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
/// C macro JsonContainerIsObject from jsonb.h:216 (PostgreSQL 15), jsonb.h:208 (PostgreSQL 16–18), jsonb.h:210 (PostgreSQL 19)
///
/// ```text
/// #define JsonContainerIsObject( jc ) ( ( ( jc ) -> header & JB_FOBJECT ) != 0 )
/// ```
///
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
#[macro_export]
macro_rules! JsonContainerIsObject {
    ($jc:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
/// C macro JsonContainerIsScalar from jsonb.h:215 (PostgreSQL 15), jsonb.h:207 (PostgreSQL 16–18), jsonb.h:209 (PostgreSQL 19)
///
/// ```text
/// #define JsonContainerIsScalar( jc ) ( ( ( jc ) -> header & JB_FSCALAR ) != 0 )
/// ```
///
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
#[macro_export]
macro_rules! JsonContainerIsScalar {
    ($jc:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
/// C macro JsonContainerSize from jsonb.h:214 (PostgreSQL 15), jsonb.h:206 (PostgreSQL 16–18), jsonb.h:208 (PostgreSQL 19)
///
/// ```text
/// #define JsonContainerSize( jc ) ( ( jc ) -> header & JB_CMASK )
/// ```
///
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
#[macro_export]
macro_rules! JsonContainerSize {
    ($jc:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(feature = "pg15")]
/// C macro JsonbPGetDatum from jsonb.h:73 (PostgreSQL 15)
///
/// ```text
/// #define JsonbPGetDatum( p ) PointerGetDatum ( p )
/// ```
///
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Conversions involving floats reject nonfinite or out-of-range integer results; conversions into Rust enums reject values without a represented discriminant. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! JsonbPGetDatum {
    ($p:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(any(feature = "pg16", feature = "pg17", feature = "pg18", feature = "pg19"))]
/// Typed call adapter for C inline function JsonbPGetDatum from jsonb.h:385 (PostgreSQL 16–18), jsonb.h:412 (PostgreSQL 19)
///
/// ```c
/// static inline Datum
/// JsonbPGetDatum(const Jsonb *p)
/// {
/// 	return PointerGetDatum(p);
/// }
/// ```
///
///
/// Calls the original function through its inspected C prototype. Each operand is evaluated once and converted using C parameter assignment rules. The result retains the function's original C type; `.get()` extracts its native storage, including `()` for a void result. Native calls retain the backend thread, PostgreSQL error, and caller safety contracts of the generated guarded binding.
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! JsonbPGetDatum {
    ($p:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(feature = "pg15")]
/// C macro PG_GETARG_JSONB_P from jsonb.h:74 (PostgreSQL 15)
///
/// ```text
/// #define PG_GETARG_JSONB_P( x ) DatumGetJsonbP ( PG_GETARG_DATUM ( x ) )
/// ```
///
///
/// Rust callers supply 2 arguments: the 1 original C parameter, followed by explicit caller-scope operands in this order: `fcinfo`. Each operand must preserve its C type and place requirements.
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Conversions involving floats reject nonfinite or out-of-range integer results; conversions into Rust enums reject values without a represented discriminant. Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! PG_GETARG_JSONB_P {
    ($x:expr, $fcinfo:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(any(feature = "pg16", feature = "pg17", feature = "pg18", feature = "pg19"))]
/// C macro PG_GETARG_JSONB_P from jsonb.h:391 (PostgreSQL 16–18), jsonb.h:418 (PostgreSQL 19)
///
/// ```text
/// #define PG_GETARG_JSONB_P( x ) DatumGetJsonbP ( PG_GETARG_DATUM ( x ) )
/// ```
///
///
/// Rust callers supply 2 arguments: the 1 original C parameter, followed by explicit caller-scope operands in this order: `fcinfo`. Each operand must preserve its C type and place requirements.
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! PG_GETARG_JSONB_P {
    ($x:expr, $fcinfo:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(feature = "pg15")]
/// C macro PG_GETARG_JSONB_P_COPY from jsonb.h:75 (PostgreSQL 15)
///
/// ```text
/// #define PG_GETARG_JSONB_P_COPY( x ) DatumGetJsonbPCopy ( PG_GETARG_DATUM ( x ) )
/// ```
///
///
/// Rust callers supply 2 arguments: the 1 original C parameter, followed by explicit caller-scope operands in this order: `fcinfo`. Each operand must preserve its C type and place requirements.
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Conversions involving floats reject nonfinite or out-of-range integer results; conversions into Rust enums reject values without a represented discriminant. Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! PG_GETARG_JSONB_P_COPY {
    ($x:expr, $fcinfo:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(any(feature = "pg16", feature = "pg17", feature = "pg18", feature = "pg19"))]
/// C macro PG_GETARG_JSONB_P_COPY from jsonb.h:392 (PostgreSQL 16–18), jsonb.h:419 (PostgreSQL 19)
///
/// ```text
/// #define PG_GETARG_JSONB_P_COPY( x ) DatumGetJsonbPCopy ( PG_GETARG_DATUM ( x ) )
/// ```
///
///
/// Rust callers supply 2 arguments: the 1 original C parameter, followed by explicit caller-scope operands in this order: `fcinfo`. Each operand must preserve its C type and place requirements.
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! PG_GETARG_JSONB_P_COPY {
    ($x:expr, $fcinfo:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(any(feature = "pg15", feature = "pg19"))]
/// C macro PG_RETURN_JSONB_P from jsonb.h:76 (PostgreSQL 15), jsonb.h:420 (PostgreSQL 19)
///
/// ```text
/// #define PG_RETURN_JSONB_P( x ) PG_RETURN_POINTER ( x )
/// ```
///
///
/// C return statements in this macro exit the enclosing Rust function or closure. Call it directly, without an outer `return`. The enclosing result must have an unambiguous C identity; otherwise use `@__pgrx_c_return_as [CMarker];` before the arguments to specify the original C function's return type. Return conversion uses C assignment rules, including truncation and pointer qualification. Rust caller cleanup follows normal Rust return behavior. Pointer access and native calls keep their usual caller safety obligations.
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Conversions involving floats reject nonfinite or out-of-range integer results; conversions into Rust enums reject values without a represented discriminant. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! PG_RETURN_JSONB_P {
    ($x:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
    (@__pgrx_c_return_as [$__pgrx_c_return:ty]; $x:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(any(feature = "pg16", feature = "pg17", feature = "pg18"))]
/// C macro PG_RETURN_JSONB_P from jsonb.h:393 (PostgreSQL 16–18)
///
/// ```text
/// #define PG_RETURN_JSONB_P( x ) PG_RETURN_POINTER ( x )
/// ```
///
///
/// C return statements in this macro exit the enclosing Rust function or closure. Call it directly, without an outer `return`. The enclosing result must have an unambiguous C identity; otherwise use `@__pgrx_c_return_as [CMarker];` before the arguments to specify the original C function's return type. Return conversion uses C assignment rules, including truncation and pointer qualification. Rust caller cleanup follows normal Rust return behavior. Pointer access and native calls keep their usual caller safety obligations.
///
/// # Safety
///
/// Preserve each operand's original C identity; a Rust alias or bindgen constant's storage type may differ from its C expression type. For pointer or place operations, the caller must establish provenance, allocation bounds, alignment, initialization, valid values, lifetimes and aliasing required by the original C operation. Mutation requires writable storage. Native calls and globals require the permitted PostgreSQL backend thread, valid PostgreSQL resource ownership and the original function's preconditions. Generated guards preserve error boundaries; they do not prove these obligations.
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! PG_RETURN_JSONB_P {
    ($x:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
    (@__pgrx_c_return_as [$__pgrx_c_return:ty]; $x:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
pub use DatumGetJsonbP;
pub use DatumGetJsonbPCopy;
pub use IsAJsonbScalar;
pub use JB_ROOT_COUNT;
pub use JB_ROOT_IS_ARRAY;
pub use JB_ROOT_IS_OBJECT;
pub use JB_ROOT_IS_SCALAR;
pub use JBE_ADVANCE_OFFSET;
pub use JBE_HAS_OFF;
pub use JBE_ISBOOL;
pub use JBE_ISBOOL_FALSE;
pub use JBE_ISBOOL_TRUE;
pub use JBE_ISCONTAINER;
pub use JBE_ISNULL;
pub use JBE_ISNUMERIC;
pub use JBE_ISSTRING;
pub use JBE_OFFLENFLD;
pub use JsonContainerIsArray;
pub use JsonContainerIsObject;
pub use JsonContainerIsScalar;
pub use JsonContainerSize;
pub use JsonbPGetDatum;
pub use PG_GETARG_JSONB_P;
pub use PG_GETARG_JSONB_P_COPY;
pub use PG_RETURN_JSONB_P;
