// Automatically generated by pgrx-c-macros for documentation. Do not hand-edit.
// C macros from pgstat_kind.h.

#[cfg(any(feature = "pg18", feature = "pg19"))]
/// Typed call adapter for C inline function pgstat_is_kind_builtin from pgstat_kind.h:60 (PostgreSQL 18), pgstat_kind.h:61 (PostgreSQL 19)
///
/// ```c
/// static inline bool
/// pgstat_is_kind_builtin(PgStat_Kind kind)
/// {
/// 	return kind >= PGSTAT_KIND_BUILTIN_MIN && kind <= PGSTAT_KIND_BUILTIN_MAX;
/// }
/// ```
///
///
#[doc = crate::__pgrx_c_doc_inline_call!()]
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! pgstat_is_kind_builtin {
    ($kind:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(any(feature = "pg18", feature = "pg19"))]
/// Typed call adapter for C inline function pgstat_is_kind_custom from pgstat_kind.h:66 (PostgreSQL 18), pgstat_kind.h:67 (PostgreSQL 19)
///
/// ```c
/// static inline bool
/// pgstat_is_kind_custom(PgStat_Kind kind)
/// {
/// 	return kind >= PGSTAT_KIND_CUSTOM_MIN && kind <= PGSTAT_KIND_CUSTOM_MAX;
/// }
/// ```
///
///
#[doc = crate::__pgrx_c_doc_inline_call!()]
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! pgstat_is_kind_custom {
    ($kind:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(any(feature = "pg18", feature = "pg19"))]
pub use pgstat_is_kind_builtin;
#[cfg(any(feature = "pg18", feature = "pg19"))]
pub use pgstat_is_kind_custom;
