// Automatically generated by pgrx-c-macros for documentation. Do not hand-edit.
// C macros from queryjumble.h.

#[cfg(feature = "pg15")]
/// C inline function IsQueryIdEnabled from queryjumble.h:78 (PostgreSQL 15)
///
/// ```c
/// static inline bool
/// IsQueryIdEnabled(void)
/// {
/// 	if (compute_query_id == COMPUTE_QUERY_ID_OFF)
/// 		return false;
/// 	if (compute_query_id == COMPUTE_QUERY_ID_ON)
/// 		return true;
/// 	return query_id_enabled;
/// }
/// ```
///
///
#[doc = crate::__pgrx_c_doc_inline_body!()]
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
#[macro_export]
macro_rules! IsQueryIdEnabled {
    () => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(feature = "pg15")]
pub use IsQueryIdEnabled;
