// Automatically generated by pgrx-c-macros for documentation. Do not hand-edit.
// C macros from rangetypes.h.

#[cfg(feature = "pg15")]
/// C macro DatumGetRangeTypeP from rangetypes.h:73 (PostgreSQL 15)
///
/// ```text
/// #define DatumGetRangeTypeP( X ) ( ( RangeType * ) PG_DETOAST_DATUM ( X ) )
/// ```
///
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
///
/// # Panics
///
/// Conversions involving floats reject nonfinite or out-of-range integer results; conversions into Rust enums reject values without a represented discriminant. Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! DatumGetRangeTypeP {
    ($X:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(any(feature = "pg16", feature = "pg17", feature = "pg18", feature = "pg19"))]
/// Typed call adapter for C inline function DatumGetRangeTypeP from rangetypes.h:73 (PostgreSQL 16–19)
///
/// ```c
/// static inline RangeType *
/// DatumGetRangeTypeP(Datum X)
/// {
/// 	return (RangeType *) PG_DETOAST_DATUM(X);
/// }
/// ```
///
///
#[doc = crate::__pgrx_c_doc_inline_call!()]
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! DatumGetRangeTypeP {
    ($X:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(feature = "pg15")]
/// C macro DatumGetRangeTypePCopy from rangetypes.h:74 (PostgreSQL 15)
///
/// ```text
/// #define DatumGetRangeTypePCopy( X ) ( ( RangeType * ) PG_DETOAST_DATUM_COPY ( X ) )
/// ```
///
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
///
/// # Panics
///
/// Conversions involving floats reject nonfinite or out-of-range integer results; conversions into Rust enums reject values without a represented discriminant. Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! DatumGetRangeTypePCopy {
    ($X:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(any(feature = "pg16", feature = "pg17", feature = "pg18", feature = "pg19"))]
/// Typed call adapter for C inline function DatumGetRangeTypePCopy from rangetypes.h:79 (PostgreSQL 16–19)
///
/// ```c
/// static inline RangeType *
/// DatumGetRangeTypePCopy(Datum X)
/// {
/// 	return (RangeType *) PG_DETOAST_DATUM_COPY(X);
/// }
/// ```
///
///
#[doc = crate::__pgrx_c_doc_inline_call!()]
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! DatumGetRangeTypePCopy {
    ($X:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(feature = "pg15")]
/// C macro PG_GETARG_RANGE_P from rangetypes.h:76 (PostgreSQL 15)
///
/// ```text
/// #define PG_GETARG_RANGE_P( n ) DatumGetRangeTypeP ( PG_GETARG_DATUM ( n ) )
/// ```
///
///
/// Rust callers supply 2 arguments: the 1 original C parameter, followed by explicit caller-scope operands in this order: `fcinfo`. Each operand must preserve its C type and place requirements.
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
///
/// # Panics
///
/// Conversions involving floats reject nonfinite or out-of-range integer results; conversions into Rust enums reject values without a represented discriminant. Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! PG_GETARG_RANGE_P {
    ($n:expr, $fcinfo:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(any(feature = "pg16", feature = "pg17", feature = "pg18", feature = "pg19"))]
/// C macro PG_GETARG_RANGE_P from rangetypes.h:91 (PostgreSQL 16–19)
///
/// ```text
/// #define PG_GETARG_RANGE_P( n ) DatumGetRangeTypeP ( PG_GETARG_DATUM ( n ) )
/// ```
///
///
/// Rust callers supply 2 arguments: the 1 original C parameter, followed by explicit caller-scope operands in this order: `fcinfo`. Each operand must preserve its C type and place requirements.
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! PG_GETARG_RANGE_P {
    ($n:expr, $fcinfo:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(feature = "pg15")]
/// C macro PG_GETARG_RANGE_P_COPY from rangetypes.h:77 (PostgreSQL 15)
///
/// ```text
/// #define PG_GETARG_RANGE_P_COPY( n ) DatumGetRangeTypePCopy ( PG_GETARG_DATUM ( n ) )
/// ```
///
///
/// Rust callers supply 2 arguments: the 1 original C parameter, followed by explicit caller-scope operands in this order: `fcinfo`. Each operand must preserve its C type and place requirements.
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
///
/// # Panics
///
/// Conversions involving floats reject nonfinite or out-of-range integer results; conversions into Rust enums reject values without a represented discriminant. Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! PG_GETARG_RANGE_P_COPY {
    ($n:expr, $fcinfo:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(any(feature = "pg16", feature = "pg17", feature = "pg18", feature = "pg19"))]
/// C macro PG_GETARG_RANGE_P_COPY from rangetypes.h:92 (PostgreSQL 16–19)
///
/// ```text
/// #define PG_GETARG_RANGE_P_COPY( n ) DatumGetRangeTypePCopy ( PG_GETARG_DATUM ( n ) )
/// ```
///
///
/// Rust callers supply 2 arguments: the 1 original C parameter, followed by explicit caller-scope operands in this order: `fcinfo`. Each operand must preserve its C type and place requirements.
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! PG_GETARG_RANGE_P_COPY {
    ($n:expr, $fcinfo:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(feature = "pg15")]
/// C macro PG_RETURN_RANGE_P from rangetypes.h:78 (PostgreSQL 15)
///
/// ```text
/// #define PG_RETURN_RANGE_P( x ) return RangeTypePGetDatum ( x )
/// ```
///
///
#[doc = crate::__pgrx_c_doc_caller_returns!()]
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
///
/// # Panics
///
/// Conversions involving floats reject nonfinite or out-of-range integer results; conversions into Rust enums reject values without a represented discriminant. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! PG_RETURN_RANGE_P {
    ($x:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
    (@__pgrx_c_return_as [$__pgrx_c_return:ty]; $x:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(any(feature = "pg16", feature = "pg17", feature = "pg18", feature = "pg19"))]
/// C macro PG_RETURN_RANGE_P from rangetypes.h:93 (PostgreSQL 16–19)
///
/// ```text
/// #define PG_RETURN_RANGE_P( x ) return RangeTypePGetDatum ( x )
/// ```
///
///
#[doc = crate::__pgrx_c_doc_caller_returns!()]
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! PG_RETURN_RANGE_P {
    ($x:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
    (@__pgrx_c_return_as [$__pgrx_c_return:ty]; $x:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
/// C macro RANGE_HAS_LBOUND from rangetypes.h:48 (PostgreSQL 15–19)
///
/// ```text
/// #define RANGE_HAS_LBOUND( flags ) ( ! ( ( flags ) & ( RANGE_EMPTY | RANGE_LB_NULL | RANGE_LB_INF ) ) )
/// ```
///
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
#[macro_export]
macro_rules! RANGE_HAS_LBOUND {
    ($flags:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
/// C macro RANGE_HAS_UBOUND from rangetypes.h:52 (PostgreSQL 15–19)
///
/// ```text
/// #define RANGE_HAS_UBOUND( flags ) ( ! ( ( flags ) & ( RANGE_EMPTY | RANGE_UB_NULL | RANGE_UB_INF ) ) )
/// ```
///
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
#[macro_export]
macro_rules! RANGE_HAS_UBOUND {
    ($flags:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
/// C macro RangeIsEmpty from rangetypes.h:56 (PostgreSQL 15–19)
///
/// ```text
/// #define RangeIsEmpty( r ) ( ( range_get_flags ( r ) & RANGE_EMPTY ) != 0 )
/// ```
///
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! RangeIsEmpty {
    ($r:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
/// C macro RangeIsOrContainsEmpty from rangetypes.h:57 (PostgreSQL 15–19)
///
/// ```text
/// #define RangeIsOrContainsEmpty( r ) ( ( range_get_flags ( r ) & ( RANGE_EMPTY | RANGE_CONTAIN_EMPTY ) ) != 0 )
/// ```
///
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! RangeIsOrContainsEmpty {
    ($r:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
/// C macro RangeTypeGetOid from rangetypes.h:35 (PostgreSQL 15–19)
///
/// ```text
/// #define RangeTypeGetOid( r ) ( ( r ) -> rangetypid )
/// ```
///
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
#[macro_export]
macro_rules! RangeTypeGetOid {
    ($r:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(feature = "pg15")]
/// C macro RangeTypePGetDatum from rangetypes.h:75 (PostgreSQL 15)
///
/// ```text
/// #define RangeTypePGetDatum( X ) PointerGetDatum ( X )
/// ```
///
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
///
/// # Panics
///
/// Conversions involving floats reject nonfinite or out-of-range integer results; conversions into Rust enums reject values without a represented discriminant. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! RangeTypePGetDatum {
    ($X:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(any(feature = "pg16", feature = "pg17", feature = "pg18"))]
/// C inline function RangeTypePGetDatum from rangetypes.h:85 (PostgreSQL 16–18)
///
/// ```c
/// static inline Datum
/// RangeTypePGetDatum(const RangeType *X)
/// {
/// 	return PointerGetDatum(X);
/// }
/// ```
///
///
#[doc = crate::__pgrx_c_doc_inline_body!()]
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! RangeTypePGetDatum {
    ($X:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
#[cfg(feature = "pg19")]
/// Typed call adapter for C inline function RangeTypePGetDatum from rangetypes.h:85 (PostgreSQL 19)
///
/// ```c
/// static inline Datum
/// RangeTypePGetDatum(const RangeType *X)
/// {
/// 	return PointerGetDatum(X);
/// }
/// ```
///
///
#[doc = crate::__pgrx_c_doc_inline_call!()]
///
/// # Safety
///
#[doc = crate::__pgrx_c_doc_safety!()]
///
/// # Panics
///
/// Indirect calls reject null function pointers; guarded native calls reject the wrong PostgreSQL thread and propagate PostgreSQL errors. These checks apply to the operand types selected by this invocation. A Rust panic is converted to PostgreSQL ERROR when it reaches a pgrx extension entry guard; otherwise normal Rust panic behavior applies.
#[macro_export]
macro_rules! RangeTypePGetDatum {
    ($X:expr $(,)?) => {
        $crate::__pgrx_c_documentation_shell!()
    };
}
pub use DatumGetRangeTypeP;
pub use DatumGetRangeTypePCopy;
pub use PG_GETARG_RANGE_P;
pub use PG_GETARG_RANGE_P_COPY;
pub use PG_RETURN_RANGE_P;
pub use RANGE_HAS_LBOUND;
pub use RANGE_HAS_UBOUND;
pub use RangeIsEmpty;
pub use RangeIsOrContainsEmpty;
pub use RangeTypeGetOid;
pub use RangeTypePGetDatum;
