/* Automatically generated by pgrx-c-macros. Do not hand-edit.

This code is generated for documentation purposes, so that it is easy to reference on docs.rs. C macros and their support code are regenerated for your build of pgrx, and your Postgres configuration may differ.
*/
// Shared generated C macro support.

/// Original compiler type-operator alignments; these may exceed record storage alignment.
#[doc(hidden)]
#[allow(non_upper_case_globals)]
pub mod __pgrx_c_alignment {
    /// Verified C scalar and array alignment for CBool, in bytes.
    pub const CBool: (usize, usize) = (1, 1);
    /// Verified C scalar and array alignment for CChar, in bytes.
    pub const CChar: (usize, usize) = (1, 1);
    /// Verified C scalar and array alignment for CSignedChar, in bytes.
    pub const CSignedChar: (usize, usize) = (1, 1);
    /// Verified C scalar and array alignment for CUnsignedChar, in bytes.
    pub const CUnsignedChar: (usize, usize) = (1, 1);
    /// Verified C scalar and array alignment for CShort, in bytes.
    pub const CShort: (usize, usize) = (2, 2);
    /// Verified C scalar and array alignment for CUnsignedShort, in bytes.
    pub const CUnsignedShort: (usize, usize) = (2, 2);
    /// Verified C scalar and array alignment for CInt, in bytes.
    pub const CInt: (usize, usize) = (4, 4);
    /// Verified C scalar and array alignment for CUnsignedInt, in bytes.
    pub const CUnsignedInt: (usize, usize) = (4, 4);
    /// Verified C scalar and array alignment for CLong, in bytes.
    pub const CLong: (usize, usize) = (8, 8);
    /// Verified C scalar and array alignment for CUnsignedLong, in bytes.
    pub const CUnsignedLong: (usize, usize) = (8, 8);
    /// Verified C scalar and array alignment for CLongLong, in bytes.
    pub const CLongLong: (usize, usize) = (8, 8);
    /// Verified C scalar and array alignment for CUnsignedLongLong, in bytes.
    pub const CUnsignedLongLong: (usize, usize) = (8, 8);
    /// Verified C scalar and array alignment for CInt128, in bytes.
    pub const CInt128: (usize, usize) = (16, 16);
    /// Verified C scalar and array alignment for CUnsignedInt128, in bytes.
    pub const CUnsignedInt128: (usize, usize) = (16, 16);
    /// Verified C scalar and array alignment for CFloat32, in bytes.
    pub const CFloat32: (usize, usize) = (4, 4);
    /// Verified C scalar and array alignment for CFloat64, in bytes.
    pub const CFloat64: (usize, usize) = (8, 8);
    /// Verified C scalar and array alignment for CPointer, in bytes.
    pub const CPointer: (usize, usize) = (8, 8);
    /// Verified C scalar and array alignment for CFunctionPointer, in bytes.
    pub const CFunctionPointer: (usize, usize) = (8, 8);
}
