name: verify package can build

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  TOOL_DIR: ./tools
  PG_VER: 14

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "v1-pgrx--package-test"

      - name: Install Postgres deps
        run: |
          sudo apt-get update -y -qq --fix-missing
          sudo apt-get install -y postgresql-server-dev-$PG_VER

      - name: Rustup
        run: $TOOL_DIR/rustup.sh nightly

      - name: Install cargo pgrx
        run: cargo +nightly install --path cargo-pgrx --debug

      - name: cargo pgrx init
        run: cargo +nightly pgrx init "--pg$PG_VER=$(which pg_config)"

      - name: Test pgrx can be packaged as a new version
        run: |
          ./update-versions.sh 0.0.999-rc.999 && \
              cargo +nightly package \
                  --workspace -Zpackage-workspace \
                  --allow-dirty \
                  --features "pg$PG_VER"
