name: Run PGX tests

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  pgx_tests:
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, 'nogha')"

    strategy:
      matrix:
        version: ["postgres-10", "postgres-11", "postgres-12", "postgres-13", "postgres-14"]
        os: ["ubuntu-latest"]

    steps:
    - uses: actions/checkout@v2

    - name: Get cargo version
      run: cargo --version

    # Ubuntu system dependencies for Postgres
    - name: Remove old postgres
      run: sudo apt remove -y postgres*
